import type { MetadataRoute } from "next";
import { SITE_NAME } from "@/lib/site";

export const dynamic = "force-static";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE_NAME,
    short_name: "Islamic Front",
    description:
      "Community welfare, Islamic learning and student guidance for Mangalagiri.",
    start_url: "/",
    display: "standalone",
    background_color: "#faf6ee",
    theme_color: "#0d3b1e",
    lang: "te",
    dir: "ltr",
    categories: ["education", "lifestyle"],
    /* Generated by scripts/generate-icons.mjs. These slots used to point at
       the full-resolution source art -- 170 KB for the 192px icon and 1.08 MB
       for the 512px one -- which browsers fetch during page load. */
    icons: [
      { src: "/assets/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/assets/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/assets/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
