/* The site's lessons: the ones extracted from the legacy static site plus the
   ones written for this site.

   Consumers import from here, never from ./lessons directly, because that file
   is regenerated by scripts/extract-lessons.mjs and knows nothing about the
   authored set. */
/* Extensions are explicit here on purpose. scripts/build-search-index.mjs
   loads this module with node --experimental-strip-types, and Node's ESM
   resolver does not guess extensions, so "./lessons" fails there while
   resolving fine through the bundler. */
import { lessons as generated, type Lesson } from "./lessons.ts";
import { authoredLessons } from "./lessons-authored.ts";

export type { Bi, Lesson, LessonSection, QuizItem } from "./lessons.ts";

/* Authored lessons win over generated ones on the same portal/slug.

   The lessons extracted from the legacy site are short -- a median of 77 words
   for learn-arabic against 280 or more for one written here -- so rewriting one
   means replacing it, not adding a second route beside it. Writing the
   replacement into lessons.ts is not an option, since extract-lessons.mjs
   regenerates that file wholesale.

   Order is preserved: a replacement keeps the generated lesson's position in
   the portal, so the sequence a reader sees does not shuffle when one is
   rewritten. */
const authoredBySlug = new Map(authoredLessons.map((l) => [`${l.portal}/${l.slug}`, l]));
const replaced = new Set<string>();

export const lessons: Lesson[] = [
  ...generated.map((l) => {
    const key = `${l.portal}/${l.slug}`;
    const override = authoredBySlug.get(key);
    if (!override) return l;
    replaced.add(key);
    return override;
  }),
  ...authoredLessons.filter((l) => !replaced.has(`${l.portal}/${l.slug}`)),
];

/* Two authored lessons sharing a route would silently drop one. */
const seen = new Set<string>();
for (const l of authoredLessons) {
  const key = `${l.portal}/${l.slug}`;
  if (seen.has(key)) throw new Error(`Duplicate authored lesson route: ${key}`);
  seen.add(key);
}

export const lessonsByPortal = (portal: string) => lessons.filter((l) => l.portal === portal);

export const findLesson = (portal: string, slug: string) =>
  lessons.find((l) => l.portal === portal && l.slug === slug) ?? null;
