/* The site's lessons: the ones extracted from the legacy static site plus the
   ones written for this site.

   Consumers import from here, never from ./lessons directly, because that file
   is regenerated by scripts/extract-lessons.mjs and knows nothing about the
   authored set. */
import { lessons as generated, type Lesson } from "./lessons";
import { authoredLessons } from "./lessons-authored";

export type { Bi, Lesson, LessonSection, QuizItem } from "./lessons";

export const lessons: Lesson[] = [...generated, ...authoredLessons];

/* A duplicate slug within a portal would give two lessons the same URL, and
   generateStaticParams would emit it twice. Cheap to check, and it fails the
   build rather than shipping a broken route. */
const seen = new Set<string>();
for (const l of lessons) {
  const key = `${l.portal}/${l.slug}`;
  if (seen.has(key)) throw new Error(`Duplicate lesson route: ${key}`);
  seen.add(key);
}

export const lessonsByPortal = (portal: string) => lessons.filter((l) => l.portal === portal);

export const findLesson = (portal: string, slug: string) =>
  lessons.find((l) => l.portal === portal && l.slug === slug) ?? null;
