/* AUTO-GENERATED by scripts/build-assessment-bank.mjs — do not edit by hand.

   The end-of-portal assessment: up to 12 questions per portal, drawn from
   the lessons' own quizzes and section checks, spread across the lessons so the
   set covers the course rather than one part of it.

   learn-quran 12, learn-salah 12, seerah 12, islamic-history 12, kids-islam 12, learn-arabic 12, learn-urdu 12, hadith 12, hajj-umrah 12, names-of-allah 12, islamic-calendar 12, special-prayers 12, womens-guidance 10. */

export type Bi = { te: string; en: string };

export type AssessmentQuestion = {
  q: Bi;
  options: Bi[];
  answer: number;
  /** Which lesson it came from, so a wrong answer can point somewhere. */
  from: { slug: string; title: Bi };
};

const bank: Record<string, AssessmentQuestion[]> = {
 "learn-quran": [
  {
   "q": {
    "te": "ఖురాన్‌లో ఎన్ని సూరాలు?",
    "en": "How many surahs are in the Quran?"
   },
   "options": [
    {
     "te": "114",
     "en": "114"
    },
    {
     "te": "30",
     "en": "30"
    },
    {
     "te": "99",
     "en": "99"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "whatis",
    "title": {
     "te": "స్థాయి 1 — ఖురాన్ అంటే ఏమిటి",
     "en": "Level 1 — What the Quran is"
    }
   }
  },
  {
   "q": {
    "te": "కొత్తవారు ఎక్కడ నుండి మొదలుపెట్టాలి?",
    "en": "Where should a beginner start?"
   },
   "options": [
    {
     "te": "జుజ్ అమ్మ — చివరి భాగం",
     "en": "Juz Amma, the last part"
    },
    {
     "te": "సూరా అల్-బఖరా",
     "en": "Surah al-Baqarah"
    },
    {
     "te": "మధ్య నుండి",
     "en": "From the middle"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "begin",
    "title": {
     "te": "స్థాయి 2 — చదవడం ఎలా మొదలుపెట్టాలి",
     "en": "Level 2 — How to begin reading"
    }
   }
  },
  {
   "q": {
    "te": "నూన్ సాకినా తర్వాత ب వస్తే ఏ నియమం?",
    "en": "Which rule applies when a ba follows noon sakinah?"
   },
   "options": [
    {
     "te": "ఇఖ్లాబ్ — నూన్ 'మ్'గా మారుతుంది",
     "en": "Iqlab: the noon becomes a meem"
    },
    {
     "te": "ఇజ్‌హార్",
     "en": "Izhar"
    },
    {
     "te": "ఖల్‌ఖలా",
     "en": "Qalqalah"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tajweed",
    "title": {
     "te": "స్థాయి 3 — తజ్వీద్",
     "en": "Level 3 — Tajweed"
    }
   }
  },
  {
   "q": {
    "te": "సూచించబడిన పునరావృత్తి నిష్పత్తి ఏమిటి?",
    "en": "What revision ratio is suggested?"
   },
   "options": [
    {
     "te": "కొత్తదానికి 1, పాతదానికి 3-4",
     "en": "One part new to three or four parts old"
    },
    {
     "te": "కొత్తదానికి 4, పాతదానికి 1",
     "en": "Four parts new to one part old"
    },
    {
     "te": "పునరావృత్తి అవసరం లేదు",
     "en": "No revision needed"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "hifz",
    "title": {
     "te": "స్థాయి 4 — హిఫ్జ్: కంఠస్థం",
     "en": "Level 4 — Hifz: memorising"
    }
   }
  },
  {
   "q": {
    "te": "'అస్బాబ్ అన్-నుజూల్' అంటే ఏమిటి?",
    "en": "What is asbab al-nuzul?"
   },
   "options": [
    {
     "te": "ఆయతులు అవతరించిన సందర్భాలు",
     "en": "The circumstances in which verses were revealed"
    },
    {
     "te": "ఆయతుల సంఖ్య",
     "en": "The number of verses"
    },
    {
     "te": "పఠన నియమాలు",
     "en": "The rules of recitation"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tafseer",
    "title": {
     "te": "స్థాయి 5 — తఫ్సీర్: అర్థం చేసుకోవడం",
     "en": "Level 5 — Tafsir: understanding"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 73:4 ఏమి ఆదేశిస్తుంది?",
    "en": "What does Quran 73:4 instruct?"
   },
   "options": [
    {
     "te": "తర్తీల్‌తో చదవమని",
     "en": "To recite with tartil"
    },
    {
     "te": "వేగంగా చదవమని",
     "en": "To recite quickly"
    },
    {
     "te": "మౌనంగా చదవమని",
     "en": "To recite silently"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "adab",
    "title": {
     "te": "స్థాయి 6 — ఖురాన్‌తో జీవించడం",
     "en": "Level 6 — Living with the Quran"
    }
   }
  },
  {
   "q": {
    "te": "'ఇల్మ్' ఏ మూలం నుండి?",
    "en": "Which root does ilm come from?"
   },
   "options": [
    {
     "te": "ఎ-ల-మ్",
     "en": "a-l-m"
    },
    {
     "te": "ఎ-మ్-ల్",
     "en": "a-m-l"
    },
    {
     "te": "ఎ-ల-య్",
     "en": "a-l-y"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "words",
    "title": {
     "te": "స్థాయి 7 — ఖురాన్ పదాలను అర్థం చేసుకోవడం",
     "en": "Level 7 — Understanding Quranic words"
    }
   }
  },
  {
   "q": {
    "te": "రోజుకు ఎన్ని పేజీలు చదివితే ఏడాదిలో పూర్తవుతుంది?",
    "en": "How many pages a day completes the Quran in a year?"
   },
   "options": [
    {
     "te": "నాలుగు",
     "en": "Four"
    },
    {
     "te": "ఇరవై",
     "en": "Twenty"
    },
    {
     "te": "ఒకటి",
     "en": "One"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily-quran",
    "title": {
     "te": "స్థాయి 8 — రోజువారీ అలవాటు",
     "en": "Level 8 — A daily habit"
    }
   }
  },
  {
   "q": {
    "te": "30 జుజ్‌లుగా విభజన ఏమిటి?",
    "en": "What is the division into 30 juz?"
   },
   "options": [
    {
     "te": "తర్వాత చేసిన ఆచరణాత్మక ఏర్పాటు",
     "en": "A later practical arrangement"
    },
    {
     "te": "అవతరణలో భాగం",
     "en": "Part of the revelation"
    },
    {
     "te": "ఉస్మాన్ (ర/అ) ఆదేశం",
     "en": "An instruction of Uthman (RA)"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "whatis",
    "title": {
     "te": "స్థాయి 1 — ఖురాన్ అంటే ఏమిటి",
     "en": "Level 1 — What the Quran is"
    }
   }
  },
  {
   "q": {
    "te": "'తలఖ్ఖీ' అంటే ఏమిటి?",
    "en": "What is talaqqi?"
   },
   "options": [
    {
     "te": "గురువు ముందు చదివి సరిదిద్దబడటం",
     "en": "Reciting to a teacher and being corrected"
    },
    {
     "te": "మౌనంగా చదవడం",
     "en": "Reading silently"
    },
    {
     "te": "కంఠస్థం చేయడం",
     "en": "Memorising"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "begin",
    "title": {
     "te": "స్థాయి 2 — చదవడం ఎలా మొదలుపెట్టాలి",
     "en": "Level 2 — How to begin reading"
    }
   }
  },
  {
   "q": {
    "te": "ఖల్‌ఖలా అక్షరాలను గుర్తుంచుకునే పదబంధం ఏది?",
    "en": "Which phrase remembers the qalqalah letters?"
   },
   "options": [
    {
     "te": "ఖుత్బ్ జద్",
     "en": "Qutb jad"
    },
    {
     "te": "యర్మలూన్",
     "en": "Yarmaloon"
    },
    {
     "te": "అల్‌హమ్దు",
     "en": "Alhamdu"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tajweed",
    "title": {
     "te": "స్థాయి 3 — తజ్వీద్",
     "en": "Level 3 — Tajweed"
    }
   }
  },
  {
   "q": {
    "te": "పూర్తి హిఫ్జ్ సాధారణంగా ఎంత కాలం?",
    "en": "How long does a complete hifz usually take?"
   },
   "options": [
    {
     "te": "మూడు నుండి ఐదు సంవత్సరాలు",
     "en": "Three to five years"
    },
    {
     "te": "ఆరు నెలలు",
     "en": "Six months"
    },
    {
     "te": "ఇరవై సంవత్సరాలు",
     "en": "Twenty years"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "hifz",
    "title": {
     "te": "స్థాయి 4 — హిఫ్జ్: కంఠస్థం",
     "en": "Level 4 — Hifz: memorising"
    }
   }
  }
 ],
 "learn-salah": [
  {
   "q": {
    "te": "నమాజ్ ఇస్లాంలో ఎన్నవ స్తంభం?",
    "en": "Which pillar of Islam is prayer?"
   },
   "options": [
    {
     "te": "రెండవది",
     "en": "The second"
    },
    {
     "te": "మొదటిది",
     "en": "The first"
    },
    {
     "te": "ఐదవది",
     "en": "The fifth"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "why",
    "title": {
     "te": "స్థాయి 1 — మనం ఎందుకు నమాజ్ చేస్తాం",
     "en": "Level 1 — Why we pray"
    }
   }
  },
  {
   "q": {
    "te": "నివాసిగా మేజోళ్ళపై ఎంతకాలం తుడవవచ్చు?",
    "en": "For how long may a resident wipe over socks?"
   },
   "options": [
    {
     "te": "ఒక పగలు ఒక రాత్రి",
     "en": "A day and a night"
    },
    {
     "te": "ఒక వారం",
     "en": "A week"
    },
    {
     "te": "మూడు రోజులు",
     "en": "Three days"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "wudu",
    "title": {
     "te": "స్థాయి 2 — వుజూ",
     "en": "Level 2 — Wudu"
    }
   }
  },
  {
   "q": {
    "te": "ఘుస్ల్ చెల్లడానికి ప్రధాన షరతు ఏమిటి?",
    "en": "What is the main condition for a valid ghusl?"
   },
   "options": [
    {
     "te": "శరీరమంతటికీ నీరు చేరడం",
     "en": "Water reaching the whole body"
    },
    {
     "te": "ఒక ప్రత్యేక పాత్ర వాడటం",
     "en": "Using a particular vessel"
    },
    {
     "te": "మూడుసార్లు స్నానం",
     "en": "Bathing three times"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ghusl",
    "title": {
     "te": "స్థాయి 3 — ఘుస్ల్",
     "en": "Level 3 — Ghusl"
    }
   }
  },
  {
   "q": {
    "te": "నమాజ్‌ను ఏది ప్రారంభిస్తుంది?",
    "en": "What begins the prayer?"
   },
   "options": [
    {
     "te": "తక్బీరతుల్ ఇహ్రామ్",
     "en": "The opening takbir"
    },
    {
     "te": "నియ్యత్ బిగ్గరగా చెప్పడం",
     "en": "Saying the intention aloud"
    },
    {
     "te": "సూరా అల్-ఫాతిహా",
     "en": "Surah al-Fatihah"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "howtopray",
    "title": {
     "te": "స్థాయి 4 — నమాజ్ ఎలా చేయాలి",
     "en": "Level 4 — How to pray"
    }
   }
  },
  {
   "q": {
    "te": "మఘ్రిబ్ ఎప్పుడు మొదలవుతుంది?",
    "en": "When does Maghrib begin?"
   },
   "options": [
    {
     "te": "సూర్యాస్తమయంతో",
     "en": "At sunset"
    },
    {
     "te": "ఎర్రదనం మాయమయ్యాక",
     "en": "After the redness fades"
    },
    {
     "te": "అర్ధరాత్రి",
     "en": "At midnight"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "fiveprayers",
    "title": {
     "te": "స్థాయి 5 — ఐదు నమాజులు, వాటి సమయాలు",
     "en": "Level 5 — The five prayers and their times"
    }
   }
  },
  {
   "q": {
    "te": "నమాజ్‌లో దృష్టి ఎక్కడ ఉంచాలి?",
    "en": "Where should the gaze rest in prayer?"
   },
   "options": [
    {
     "te": "సజ్దా స్థానంపై",
     "en": "At the place of prostration"
    },
    {
     "te": "పైకి ఆకాశం వైపు",
     "en": "Upward at the sky"
    },
    {
     "te": "చుట్టూ",
     "en": "Around the room"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "khushu",
    "title": {
     "te": "స్థాయి 6 — ఖుషూ: హృదయం హాజరుగా",
     "en": "Level 6 — Khushu: presence of heart"
    }
   }
  },
  {
   "q": {
    "te": "ఫజ్ర్‌కు ముందు ఎన్ని సున్నత్ రక్అత్‌లు?",
    "en": "How many sunnah units come before Fajr?"
   },
   "options": [
    {
     "te": "రెండు",
     "en": "Two"
    },
    {
     "te": "నాలుగు",
     "en": "Four"
    },
    {
     "te": "ఆరు",
     "en": "Six"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "sunnah-salah",
    "title": {
     "te": "స్థాయి 7 — సున్నత్, నఫిల్ నమాజులు",
     "en": "Level 7 — Sunnah and voluntary prayers"
    }
   }
  },
  {
   "q": {
    "te": "సజ్దాలో మోచేతులను నేలపై పెట్టడం గురించి?",
    "en": "What about resting the forearms on the ground in prostration?"
   },
   "options": [
    {
     "te": "ప్రవక్త ﷺ దీన్ని వారించారు",
     "en": "The Prophet ﷺ forbade it"
    },
    {
     "te": "అది సున్నత్",
     "en": "It is sunnah"
    },
    {
     "te": "అది తప్పనిసరి",
     "en": "It is required"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "fixing-salah",
    "title": {
     "te": "స్థాయి 8 — సాధారణ పొరపాట్లను సరిదిద్దడం",
     "en": "Level 8 — Fixing common mistakes"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 29:45 ప్రకారం నమాజ్ ఏమి చేస్తుంది?",
    "en": "According to Quran 29:45, what does prayer do?"
   },
   "options": [
    {
     "te": "అశ్లీలత, చెడు నుండి ఆపుతుంది",
     "en": "Restrains from immorality and wrongdoing"
    },
    {
     "te": "సంపదను పెంచుతుంది",
     "en": "Increases wealth"
    },
    {
     "te": "నిద్రను తగ్గిస్తుంది",
     "en": "Reduces the need for sleep"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "why",
    "title": {
     "te": "స్థాయి 1 — మనం ఎందుకు నమాజ్ చేస్తాం",
     "en": "Level 1 — Why we pray"
    }
   }
  },
  {
   "q": {
    "te": "అన్ని మజ్‌హబ్‌లూ దేన్ని వుజూ భంగపరిచేదిగా అంగీకరిస్తాయి?",
    "en": "Which do all schools agree breaks wudu?"
   },
   "options": [
    {
     "te": "గాఢ నిద్ర",
     "en": "Deep sleep"
    },
    {
     "te": "ఒంటె మాంసం",
     "en": "Camel meat"
    },
    {
     "te": "వ్యతిరేక లింగాన్ని తాకడం",
     "en": "Touching the opposite sex"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "wudu",
    "title": {
     "te": "స్థాయి 2 — వుజూ",
     "en": "Level 2 — Wudu"
    }
   }
  },
  {
   "q": {
    "te": "మహిళలు ఘుస్ల్‌కు జడ విప్పాలా?",
    "en": "Must a woman undo her braid for ghusl?"
   },
   "options": [
    {
     "te": "జనాబత్‌కు అవసరం లేదు — మూడుసార్లు నీరు పోస్తే సరిపోతుంది",
     "en": "Not for janabah; pouring water three times suffices"
    },
    {
     "te": "ఎప్పుడూ విప్పాలి",
     "en": "Always"
    },
    {
     "te": "ఎప్పుడూ విప్పకూడదు",
     "en": "Never"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ghusl",
    "title": {
     "te": "స్థాయి 3 — ఘుస్ల్",
     "en": "Level 3 — Ghusl"
    }
   }
  },
  {
   "q": {
    "te": "రుకూలో ఏమి చెబుతారు?",
    "en": "What is said in the bowing?"
   },
   "options": [
    {
     "te": "సుబ్‌హాన రబ్బియల్ అజీమ్",
     "en": "Subhana rabbiy al-azeem"
    },
    {
     "te": "సుబ్‌హాన రబ్బియల్ ఆలా",
     "en": "Subhana rabbiy al-a'la"
    },
    {
     "te": "అల్‌హమ్దులిల్లాహ్",
     "en": "Alhamdulillah"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "howtopray",
    "title": {
     "te": "స్థాయి 4 — నమాజ్ ఎలా చేయాలి",
     "en": "Level 4 — How to pray"
    }
   }
  }
 ],
 "seerah": [
  {
   "q": {
    "te": "మక్కావాసులు ఆయనను ఏమని పిలిచేవారు?",
    "en": "What did the people of Makkah call him?"
   },
   "options": [
    {
     "te": "అల్-అమీన్",
     "en": "Al-Ameen"
    },
    {
     "te": "అల్-ఖాతిబ్",
     "en": "Al-Katib"
    },
    {
     "te": "అల్-మలిక్",
     "en": "Al-Malik"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "before-prophethood",
    "title": {
     "te": "స్థాయి 1 — ప్రవక్తత్వానికి ముందు",
     "en": "Level 1 — Before prophethood"
    }
   }
  },
  {
   "q": {
    "te": "మొదటి వహీ ఏ సూరాలోనిది?",
    "en": "The first revelation was from which surah?"
   },
   "options": [
    {
     "te": "అల్-అలఖ్",
     "en": "Al-Alaq"
    },
    {
     "te": "అల్-ఫాతిహా",
     "en": "Al-Fatihah"
    },
    {
     "te": "అద్-దుహా",
     "en": "Ad-Duha"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "beginning-of-revelation",
    "title": {
     "te": "స్థాయి 2 — వహీ ఆరంభం",
     "en": "Level 2 — The beginning of revelation"
    }
   }
  },
  {
   "q": {
    "te": "మక్కా కాలంలో ఎన్ని యుద్ధాలు జరిగాయి?",
    "en": "How many battles took place in the Makkan period?"
   },
   "options": [
    {
     "te": "ఒక్కటీ లేదు",
     "en": "None"
    },
    {
     "te": "మూడు",
     "en": "Three"
    },
    {
     "te": "ఒకటి",
     "en": "One"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "the-makkah-period",
    "title": {
     "te": "స్థాయి 3 — మక్కా కాలం",
     "en": "Level 3 — The Makkan period"
    }
   }
  },
  {
   "q": {
    "te": "సౌర్ గుహలో ప్రవక్త ﷺ ఏమన్నారు?",
    "en": "What did the Prophet ﷺ say in the cave of Thawr?"
   },
   "options": [
    {
     "te": "'దుఃఖించవద్దు, అల్లాహ్ మనతో ఉన్నాడు'",
     "en": "Do not grieve, Allah is with us"
    },
    {
     "te": "'మనం తిరిగి వెళదాం'",
     "en": "Let us go back"
    },
    {
     "te": "ఏమీ అనలేదు",
     "en": "Nothing"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "hijrah-and-madinah",
    "title": {
     "te": "స్థాయి 4 — హిజ్రత్, మదీనా",
     "en": "Level 4 — The Hijrah and Madinah"
    }
   }
  },
  {
   "q": {
    "te": "ఖందఖ్‌లో కందకం ఎవరి సూచన?",
    "en": "Whose idea was the trench at Khandaq?"
   },
   "options": [
    {
     "te": "సల్మాన్ ఫారిసీ (ర/అ)",
     "en": "Salman al-Farisi (RA)"
    },
    {
     "te": "ఉమర్ (ర/అ)",
     "en": "Umar (RA)"
    },
    {
     "te": "ఖాలిద్ బిన్ వలీద్",
     "en": "Khalid ibn al-Walid"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "major-events-and-battles",
    "title": {
     "te": "స్థాయి 5 — ప్రధాన సంఘటనలు",
     "en": "Level 5 — The major events"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 68:4 ఆయన గురించి ఏమి చెబుతుంది?",
    "en": "What does Quran 68:4 say about him?"
   },
   "options": [
    {
     "te": "'నీవు గొప్ప స్వభావంపై ఉన్నావు'",
     "en": "You are of a great character"
    },
    {
     "te": "'నీవు బలవంతుడివి'",
     "en": "You are strong"
    },
    {
     "te": "'నీవు ధనవంతుడివి'",
     "en": "You are wealthy"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "character-and-legacy",
    "title": {
     "te": "స్థాయి 6 — స్వభావం",
     "en": "Level 6 — His character"
    }
   }
  },
  {
   "q": {
    "te": "ఇస్లాం మొదటి ముఅజ్జిన్ ఎవరు?",
    "en": "Who was the first to call the prayer in Islam?"
   },
   "options": [
    {
     "te": "బిలాల్ (ర/అ)",
     "en": "Bilal (RA)"
    },
    {
     "te": "సల్మాన్ (ర/అ)",
     "en": "Salman (RA)"
    },
    {
     "te": "సుహైబ్ (ర/అ)",
     "en": "Suhayb (RA)"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "the-companions",
    "title": {
     "te": "స్థాయి 7 — సహాబా",
     "en": "Level 7 — The companions"
    }
   }
  },
  {
   "q": {
    "te": "'ఎవరైతే మమ్మల్ని మోసం చేస్తారో...' — ఏ సందర్భంలో?",
    "en": "Whoever deceives us is not one of us was said in what context?"
   },
   "options": [
    {
     "te": "తడి ధాన్యాన్ని దాచిన వ్యాపారి",
     "en": "A trader hiding wet grain"
    },
    {
     "te": "ఒక యుద్ధంలో",
     "en": "During a battle"
    },
    {
     "te": "ఒక ఖుత్బాలో",
     "en": "In a sermon"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "applying-the-seerah-today",
    "title": {
     "te": "స్థాయి 8 — సీరత్‌ను నేటికి తీసుకురావడం",
     "en": "Level 8 — Bringing the seerah into now"
    }
   }
  },
  {
   "q": {
    "te": "ఖదీజా (ర/అ)తో వివాహ ప్రతిపాదన ఎవరు పంపారు?",
    "en": "Who sent the proposal of marriage?"
   },
   "options": [
    {
     "te": "ఖదీజా (ర/అ) స్వయంగా",
     "en": "Khadijah (RA) herself"
    },
    {
     "te": "అబూ తాలిబ్",
     "en": "Abu Talib"
    },
    {
     "te": "ఖురైష్ నాయకులు",
     "en": "The leaders of Quraysh"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "before-prophethood",
    "title": {
     "te": "స్థాయి 1 — ప్రవక్తత్వానికి ముందు",
     "en": "Level 1 — Before prophethood"
    }
   }
  },
  {
   "q": {
    "te": "వరఖా బిన్ నౌఫల్ ఏమి చెప్పారు?",
    "en": "What did Waraqah ibn Nawfal say?"
   },
   "options": [
    {
     "te": "అది మూసా (అ)కు వచ్చిన అదే దూత",
     "en": "It was the same angel who came to Musa"
    },
    {
     "te": "అది ఒక కల",
     "en": "It was a dream"
    },
    {
     "te": "ఆయన అనారోగ్యంతో ఉన్నారు",
     "en": "He was unwell"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "beginning-of-revelation",
    "title": {
     "te": "స్థాయి 2 — వహీ ఆరంభం",
     "en": "Level 2 — The beginning of revelation"
    }
   }
  },
  {
   "q": {
    "te": "బహిష్కరణ ఎంతకాలం కొనసాగింది?",
    "en": "How long did the boycott last?"
   },
   "options": [
    {
     "te": "సుమారు మూడు సంవత్సరాలు",
     "en": "About three years"
    },
    {
     "te": "ఆరు నెలలు",
     "en": "Six months"
    },
    {
     "te": "పది సంవత్సరాలు",
     "en": "Ten years"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "the-makkah-period",
    "title": {
     "te": "స్థాయి 3 — మక్కా కాలం",
     "en": "Level 3 — The Makkan period"
    }
   }
  },
  {
   "q": {
    "te": "అఖబా ప్రతిజ్ఞలు ఎక్కడి ప్రజలవి?",
    "en": "The pledges at Aqabah were made by people of where?"
   },
   "options": [
    {
     "te": "యథ్రిబ్ (మదీనా)",
     "en": "Yathrib, later Madinah"
    },
    {
     "te": "తాయిఫ్",
     "en": "Taif"
    },
    {
     "te": "అబిసీనియా",
     "en": "Abyssinia"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "hijrah-and-madinah",
    "title": {
     "te": "స్థాయి 4 — హిజ్రత్, మదీనా",
     "en": "Level 4 — The Hijrah and Madinah"
    }
   }
  }
 ],
 "islamic-history": [
  {
   "q": {
    "te": "'జాహిలియ్యా' అనే పదం దేనికి వ్యతిరేకం?",
    "en": "The word jahiliyyah is the opposite of what?"
   },
   "options": [
    {
     "te": "హిల్మ్ — సహనం, ఆత్మనిగ్రహం",
     "en": "Hilm, forbearance and restraint"
    },
    {
     "te": "ఇల్మ్ — జ్ఞానం మాత్రమే",
     "en": "Ilm, knowledge alone"
    },
    {
     "te": "అమల్ — ఆచరణ",
     "en": "Amal, action"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "prearabia",
    "title": {
     "te": "స్థాయి 1 — ఇస్లాంకు ముందటి అరేబియా",
     "en": "Level 1 — Arabia before Islam"
    }
   }
  },
  {
   "q": {
    "te": "మొదటి వహీ ఎప్పుడు?",
    "en": "When did the first revelation come?"
   },
   "options": [
    {
     "te": "610 CE",
     "en": "610 CE"
    },
    {
     "te": "570 CE",
     "en": "570 CE"
    },
    {
     "te": "622 CE",
     "en": "622 CE"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "prophet",
    "title": {
     "te": "స్థాయి 2 — ప్రవక్త ﷺ జీవితం: ఇరవై మూడు సంవత్సరాలు",
     "en": "Level 2 — The Prophet ﷺ: twenty-three years"
    }
   }
  },
  {
   "q": {
    "te": "ప్రామాణిక ఖురాన్ పాఠాన్ని ఎవరు స్థిరపరిచారు?",
    "en": "Who fixed the standard text of the Quran?"
   },
   "options": [
    {
     "te": "ఉస్మాన్ (ర/అ)",
     "en": "Uthman (RA)"
    },
    {
     "te": "ఉమర్ (ర/అ)",
     "en": "Umar (RA)"
    },
    {
     "te": "అలీ (ర/అ)",
     "en": "Ali (RA)"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "rashidun",
    "title": {
     "te": "స్థాయి 3 — రాషిదూన్ ఖిలాఫత్",
     "en": "Level 3 — The Rashidun Caliphate"
    }
   }
  },
  {
   "q": {
    "te": "అరబిక్‌ను పరిపాలనా భాషగా చేసినది ఎవరు?",
    "en": "Who made Arabic the language of administration?"
   },
   "options": [
    {
     "te": "అబ్దుల్ మలిక్",
     "en": "Abd al-Malik"
    },
    {
     "te": "ముఆవియా",
     "en": "Mu'awiyah"
    },
    {
     "te": "యజీద్",
     "en": "Yazid"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "umayyad",
    "title": {
     "te": "స్థాయి 4 — ఉమయ్యద్ ఖిలాఫత్",
     "en": "Level 4 — The Umayyad Caliphate"
    }
   }
  },
  {
   "q": {
    "te": "బాగ్దాద్ అసలు పేరు ఏమిటి?",
    "en": "What was Baghdad's formal name?"
   },
   "options": [
    {
     "te": "మదీనతుస్ సలామ్ — శాంతి నగరం",
     "en": "Madinat as-Salam, the city of peace"
    },
    {
     "te": "మదీనతున్ నబీ",
     "en": "Madinat an-Nabi"
    },
    {
     "te": "దారుల్ హిక్మా",
     "en": "Dar al-Hikma"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "wisdom",
    "title": {
     "te": "స్థాయి 5 — అబ్బాసీ స్వర్ణయుగం",
     "en": "Level 5 — The Abbasid Golden Age"
    }
   }
  },
  {
   "q": {
    "te": "గ్రనాడా ఎప్పుడు పతనమైంది?",
    "en": "When did Granada fall?"
   },
   "options": [
    {
     "te": "1492",
     "en": "1492"
    },
    {
     "te": "1031",
     "en": "1031"
    },
    {
     "te": "711",
     "en": "711"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "andalus",
    "title": {
     "te": "స్థాయి 6 — అల్-అందలుస్: ముస్లిం స్పెయిన్",
     "en": "Level 6 — Al-Andalus: Muslim Spain"
    }
   }
  },
  {
   "q": {
    "te": "ఒట్టోమన్ సామ్రాజ్యం ఎప్పుడు మొదలైంది?",
    "en": "When did the Ottoman Empire begin?"
   },
   "options": [
    {
     "te": "1299",
     "en": "1299"
    },
    {
     "te": "1453",
     "en": "1453"
    },
    {
     "te": "1520",
     "en": "1520"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ottoman",
    "title": {
     "te": "స్థాయి 7 — ఒట్టోమన్ సామ్రాజ్యం",
     "en": "Level 7 — The Ottoman Empire"
    }
   }
  },
  {
   "q": {
    "te": "'ముఖద్దిమా' ఎవరు రాశారు?",
    "en": "Who wrote the Muqaddimah?"
   },
   "options": [
    {
     "te": "ఇబ్న్ ఖల్దూన్",
     "en": "Ibn Khaldun"
    },
    {
     "te": "ఇబ్న్ సీనా",
     "en": "Ibn Sina"
    },
    {
     "te": "అల్-రాజీ",
     "en": "Al-Razi"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "scholars",
    "title": {
     "te": "స్థాయి 8 — పండితులు, శాస్త్రవేత్తలు",
     "en": "Level 8 — The scholars and scientists"
    }
   }
  },
  {
   "q": {
    "te": "సైక్స్-పికో ఒప్పందం ఏ సంవత్సరం?",
    "en": "In what year was the Sykes-Picot agreement?"
   },
   "options": [
    {
     "te": "1916",
     "en": "1916"
    },
    {
     "te": "1857",
     "en": "1857"
    },
    {
     "te": "1924",
     "en": "1924"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "colonial",
    "title": {
     "te": "స్థాయి 9 — వలస యుగం",
     "en": "Level 9 — The colonial era"
    }
   }
  },
  {
   "q": {
    "te": "ప్రపంచ ముస్లింలలో ఎంత శాతం ఆసియా-పసిఫిక్‌లో ఉన్నారు?",
    "en": "What share of the world's Muslims live in the Asia-Pacific?"
   },
   "options": [
    {
     "te": "సుమారు అరవై శాతం",
     "en": "About sixty per cent"
    },
    {
     "te": "సుమారు పది శాతం",
     "en": "About ten per cent"
    },
    {
     "te": "సుమారు తొంభై శాతం",
     "en": "About ninety per cent"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "modern",
    "title": {
     "te": "స్థాయి 10 — నేటి ముస్లిం ప్రపంచం",
     "en": "Level 10 — The Muslim world today"
    }
   }
  },
  {
   "q": {
    "te": "మక్కాలో కాబా సంరక్షకులు ఎవరు?",
    "en": "Who were the custodians of the Kaaba in Makkah?"
   },
   "options": [
    {
     "te": "ఖురైష్",
     "en": "The Quraysh"
    },
    {
     "te": "బనూ ఇస్రాయీల్",
     "en": "The Banu Israil"
    },
    {
     "te": "బైజాంటైన్లు",
     "en": "The Byzantines"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "prearabia",
    "title": {
     "te": "స్థాయి 1 — ఇస్లాంకు ముందటి అరేబియా",
     "en": "Level 1 — Arabia before Islam"
    }
   }
  },
  {
   "q": {
    "te": "ఖందఖ్ యుద్ధంలో కందకం ఎవరి సూచన?",
    "en": "Whose suggestion was the trench at Khandaq?"
   },
   "options": [
    {
     "te": "సల్మాన్ ఫారిసీ (ర/అ)",
     "en": "Salman al-Farisi (RA)"
    },
    {
     "te": "అబూ బక్ర్ (ర/అ)",
     "en": "Abu Bakr (RA)"
    },
    {
     "te": "ఖాలిద్ బిన్ వలీద్ (ర/అ)",
     "en": "Khalid ibn al-Walid (RA)"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "prophet",
    "title": {
     "te": "స్థాయి 2 — ప్రవక్త ﷺ జీవితం: ఇరవై మూడు సంవత్సరాలు",
     "en": "Level 2 — The Prophet ﷺ: twenty-three years"
    }
   }
  }
 ],
 "kids-islam": [
  {
   "q": {
    "te": "'బిస్మిల్లాహ్' అంటే ఏమిటి?",
    "en": "What does bismillah mean?"
   },
   "options": [
    {
     "te": "అల్లాహ్ పేరుతో",
     "en": "In the name of Allah"
    },
    {
     "te": "ధన్యవాదాలు",
     "en": "Thank you"
    },
    {
     "te": "వీడ్కోలు",
     "en": "Goodbye"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "my-first-islam",
    "title": {
     "te": "స్థాయి 1 — నా మొదటి ఇస్లాం",
     "en": "Level 1 — My first Islam"
    }
   }
  },
  {
   "q": {
    "te": "త్రాసులో అత్యంత బరువైనది ఏమిటి?",
    "en": "What is heaviest on the scales?"
   },
   "options": [
    {
     "te": "మంచి నడవడిక",
     "en": "Good character"
    },
    {
     "te": "బంగారం",
     "en": "Gold"
    },
    {
     "te": "పుస్తకాలు",
     "en": "Books"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "good-manners",
    "title": {
     "te": "స్థాయి 2 — మంచి నడవడిక",
     "en": "Level 2 — Good manners"
    }
   }
  },
  {
   "q": {
    "te": "నిద్రించే ముందు ఏమి చెబుతారు?",
    "en": "What is said before sleeping?"
   },
   "options": [
    {
     "te": "బిస్మిక అల్లాహుమ్మ అమూతు వ అహ్‌యా",
     "en": "Bismika Allahumma amootu wa ahya"
    },
    {
     "te": "అల్లాహు అక్బర్",
     "en": "Allahu akbar"
    },
    {
     "te": "జజాకల్లాహు ఖైరన్",
     "en": "Jazaak Allahu khayran"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily-duas",
    "title": {
     "te": "స్థాయి 3 — రోజువారీ దుఆలు",
     "en": "Level 3 — Everyday duas"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్‌లో ఎంతమంది ప్రవక్తల పేర్లు ఉన్నాయి?",
    "en": "How many prophets are named in the Quran?"
   },
   "options": [
    {
     "te": "ఇరవై ఐదు",
     "en": "Twenty-five"
    },
    {
     "te": "ఐదు",
     "en": "Five"
    },
    {
     "te": "వంద",
     "en": "A hundred"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "stories-of-the-prophets",
    "title": {
     "te": "స్థాయి 4 — ప్రవక్తల కథలు",
     "en": "Level 4 — Stories of the prophets"
    }
   }
  },
  {
   "q": {
    "te": "సజ్దాలో ఏమవుతుంది?",
    "en": "What happens in prostration?"
   },
   "options": [
    {
     "te": "మనం అల్లాహ్‌కు అత్యంత దగ్గరగా ఉంటాం",
     "en": "We are closest to Allah"
    },
    {
     "te": "నమాజ్ ముగుస్తుంది",
     "en": "The prayer ends"
    },
    {
     "te": "మనం మాట్లాడతాం",
     "en": "We speak to each other"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "salah-and-quran-basics",
    "title": {
     "te": "స్థాయి 5 — నమాజ్, ఖురాన్ ప్రాథమికాలు",
     "en": "Level 5 — Prayer and Quran basics"
    }
   }
  },
  {
   "q": {
    "te": "ఉసామా (ర/అ) ఎన్నేళ్ళకు సేనాధిపతి అయ్యారు?",
    "en": "At what age did Usamah (RA) command an army?"
   },
   "options": [
    {
     "te": "పద్దెనిమిది",
     "en": "Eighteen"
    },
    {
     "te": "నలభై",
     "en": "Forty"
    },
    {
     "te": "ముప్ఫై",
     "en": "Thirty"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "young-muslim-leadership",
    "title": {
     "te": "స్థాయి 6 — యువ ముస్లిం నాయకత్వం",
     "en": "Level 6 — Young Muslim leadership"
    }
   }
  },
  {
   "q": {
    "te": "ప్రవక్త ﷺ ప్రకారం ఏమి మానకపోతే ఉపవాసానికి అర్థం లేదు?",
    "en": "What did the Prophet ﷺ say must also be given up?"
   },
   "options": [
    {
     "te": "అబద్ధాలు, చెడు పనులు",
     "en": "False speech and bad conduct"
    },
    {
     "te": "నిద్ర",
     "en": "Sleep"
    },
    {
     "te": "ఆట",
     "en": "Play"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ramadan-and-eid",
    "title": {
     "te": "స్థాయి 7 — రమదాన్, ఈద్",
     "en": "Level 7 — Ramadan and Eid"
    }
   }
  },
  {
   "q": {
    "te": "ప్రవక్త ﷺ ప్రకారం బలవంతుడు ఎవరు?",
    "en": "According to the Prophet ﷺ, who is strong?"
   },
   "options": [
    {
     "te": "కోపంలో తనను నిగ్రహించుకునేవాడు",
     "en": "One who controls himself when angry"
    },
    {
     "te": "కుస్తీలో గెలిచేవాడు",
     "en": "One who wins at wrestling"
    },
    {
     "te": "వేగంగా పరుగెత్తేవాడు",
     "en": "One who runs fastest"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "honesty-and-courage",
    "title": {
     "te": "స్థాయి 8 — నిజాయితీ, ధైర్యం",
     "en": "Level 8 — Honesty and courage"
    }
   }
  },
  {
   "q": {
    "te": "ఇస్లాంకు ఎన్ని స్తంభాలు?",
    "en": "How many pillars does Islam have?"
   },
   "options": [
    {
     "te": "ఐదు",
     "en": "Five"
    },
    {
     "te": "మూడు",
     "en": "Three"
    },
    {
     "te": "పది",
     "en": "Ten"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "my-first-islam",
    "title": {
     "te": "స్థాయి 1 — నా మొదటి ఇస్లాం",
     "en": "Level 1 — My first Islam"
    }
   }
  },
  {
   "q": {
    "te": "చిరునవ్వు ఏమిటని ప్రవక్త ﷺ చెప్పారు?",
    "en": "What did the Prophet ﷺ say a smile is?"
   },
   "options": [
    {
     "te": "ఒక సదఖా",
     "en": "A charity"
    },
    {
     "te": "ఒక అలవాటు",
     "en": "A habit"
    },
    {
     "te": "ఒక నియమం",
     "en": "A rule"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "good-manners",
    "title": {
     "te": "స్థాయి 2 — మంచి నడవడిక",
     "en": "Level 2 — Good manners"
    }
   }
  },
  {
   "q": {
    "te": "యూనుస్ (అ) దుఆ ఎక్కడ చేశారు?",
    "en": "Where did Yunus make his du'a?"
   },
   "options": [
    {
     "te": "ఒక పెద్ద చేప కడుపులో",
     "en": "Inside a great fish"
    },
    {
     "te": "ఒక కొండపై",
     "en": "On a mountain"
    },
    {
     "te": "ఒక మస్జిద్‌లో",
     "en": "In a mosque"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily-duas",
    "title": {
     "te": "స్థాయి 3 — రోజువారీ దుఆలు",
     "en": "Level 3 — Everyday duas"
    }
   }
  },
  {
   "q": {
    "te": "ఇబ్రాహీమ్ (అ) విగ్రహాలు పగలగొట్టిన తర్వాత గొడ్డలిని ఎక్కడ ఉంచారు?",
    "en": "Where did Ibrahim leave the axe?"
   },
   "options": [
    {
     "te": "అతిపెద్ద విగ్రహం మెడలో",
     "en": "On the neck of the biggest idol"
    },
    {
     "te": "నేలపై",
     "en": "On the ground"
    },
    {
     "te": "ఇంట్లో",
     "en": "At home"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "stories-of-the-prophets",
    "title": {
     "te": "స్థాయి 4 — ప్రవక్తల కథలు",
     "en": "Level 4 — Stories of the prophets"
    }
   }
  }
 ],
 "learn-arabic": [
  {
   "q": {
    "te": "అరబిక్‌లో ఎన్ని అక్షరాలు?",
    "en": "How many letters are in the Arabic alphabet?"
   },
   "options": [
    {
     "te": "28",
     "en": "28"
    },
    {
     "te": "26",
     "en": "26"
    },
    {
     "te": "32",
     "en": "32"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "alphabet",
    "title": {
     "te": "స్థాయి 1 — అరబిక్ అక్షరమాల",
     "en": "Level 1 — The Arabic alphabet"
    }
   }
  },
  {
   "q": {
    "te": "సుకూన్ దేన్ని సూచిస్తుంది?",
    "en": "What does sukun indicate?"
   },
   "options": [
    {
     "te": "ఆ అక్షరానికి స్వరం లేదు",
     "en": "The letter carries no vowel"
    },
    {
     "te": "అక్షరం రెట్టింపు",
     "en": "The letter is doubled"
    },
    {
     "te": "పదం ముగిసింది",
     "en": "The word has ended"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "harakat",
    "title": {
     "te": "స్థాయి 2 — హరకాత్ మరియు స్వరాలు",
     "en": "Level 2 — Harakat and vowels"
    }
   }
  },
  {
   "q": {
    "te": "క-త-బ మూలం ఏ భావనను మోస్తుంది?",
    "en": "What idea does the root k-t-b carry?"
   },
   "options": [
    {
     "te": "రాయడం",
     "en": "Writing"
    },
    {
     "te": "చదవడం",
     "en": "Reading"
    },
    {
     "te": "నడవడం",
     "en": "Walking"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "vocabulary",
    "title": {
     "te": "స్థాయి 3 — మూలాలు మరియు పదజాలం",
     "en": "Level 3 — Roots and vocabulary"
    }
   }
  },
  {
   "q": {
    "te": "'ఫీ' (లో) ఏ రకమైన పదం?",
    "en": "What kind of word is fi, meaning in?"
   },
   "options": [
    {
     "te": "హర్ఫ్ (అవ్యయం)",
     "en": "A harf, a particle"
    },
    {
     "te": "ఇస్మ్ (నామవాచకం)",
     "en": "An ism, a noun"
    },
    {
     "te": "ఫిఅల్ (క్రియ)",
     "en": "A fi'l, a verb"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "grammar",
    "title": {
     "te": "స్థాయి 4 — వ్యాకరణ ప్రాథమికాలు",
     "en": "Level 4 — Grammar basics"
    }
   }
  },
  {
   "q": {
    "te": "ఫుస్‌హా అంటే ఏమిటి?",
    "en": "What is fus-ha?"
   },
   "options": [
    {
     "te": "ప్రామాణిక అరబిక్, అన్ని అరబ్ దేశాలకూ ఉమ్మడి",
     "en": "Standard Arabic, common across the Arab world"
    },
    {
     "te": "ఈజిప్షియన్ మాండలికం",
     "en": "The Egyptian dialect"
    },
    {
     "te": "ఒక పఠన శైలి",
     "en": "A style of recitation"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "quranic",
    "title": {
     "te": "స్థాయి 5 — ఖురానిక్ అరబిక్",
     "en": "Level 5 — Quranic Arabic"
    }
   }
  },
  {
   "q": {
    "te": "'జజాకల్లాహు ఖైరన్' అంటే ఏమిటి?",
    "en": "What does jazaak Allahu khayran mean?"
   },
   "options": [
    {
     "te": "అల్లాహ్ మీకు మేలు ప్రసాదించుగాక",
     "en": "May Allah reward you with good"
    },
    {
     "te": "అల్లాహ్ కోరితే",
     "en": "If Allah wills"
    },
    {
     "te": "సర్వ స్తుతి అల్లాహ్‌కే",
     "en": "All praise is for Allah"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily",
    "title": {
     "te": "స్థాయి 6 — రోజువారీ అరబిక్",
     "en": "Level 6 — Everyday Arabic"
    }
   }
  },
  {
   "q": {
    "te": "సూర్య అక్షరం ముందు 'అల్' లోని ల ఏమవుతుంది?",
    "en": "What happens to the laam of al before a sun letter?"
   },
   "options": [
    {
     "te": "మౌనమై తర్వాతి అక్షరం రెట్టింపు అవుతుంది",
     "en": "It goes silent and the next letter doubles"
    },
    {
     "te": "స్పష్టంగా వినిపిస్తుంది",
     "en": "It is pronounced clearly"
    },
    {
     "te": "అది పూర్తిగా తొలగిపోతుంది",
     "en": "It is dropped from the writing"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "alphabet",
    "title": {
     "te": "స్థాయి 1 — అరబిక్ అక్షరమాల",
     "en": "Level 1 — The Arabic alphabet"
    }
   }
  },
  {
   "q": {
    "te": "తన్వీన్ ఏమి చేరుస్తుంది?",
    "en": "What does tanween add?"
   },
   "options": [
    {
     "te": "చివర 'న్' శబ్దం",
     "en": "An n sound at the end"
    },
    {
     "te": "అక్షరాన్ని రెట్టింపు చేస్తుంది",
     "en": "It doubles the letter"
    },
    {
     "te": "స్వరాన్ని తొలగిస్తుంది",
     "en": "It removes the vowel"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "harakat",
    "title": {
     "te": "స్థాయి 2 — హరకాత్ మరియు స్వరాలు",
     "en": "Level 2 — Harakat and vowels"
    }
   }
  },
  {
   "q": {
    "te": "'రహ్మాన్' ఏ మూలం నుండి వచ్చింది?",
    "en": "Which root does Rahman come from?"
   },
   "options": [
    {
     "te": "ర-హ-మ్",
     "en": "r-h-m"
    },
    {
     "te": "ర-హ-న్",
     "en": "r-h-n"
    },
    {
     "te": "ర-మ్-హ్",
     "en": "r-m-h"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "vocabulary",
    "title": {
     "te": "స్థాయి 3 — మూలాలు మరియు పదజాలం",
     "en": "Level 3 — Roots and vocabulary"
    }
   }
  },
  {
   "q": {
    "te": "'ముస్లిమాన్' ఎంతమందిని సూచిస్తుంది?",
    "en": "How many does muslimaan refer to?"
   },
   "options": [
    {
     "te": "సరిగ్గా ఇద్దరు",
     "en": "Exactly two"
    },
    {
     "te": "ఒకరు",
     "en": "One"
    },
    {
     "te": "చాలామంది",
     "en": "Many"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "grammar",
    "title": {
     "te": "స్థాయి 4 — వ్యాకరణ ప్రాథమికాలు",
     "en": "Level 4 — Grammar basics"
    }
   }
  },
  {
   "q": {
    "te": "ఏ పదాలను ముందుగా నేర్చుకోవాలి?",
    "en": "Which words should be learned first?"
   },
   "options": [
    {
     "te": "అత్యధికంగా వచ్చే చిన్న పదాలు",
     "en": "The small, most frequent words"
    },
    {
     "te": "పొడవాటి నామవాచకాలు",
     "en": "Long nouns"
    },
    {
     "te": "అరుదైన పదాలు",
     "en": "Rare words"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "quranic",
    "title": {
     "te": "స్థాయి 5 — ఖురానిక్ అరబిక్",
     "en": "Level 5 — Quranic Arabic"
    }
   }
  },
  {
   "q": {
    "te": "మరణ వార్త విన్నప్పుడు ఏమి చెబుతారు?",
    "en": "What is said on hearing of a death?"
   },
   "options": [
    {
     "te": "ఇన్నా లిల్లాహి వ ఇన్నా ఇలైహి రాజిఊన్",
     "en": "Innaa lillaahi wa innaa ilayhi raaji'oon"
    },
    {
     "te": "మాషా అల్లాహ్",
     "en": "Maa shaa Allah"
    },
    {
     "te": "బారకల్లాహు ఫీక్",
     "en": "Baarak Allahu feek"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily",
    "title": {
     "te": "స్థాయి 6 — రోజువారీ అరబిక్",
     "en": "Level 6 — Everyday Arabic"
    }
   }
  }
 ],
 "learn-urdu": [
  {
   "q": {
    "te": "పర్షియన్ చేర్చిన అక్షరాలు ఏ శబ్దాల కోసం?",
    "en": "The letters Persian added cover which sounds?"
   },
   "options": [
    {
     "te": "ప, చ, జ, గ",
     "en": "p, ch, zh, g"
    },
    {
     "te": "ఐన్, హా",
     "en": "ayn and ha"
    },
    {
     "te": "పొడవాటి స్వరాలు",
     "en": "long vowels"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "alphabet",
    "title": {
     "te": "స్థాయి 1 — ఉర్దూ అక్షరమాల",
     "en": "Level 1 — The Urdu alphabet"
    }
   }
  },
  {
   "q": {
    "te": "ముద్రిత ఉర్దూ వార్తాపత్రికలో అఅరాబ్ ఉంటాయా?",
    "en": "Does a printed Urdu newspaper carry the aerab?"
   },
   "options": [
    {
     "te": "ఉండవు",
     "en": "No"
    },
    {
     "te": "ఎప్పుడూ ఉంటాయి",
     "en": "Always"
    },
    {
     "te": "మొదటి పేజీలో మాత్రమే",
     "en": "Only on the front page"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "reading",
    "title": {
     "te": "స్థాయి 2 — చదవడం ప్రాథమికాలు",
     "en": "Level 2 — Reading basics"
    }
   }
  },
  {
   "q": {
    "te": "నస్తలీక్‌లో అక్షరాలు ఒకే గీతపై ఉంటాయా?",
    "en": "Do letters in nastaliq sit on one baseline?"
   },
   "options": [
    {
     "te": "ఉండవు — ప్రతి అక్షరం కొంచెం కింద",
     "en": "No, each sits a little lower"
    },
    {
     "te": "అవును, ఎప్పుడూ",
     "en": "Yes, always"
    },
    {
     "te": "పదం మధ్యలో మాత్రమే",
     "en": "Only in the middle of a word"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "writing",
    "title": {
     "te": "స్థాయి 3 — రాయడం నేర్చుకోవడం",
     "en": "Level 3 — Learning to write"
    }
   }
  },
  {
   "q": {
    "te": "'జీ నహీఁ' అంటే ఏమిటి?",
    "en": "What does jee nahin mean?"
   },
   "options": [
    {
     "te": "కాదు (గౌరవపూర్వకంగా)",
     "en": "No, respectfully"
    },
    {
     "te": "అవును",
     "en": "Yes"
    },
    {
     "te": "ధన్యవాదాలు",
     "en": "Thank you"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily",
    "title": {
     "te": "స్థాయి 4 — రోజువారీ ఉర్దూ",
     "en": "Level 4 — Everyday Urdu"
    }
   }
  },
  {
   "q": {
    "te": "'ఫరిష్తా' అంటే ఏమిటి?",
    "en": "What does farishta mean?"
   },
   "options": [
    {
     "te": "దైవదూత",
     "en": "An angel"
    },
    {
     "te": "ప్రవక్త",
     "en": "A prophet"
    },
    {
     "te": "పండితుడు",
     "en": "A scholar"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "islamic",
    "title": {
     "te": "స్థాయి 5 — ఇస్లామిక్ ఉర్దూ",
     "en": "Level 5 — Islamic Urdu"
    }
   }
  },
  {
   "q": {
    "te": "గజల్ చివరి షేర్‌ను ఏమంటారు?",
    "en": "What is the closing couplet of a ghazal called?"
   },
   "options": [
    {
     "te": "మఖ్‌తా",
     "en": "Maqta"
    },
    {
     "te": "మత్‌లా",
     "en": "Matla"
    },
    {
     "te": "నజ్మ్",
     "en": "Nazm"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "advanced",
    "title": {
     "te": "స్థాయి 6 — ఉన్నత ఉర్దూ",
     "en": "Level 6 — Advanced Urdu"
    }
   }
  },
  {
   "q": {
    "te": "ఉర్దూ ఏ కాలిగ్రఫీ శైలిలో రాస్తారు?",
    "en": "Which calligraphic style is Urdu written in?"
   },
   "options": [
    {
     "te": "నస్తలీక్",
     "en": "Nastaliq"
    },
    {
     "te": "నస్ఖ్",
     "en": "Naskh"
    },
    {
     "te": "కూఫీ",
     "en": "Kufic"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "alphabet",
    "title": {
     "te": "స్థాయి 1 — ఉర్దూ అక్షరమాల",
     "en": "Level 1 — The Urdu alphabet"
    }
   }
  },
  {
   "q": {
    "te": "'తష్దీద్' దేన్ని సూచిస్తుంది?",
    "en": "What does tashdeed indicate?"
   },
   "options": [
    {
     "te": "అక్షరం రెట్టింపు",
     "en": "A doubled letter"
    },
    {
     "te": "స్వరం లేదు",
     "en": "No vowel"
    },
    {
     "te": "పదాంతం",
     "en": "The end of a word"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "reading",
    "title": {
     "te": "స్థాయి 2 — చదవడం ప్రాథమికాలు",
     "en": "Level 2 — Reading basics"
    }
   }
  },
  {
   "q": {
    "te": "మంచి నస్తలీక్‌కు కలంను ఎలా పట్టుకోవాలి?",
    "en": "How should the pen be held for good nastaliq?"
   },
   "options": [
    {
     "te": "కొంచెం వాలుగా",
     "en": "At a slight angle"
    },
    {
     "te": "నిటారుగా",
     "en": "Upright"
    },
    {
     "te": "ఎడమ చేతితో",
     "en": "In the left hand"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "writing",
    "title": {
     "te": "స్థాయి 3 — రాయడం నేర్చుకోవడం",
     "en": "Level 3 — Learning to write"
    }
   }
  },
  {
   "q": {
    "te": "'ముఝే సమఝ్ నహీఁ ఆయా' అంటే ఏమిటి?",
    "en": "What does mujhe samajh nahin aaya mean?"
   },
   "options": [
    {
     "te": "నాకు అర్థం కాలేదు",
     "en": "I did not understand"
    },
    {
     "te": "నేను బాగున్నాను",
     "en": "I am fine"
    },
    {
     "te": "మీ పేరు ఏమిటి?",
     "en": "What is your name?"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "daily",
    "title": {
     "te": "స్థాయి 4 — రోజువారీ ఉర్దూ",
     "en": "Level 4 — Everyday Urdu"
    }
   }
  },
  {
   "q": {
    "te": "'మక్రూహ్' అంటే ఏమిటి?",
    "en": "What does makruh mean?"
   },
   "options": [
    {
     "te": "ఇష్టపడనిది",
     "en": "Disliked"
    },
    {
     "te": "నిషిద్ధం",
     "en": "Forbidden"
    },
    {
     "te": "తప్పనిసరి",
     "en": "Obligatory"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "islamic",
    "title": {
     "te": "స్థాయి 5 — ఇస్లామిక్ ఉర్దూ",
     "en": "Level 5 — Islamic Urdu"
    }
   }
  },
  {
   "q": {
    "te": "ఇఖ్బాల్ కవిత్వంలో 'ఖుదీ' అంటే ఏమిటి?",
    "en": "What does khudi mean in Iqbal's poetry?"
   },
   "options": [
    {
     "te": "ఆత్మగౌరవం, స్వీయ నిర్మాణం",
     "en": "Selfhood and self-building"
    },
    {
     "te": "ఏకాంతం",
     "en": "Solitude"
    },
    {
     "te": "ప్రయాణం",
     "en": "Travel"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "advanced",
    "title": {
     "te": "స్థాయి 6 — ఉన్నత ఉర్దూ",
     "en": "Level 6 — Advanced Urdu"
    }
   }
  }
 ],
 "hadith": [
  {
   "q": {
    "te": "హదీసులో 'మత్న్' అంటే ఏమిటి?",
    "en": "What is the matn of a hadith?"
   },
   "options": [
    {
     "te": "అసలు పాఠం",
     "en": "The text itself"
    },
    {
     "te": "ఉల్లేఖకుల శృంఖల",
     "en": "The chain of narrators"
    },
    {
     "te": "గ్రంథ రచయిత",
     "en": "The compiler"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-is-hadith",
    "title": {
     "te": "స్థాయి 1 — హదీసు అంటే ఏమిటి",
     "en": "Level 1 — What a hadith is"
    }
   }
  },
  {
   "q": {
    "te": "'దబ్త్' అంటే ఏమిటి?",
    "en": "What is dabt?"
   },
   "options": [
    {
     "te": "ఉల్లేఖకుడి ఖచ్చితత్వం, జ్ఞాపకశక్తి",
     "en": "A narrator's precision and memory"
    },
    {
     "te": "గ్రంథ పరిమాణం",
     "en": "The size of a book"
    },
    {
     "te": "హదీసు పాఠం",
     "en": "The text of a hadith"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-was-checked",
    "title": {
     "te": "స్థాయి 2 — ఉల్లేఖనలు ఎలా పరిశీలించబడ్డాయి",
     "en": "Level 2 — How narrations were checked"
    }
   }
  },
  {
   "q": {
    "te": "బుఖారీ అదనపు షరతు ఏమిటి?",
    "en": "What extra condition did Bukhari require?"
   },
   "options": [
    {
     "te": "వరుస ఉల్లేఖకులు నిజంగా కలిశారని నిరూపణ",
     "en": "Proof that consecutive narrators actually met"
    },
    {
     "te": "ఉల్లేఖన పొడవుగా ఉండాలి",
     "en": "That the narration be long"
    },
    {
     "te": "అది మదీనాలో వినబడాలి",
     "en": "That it be heard in Madinah"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "the-six-books",
    "title": {
     "te": "స్థాయి 3 — ఆరు గ్రంథాలు",
     "en": "Level 3 — The six collections"
    }
   }
  },
  {
   "q": {
    "te": "ఒక ఇస్లామిక్ ఫార్వర్డ్ వచ్చినప్పుడు మొదటి ప్రశ్న?",
    "en": "On receiving an Islamic forward, the first question is?"
   },
   "options": [
    {
     "te": "దీనికి మూలం ఉందా?",
     "en": "Does it name a source?"
    },
    {
     "te": "ఇది ఎవరు పంపారు?",
     "en": "Who sent it?"
    },
    {
     "te": "ఇది ఎంత పొడవు?",
     "en": "How long is it?"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "living-by-it",
    "title": {
     "te": "స్థాయి 4 — హదీసుతో జీవించడం",
     "en": "Level 4 — Living by hadith"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 16:44 ప్రవక్త ﷺ పని ఏమని చెబుతుంది?",
    "en": "What does Quran 16:44 say the Prophet's task includes?"
   },
   "options": [
    {
     "te": "అవతరించినదాన్ని ప్రజలకు స్పష్టం చేయడం",
     "en": "Making clear to people what was sent down"
    },
    {
     "te": "కొత్త గ్రంథం రాయడం",
     "en": "Writing a new book"
    },
    {
     "te": "ఖురాన్‌ను మార్చడం",
     "en": "Changing the Quran"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-is-hadith",
    "title": {
     "te": "స్థాయి 1 — హదీసు అంటే ఏమిటి",
     "en": "Level 1 — What a hadith is"
    }
   }
  },
  {
   "q": {
    "te": "పాఠాన్ని పరిశీలించేటప్పుడు ఏది అనుమానాస్పదం?",
    "en": "When examining a text, what is suspect?"
   },
   "options": [
    {
     "te": "చిన్న పనికి అపారమైన ప్రతిఫల వాగ్దానం",
     "en": "An enormous reward promised for a trivial act"
    },
    {
     "te": "సంక్షిప్తమైన మాట",
     "en": "Concise wording"
    },
    {
     "te": "ఖురాన్‌తో సరిపోవడం",
     "en": "Agreement with the Quran"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-was-checked",
    "title": {
     "te": "స్థాయి 2 — ఉల్లేఖనలు ఎలా పరిశీలించబడ్డాయి",
     "en": "Level 2 — How narrations were checked"
    }
   }
  },
  {
   "q": {
    "te": "నవవీ నలభై హదీసుల ఎంపిక ప్రమాణం ఏమిటి?",
    "en": "What was Nawawi's criterion for his forty?"
   },
   "options": [
    {
     "te": "ప్రతిదీ ఇస్లాం ఒక ప్రధాన సూత్రాన్ని కలిగి ఉండాలి",
     "en": "Each should carry a major principle of Islam"
    },
    {
     "te": "ప్రతిదీ చిన్నదిగా ఉండాలి",
     "en": "Each should be short"
    },
    {
     "te": "ప్రతిదీ బుఖారీ నుండే ఉండాలి",
     "en": "Each should be from Bukhari"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "the-six-books",
    "title": {
     "te": "స్థాయి 3 — ఆరు గ్రంథాలు",
     "en": "Level 3 — The six collections"
    }
   }
  },
  {
   "q": {
    "te": "సూచించబడిన ఆచరణాత్మక పద్ధతి ఏమిటి?",
    "en": "What practical method is suggested?"
   },
   "options": [
    {
     "te": "వారానికి ఒక హదీసు, ఆచరణతో సహా",
     "en": "One hadith a week, acted upon"
    },
    {
     "te": "రోజుకు యాభై చదవడం",
     "en": "Reading fifty a day"
    },
    {
     "te": "మొత్తం బుఖారీ కంఠస్థం",
     "en": "Memorising all of Bukhari"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "living-by-it",
    "title": {
     "te": "స్థాయి 4 — హదీసుతో జీవించడం",
     "en": "Level 4 — Living by hadith"
    }
   }
  },
  {
   "q": {
    "te": "'హదీసు ఖుద్సీ'లో పదాలు ఎవరివి?",
    "en": "In a hadith qudsi, whose are the words?"
   },
   "options": [
    {
     "te": "ప్రవక్త ﷺవి; అర్థం అల్లాహ్ నుండి",
     "en": "The Prophet's, with the meaning from Allah"
    },
    {
     "te": "పూర్తిగా అల్లాహ్‌వి, ఖురాన్ లాగే",
     "en": "Entirely Allah's, as in the Quran"
    },
    {
     "te": "ఉల్లేఖకుడివి",
     "en": "The narrator's"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-is-hadith",
    "title": {
     "te": "స్థాయి 1 — హదీసు అంటే ఏమిటి",
     "en": "Level 1 — What a hadith is"
    }
   }
  },
  {
   "q": {
    "te": "ప్రవక్త ﷺపై ఉద్దేశపూర్వకంగా అబద్ధం చెప్పడం గురించి?",
    "en": "About deliberately lying concerning the Prophet ﷺ?"
   },
   "options": [
    {
     "te": "అతను నరకంలో తన స్థానం సిద్ధం చేసుకోవాలి",
     "en": "He should take his seat in the Fire"
    },
    {
     "te": "అది చిన్న విషయం",
     "en": "It is a minor matter"
    },
    {
     "te": "అది అనుమతించబడింది",
     "en": "It is permitted"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-was-checked",
    "title": {
     "te": "స్థాయి 2 — ఉల్లేఖనలు ఎలా పరిశీలించబడ్డాయి",
     "en": "Level 2 — How narrations were checked"
    }
   }
  },
  {
   "q": {
    "te": "ముస్నద్ అహ్మద్ ఎలా అమర్చబడింది?",
    "en": "How is the Musnad of Ahmad arranged?"
   },
   "options": [
    {
     "te": "సహచరుల పేర్ల ప్రకారం",
     "en": "By companion"
    },
    {
     "te": "అంశాల ప్రకారం",
     "en": "By topic"
    },
    {
     "te": "అక్షరక్రమంలో",
     "en": "Alphabetically"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "the-six-books",
    "title": {
     "te": "స్థాయి 3 — ఆరు గ్రంథాలు",
     "en": "Level 3 — The six collections"
    }
   }
  },
  {
   "q": {
    "te": "రెండు హదీసులు విరుద్ధంగా కనిపిస్తే మొదట ఏమి చేస్తారు?",
    "en": "When two hadith seem to contradict, what is done first?"
   },
   "options": [
    {
     "te": "వాటిని సమన్వయం చేయడానికి ప్రయత్నించడం",
     "en": "Try to reconcile them"
    },
    {
     "te": "రెండింటినీ వదిలేయడం",
     "en": "Discard both"
    },
    {
     "te": "పొడవైనదాన్ని తీసుకోవడం",
     "en": "Take the longer one"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "living-by-it",
    "title": {
     "te": "స్థాయి 4 — హదీసుతో జీవించడం",
     "en": "Level 4 — Living by hadith"
    }
   }
  }
 ],
 "hajj-umrah": [
  {
   "q": {
    "te": "హజ్ ఇస్లాంలో ఎన్నవ స్తంభం?",
    "en": "Which pillar of Islam is Hajj?"
   },
   "options": [
    {
     "te": "ఐదవది",
     "en": "The fifth"
    },
    {
     "te": "మూడవది",
     "en": "The third"
    },
    {
     "te": "మొదటిది",
     "en": "The first"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "why-hajj",
    "title": {
     "te": "స్థాయి 1 — హజ్ ఎందుకు, ఎవరిపై విధి",
     "en": "Level 1 — Why Hajj, and who it is due upon"
    }
   }
  },
  {
   "q": {
    "te": "భారతదేశం నుండి వచ్చేవారు సాధారణంగా ఏ మీఖాత్ మీదుగా వెళతారు?",
    "en": "Which miqat do pilgrims from India usually pass?"
   },
   "options": [
    {
     "te": "యలమ్‌లమ్",
     "en": "Yalamlam"
    },
    {
     "te": "జుల్-హులైఫా",
     "en": "Dhul-Hulayfah"
    },
    {
     "te": "జాతు ఇర్ఖ్",
     "en": "Dhat Irq"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ihram",
    "title": {
     "te": "స్థాయి 2 — ఇహ్రామ్ మరియు మీఖాత్",
     "en": "Level 2 — Ihram and the Miqat"
    }
   }
  },
  {
   "q": {
    "te": "భారతీయ యాత్రికులు సాధారణంగా ఏ రూపం చేస్తారు?",
    "en": "Which form do pilgrims from India usually perform?"
   },
   "options": [
    {
     "te": "తమత్తుఅ",
     "en": "Tamattu"
    },
    {
     "te": "ఇఫ్రాద్",
     "en": "Ifrad"
    },
    {
     "te": "ఖిరాన్",
     "en": "Qiran"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "types",
    "title": {
     "te": "స్థాయి 3 — హజ్ మూడు రకాలు",
     "en": "Level 3 — The three types of Hajj"
    }
   }
  },
  {
   "q": {
    "te": "తవాఫ్ ఎక్కడ మొదలవుతుంది?",
    "en": "Where does tawaf begin?"
   },
   "options": [
    {
     "te": "హజర్ అల్-అస్వద్ వద్ద",
     "en": "At the Hajar al-Aswad"
    },
    {
     "te": "మఖామ్ ఇబ్రాహీమ్ వద్ద",
     "en": "At the Maqam Ibrahim"
    },
    {
     "te": "సఫా వద్ద",
     "en": "At Safa"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tawaf-sai",
    "title": {
     "te": "స్థాయి 4 — తవాఫ్ మరియు సఅయి",
     "en": "Level 4 — Tawaf and Sa'i"
    }
   }
  },
  {
   "q": {
    "te": "అరఫాలో నిలబడటం ఎప్పటివరకు?",
    "en": "The standing at Arafah lasts until when?"
   },
   "options": [
    {
     "te": "సూర్యాస్తమయం వరకు",
     "en": "Until sunset"
    },
    {
     "te": "అస్ర్ వరకు",
     "en": "Until Asr"
    },
    {
     "te": "మధ్యాహ్నం వరకు",
     "en": "Until midday"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "days-of-hajj",
    "title": {
     "te": "స్థాయి 5 — హజ్ ఐదు రోజులు",
     "en": "Level 5 — The five days of Hajj"
    }
   }
  },
  {
   "q": {
    "te": "ఉమ్రహ్‌లో ఎన్ని దశలు?",
    "en": "How many steps does Umrah have?"
   },
   "options": [
    {
     "te": "నాలుగు",
     "en": "Four"
    },
    {
     "te": "ఏడు",
     "en": "Seven"
    },
    {
     "te": "రెండు",
     "en": "Two"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "umrah",
    "title": {
     "te": "స్థాయి 6 — ఉమ్రహ్ దశలవారీగా",
     "en": "Level 6 — Umrah step by step"
    }
   }
  },
  {
   "q": {
    "te": "'సామర్థ్యం' లో కింది వాటిలో ఏది కలిసి ఉండదు?",
    "en": "Which of these is NOT part of being 'able' to perform Hajj?"
   },
   "options": [
    {
     "te": "అరబిక్ భాష తెలిసి ఉండటం",
     "en": "Knowing the Arabic language"
    },
    {
     "te": "ప్రయాణ ఖర్చు భరించగలగడం",
     "en": "Being able to afford the journey"
    },
    {
     "te": "మార్గం సురక్షితంగా ఉండటం",
     "en": "The route being safe"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "why-hajj",
    "title": {
     "te": "స్థాయి 1 — హజ్ ఎందుకు, ఎవరిపై విధి",
     "en": "Level 1 — Why Hajj, and who it is due upon"
    }
   }
  },
  {
   "q": {
    "te": "కింది వాటిలో ఇహ్రామ్‌లో అనుమతించబడినది ఏది?",
    "en": "Which of these is permitted while in ihram?"
   },
   "options": [
    {
     "te": "గొడుగుతో నీడ చేసుకోవడం",
     "en": "Shading yourself with an umbrella"
    },
    {
     "te": "సువాసన వాడటం",
     "en": "Applying perfume"
    },
    {
     "te": "గోళ్ళు కత్తిరించడం",
     "en": "Cutting your nails"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ihram",
    "title": {
     "te": "స్థాయి 2 — ఇహ్రామ్ మరియు మీఖాత్",
     "en": "Level 2 — Ihram and the Miqat"
    }
   }
  },
  {
   "q": {
    "te": "ఖిరాన్‌లో ఇహ్రామ్ ఎప్పటివరకు కొనసాగుతుంది?",
    "en": "In qiran, how long does the ihram last?"
   },
   "options": [
    {
     "te": "జుల్-హిజ్జా 10 వరకు",
     "en": "Until 10 Dhu al-Hijjah"
    },
    {
     "te": "ఉమ్రహ్ పూర్తయ్యేవరకు",
     "en": "Until the Umrah is complete"
    },
    {
     "te": "మీఖాత్ వరకు",
     "en": "Until the miqat"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "types",
    "title": {
     "te": "స్థాయి 3 — హజ్ మూడు రకాలు",
     "en": "Level 3 — The three types of Hajj"
    }
   }
  },
  {
   "q": {
    "te": "సఅయి ఎక్కడ ముగుస్తుంది?",
    "en": "Where does sa'i end?"
   },
   "options": [
    {
     "te": "మర్వా వద్ద",
     "en": "At Marwah"
    },
    {
     "te": "సఫా వద్ద",
     "en": "At Safa"
    },
    {
     "te": "కాబా వద్ద",
     "en": "At the Kaaba"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tawaf-sai",
    "title": {
     "te": "స్థాయి 4 — తవాఫ్ మరియు సఅయి",
     "en": "Level 4 — Tawaf and Sa'i"
    }
   }
  },
  {
   "q": {
    "te": "ముజ్దలిఫాలో ఏ నమాజులు కలిపి చదువుతారు?",
    "en": "Which prayers are combined at Muzdalifah?"
   },
   "options": [
    {
     "te": "మఘ్రిబ్ మరియు ఇషా",
     "en": "Maghrib and Isha"
    },
    {
     "te": "జుహ్ర్ మరియు అస్ర్",
     "en": "Zuhr and Asr"
    },
    {
     "te": "ఫజ్ర్ మరియు జుహ్ర్",
     "en": "Fajr and Zuhr"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "days-of-hajj",
    "title": {
     "te": "స్థాయి 5 — హజ్ ఐదు రోజులు",
     "en": "Level 5 — The five days of Hajj"
    }
   }
  },
  {
   "q": {
    "te": "ఉమ్రహ్‌లో కింది వాటిలో ఏది ఉండదు?",
    "en": "Which of these is NOT part of Umrah?"
   },
   "options": [
    {
     "te": "అరఫాలో నిలబడటం",
     "en": "Standing at Arafah"
    },
    {
     "te": "తవాఫ్",
     "en": "Tawaf"
    },
    {
     "te": "సఅయి",
     "en": "Sa'i"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "umrah",
    "title": {
     "te": "స్థాయి 6 — ఉమ్రహ్ దశలవారీగా",
     "en": "Level 6 — Umrah step by step"
    }
   }
  }
 ],
 "names-of-allah": [
  {
   "q": {
    "te": "అల్లాహ్ పేర్లు ఎక్కడి నుండి వస్తాయి?",
    "en": "Where do Allah's names come from?"
   },
   "options": [
    {
     "te": "ఖురాన్ మరియు ప్రామాణిక సున్నత్",
     "en": "The Quran and authentic Sunnah"
    },
    {
     "te": "పండితుల ఏకాభిప్రాయం",
     "en": "The consensus of scholars"
    },
    {
     "te": "ప్రాచీన సంప్రదాయం",
     "en": "Ancient tradition"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-they-are",
    "title": {
     "te": "స్థాయి 1 — అస్మా ఉల్-హుస్నా అంటే ఏమిటి",
     "en": "Level 1 — What the Beautiful Names are"
    }
   }
  },
  {
   "q": {
    "te": "బుఖారీ, ముస్లిం హదీసులో ఏమి లేదు?",
    "en": "What is NOT in the Bukhari and Muslim hadith?"
   },
   "options": [
    {
     "te": "పేర్ల జాబితా",
     "en": "The list of names"
    },
    {
     "te": "తొంభై తొమ్మిది అనే సంఖ్య",
     "en": "The number ninety-nine"
    },
    {
     "te": "స్వర్గ వాగ్దానం",
     "en": "The promise of Paradise"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ninety-nine",
    "title": {
     "te": "స్థాయి 2 — తొంభై తొమ్మిది అనే సంఖ్య",
     "en": "Level 2 — The number ninety-nine"
    }
   }
  },
  {
   "q": {
    "te": "'జమాల్' పేర్లు దేన్ని కలిగిస్తాయి?",
    "en": "The names of jamal give rise to what?"
   },
   "options": [
    {
     "te": "ఆశ",
     "en": "Hope"
    },
    {
     "te": "నిరాశ",
     "en": "Despair"
    },
    {
     "te": "ఉదాసీనత",
     "en": "Indifference"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "mercy-and-majesty",
    "title": {
     "te": "స్థాయి 3 — కారుణ్యం మరియు గాంభీర్యం",
     "en": "Level 3 — Mercy and majesty"
    }
   }
  },
  {
   "q": {
    "te": "పేరు (ఇస్మ్) మరియు గుణం (సిఫత్) మధ్య తేడా ఏమిటి?",
    "en": "What is the difference between a name (ism) and an attribute (sifah)?"
   },
   "options": [
    {
     "te": "పేరు అల్లాహ్‌ను సూచిస్తుంది; గుణం ఆయన లక్షణాన్ని",
     "en": "A name refers to Allah; an attribute refers to a quality of His"
    },
    {
     "te": "ఏ తేడా లేదు",
     "en": "There is no difference"
    },
    {
     "te": "గుణాలు ఖురాన్‌లో లేవు",
     "en": "Attributes are not in the Quran"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-they-are",
    "title": {
     "te": "స్థాయి 1 — అస్మా ఉల్-హుస్నా అంటే ఏమిటి",
     "en": "Level 1 — What the Beautiful Names are"
    }
   }
  },
  {
   "q": {
    "te": "'ఇహ్సా' లో ఏమి ఉంటుంది?",
    "en": "What does 'ihsa' include?"
   },
   "options": [
    {
     "te": "కంఠస్థం, అర్థం, ఆచరణ",
     "en": "Memorising, understanding and acting"
    },
    {
     "te": "కేవలం లెక్కపెట్టడం",
     "en": "Counting alone"
    },
    {
     "te": "కేవలం రాయడం",
     "en": "Writing them out"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ninety-nine",
    "title": {
     "te": "స్థాయి 2 — తొంభై తొమ్మిది అనే సంఖ్య",
     "en": "Level 2 — The number ninety-nine"
    }
   }
  },
  {
   "q": {
    "te": "కింది వాటిలో జలాల్ పేరు ఏది?",
    "en": "Which of these is a name of jalal?"
   },
   "options": [
    {
     "te": "అల్-ఖహ్హార్",
     "en": "Al-Qahhar"
    },
    {
     "te": "అల్-వదూద్",
     "en": "Al-Wadud"
    },
    {
     "te": "అల్-లతీఫ్",
     "en": "Al-Latif"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "mercy-and-majesty",
    "title": {
     "te": "స్థాయి 3 — కారుణ్యం మరియు గాంభీర్యం",
     "en": "Level 3 — Mercy and majesty"
    }
   }
  },
  {
   "q": {
    "te": "బిస్మిల్లాహ్‌లో ఎన్ని పేర్లు ఉన్నాయి?",
    "en": "How many names appear in the bismillah?"
   },
   "options": [
    {
     "te": "మూడు",
     "en": "Three"
    },
    {
     "te": "ఒకటి",
     "en": "One"
    },
    {
     "te": "ఏడు",
     "en": "Seven"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-they-are",
    "title": {
     "te": "స్థాయి 1 — అస్మా ఉల్-హుస్నా అంటే ఏమిటి",
     "en": "Level 1 — What the Beautiful Names are"
    }
   }
  },
  {
   "q": {
    "te": "అల్లాహ్‌కు మనకు తెలియని పేర్లు ఉన్నాయా?",
    "en": "Are there names of Allah we have not been taught?"
   },
   "options": [
    {
     "te": "అవును — ప్రవక్త ﷺ దుఆ దీన్ని సూచిస్తుంది",
     "en": "Yes, the Prophet's supplication indicates so"
    },
    {
     "te": "లేదు, అన్నీ తెలుసు",
     "en": "No, we know them all"
    },
    {
     "te": "ఖురాన్ దీని గురించి మౌనం",
     "en": "The Quran is silent on this"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ninety-nine",
    "title": {
     "te": "స్థాయి 2 — తొంభై తొమ్మిది అనే సంఖ్య",
     "en": "Level 2 — The number ninety-nine"
    }
   }
  },
  {
   "q": {
    "te": "హదీసు ఖుద్సీ ప్రకారం అల్లాహ్ కారుణ్యం దేన్ని అధిగమిస్తుంది?",
    "en": "According to the hadith qudsi, Allah's mercy prevails over what?"
   },
   "options": [
    {
     "te": "ఆయన ఆగ్రహాన్ని",
     "en": "His wrath"
    },
    {
     "te": "ఆయన జ్ఞానాన్ని",
     "en": "His knowledge"
    },
    {
     "te": "ఆయన సృష్టిని",
     "en": "His creation"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "mercy-and-majesty",
    "title": {
     "te": "స్థాయి 3 — కారుణ్యం మరియు గాంభీర్యం",
     "en": "Level 3 — Mercy and majesty"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 7:180 మనల్ని ఏమి చేయమని చెబుతుంది?",
    "en": "What does Quran 7:180 instruct us to do?"
   },
   "options": [
    {
     "te": "ఆ పేర్లతో అల్లాహ్‌ను వేడుకోవాలి",
     "en": "Call upon Allah by those names"
    },
    {
     "te": "ఆ పేర్లను రాయాలి",
     "en": "Write the names down"
    },
    {
     "te": "ఆ పేర్లను దాచాలి",
     "en": "Keep the names hidden"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "what-they-are",
    "title": {
     "te": "స్థాయి 1 — అస్మా ఉల్-హుస్నా అంటే ఏమిటి",
     "en": "Level 1 — What the Beautiful Names are"
    }
   }
  },
  {
   "q": {
    "te": "ఈ హదీసు ఏ గ్రంథాల్లో ఉంది?",
    "en": "Which collections record this hadith?"
   },
   "options": [
    {
     "te": "బుఖారీ మరియు ముస్లిం",
     "en": "Bukhari and Muslim"
    },
    {
     "te": "కేవలం ఇబ్న్ మాజా",
     "en": "Ibn Majah only"
    },
    {
     "te": "ఏ గ్రంథంలోనూ లేదు",
     "en": "It is not in any collection"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "ninety-nine",
    "title": {
     "te": "స్థాయి 2 — తొంభై తొమ్మిది అనే సంఖ్య",
     "en": "Level 2 — The number ninety-nine"
    }
   }
  },
  {
   "q": {
    "te": "'అత్-తవ్వాబ్' అంటే ఏమిటి?",
    "en": "What does 'At-Tawwab' mean?"
   },
   "options": [
    {
     "te": "పశ్చాత్తాపాన్ని స్వీకరించేవాడు",
     "en": "The One who accepts repentance"
    },
    {
     "te": "శిక్షించేవాడు",
     "en": "The One who punishes"
    },
    {
     "te": "సృష్టించేవాడు",
     "en": "The Creator"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "mercy-and-majesty",
    "title": {
     "te": "స్థాయి 3 — కారుణ్యం మరియు గాంభీర్యం",
     "en": "Level 3 — Mercy and majesty"
    }
   }
  }
 ],
 "islamic-calendar": [
  {
   "q": {
    "te": "హిజ్రీ క్యాలెండర్ ఏ సంఘటన నుండి లెక్కిస్తుంది?",
    "en": "From which event does the Hijri calendar count?"
   },
   "options": [
    {
     "te": "మదీనాకు హిజ్రత్",
     "en": "The migration to Madinah"
    },
    {
     "te": "ప్రవక్త ﷺ జననం",
     "en": "The Prophet's birth"
    },
    {
     "te": "మక్కా విజయం",
     "en": "The conquest of Makkah"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-works",
    "title": {
     "te": "స్థాయి 1 — హిజ్రీ క్యాలెండర్ ఎలా పనిచేస్తుంది",
     "en": "Level 1 — How the Hijri calendar works"
    }
   }
  },
  {
   "q": {
    "te": "హదీసు ప్రకారం మేఘావృతమైతే?",
    "en": "According to the hadith, if the sky is obscured?"
   },
   "options": [
    {
     "te": "మాసాన్ని ముప్ఫైకి పూర్తి చేయాలి",
     "en": "Complete the month as thirty"
    },
    {
     "te": "గణనను తప్పనిసరిగా వాడాలి",
     "en": "Calculation must be used"
    },
    {
     "te": "ఇరవై తొమ్మిదికి ముగించాలి",
     "en": "End at twenty-nine"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "moon-sighting",
    "title": {
     "te": "స్థాయి 2 — చంద్రవంక దర్శనం, ఈద్ తేదీలు వేరవడం",
     "en": "Level 2 — Moon sighting, and why Eid dates differ"
    }
   }
  },
  {
   "q": {
    "te": "వరుసగా ఉన్న మూడు పవిత్ర మాసాలు ఏవి?",
    "en": "Which three sacred months run consecutively?"
   },
   "options": [
    {
     "te": "జుల్-ఖాదా, జుల్-హిజ్జా, ముహర్రం",
     "en": "Dhu al-Qa'dah, Dhu al-Hijjah, Muharram"
    },
    {
     "te": "రజబ్, షాబాన్, రమదాన్",
     "en": "Rajab, Sha'ban, Ramadan"
    },
    {
     "te": "ముహర్రం, సఫర్, రబీ అల్-అవ్వల్",
     "en": "Muharram, Safar, Rabi al-Awwal"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "sacred-months",
    "title": {
     "te": "స్థాయి 3 — నాలుగు పవిత్ర మాసాలు",
     "en": "Level 3 — The four sacred months"
    }
   }
  },
  {
   "q": {
    "te": "ఇస్లామిక్ రోజు ఎప్పుడు మొదలవుతుంది?",
    "en": "When does the Islamic day begin?"
   },
   "options": [
    {
     "te": "సూర్యాస్తమయంతో",
     "en": "At sunset"
    },
    {
     "te": "అర్ధరాత్రితో",
     "en": "At midnight"
    },
    {
     "te": "సూర్యోదయంతో",
     "en": "At sunrise"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-works",
    "title": {
     "te": "స్థాయి 1 — హిజ్రీ క్యాలెండర్ ఎలా పనిచేస్తుంది",
     "en": "Level 1 — How the Hijri calendar works"
    }
   }
  },
  {
   "q": {
    "te": "మెజారిటీ పండితులు దేన్ని ఆధారంగా ఉంచుతారు?",
    "en": "What do the majority of scholars make the basis?"
   },
   "options": [
    {
     "te": "కంటితో చంద్రవంక దర్శనం",
     "en": "Physical sighting of the crescent"
    },
    {
     "te": "ఖగోళ గణన",
     "en": "Astronomical calculation"
    },
    {
     "te": "ప్రభుత్వ ప్రకటన",
     "en": "A government announcement"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "moon-sighting",
    "title": {
     "te": "స్థాయి 2 — చంద్రవంక దర్శనం, ఈద్ తేదీలు వేరవడం",
     "en": "Level 2 — Moon sighting, and why Eid dates differ"
    }
   }
  },
  {
   "q": {
    "te": "రమదాన్ తర్వాత అత్యుత్తమ ఉపవాసం ఏ మాసంలో?",
    "en": "The best fasting after Ramadan is in which month?"
   },
   "options": [
    {
     "te": "ముహర్రం",
     "en": "Muharram"
    },
    {
     "te": "సఫర్",
     "en": "Safar"
    },
    {
     "te": "షవ్వాల్",
     "en": "Shawwal"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "sacred-months",
    "title": {
     "te": "స్థాయి 3 — నాలుగు పవిత్ర మాసాలు",
     "en": "Level 3 — The four sacred months"
    }
   }
  },
  {
   "q": {
    "te": "'ముహర్రం' అనే పేరుకు అర్థం ఏమిటి?",
    "en": "What does the name 'Muharram' mean?"
   },
   "options": [
    {
     "te": "నిషేధించబడినది",
     "en": "Forbidden"
    },
    {
     "te": "వసంతం",
     "en": "Spring"
    },
    {
     "te": "మండే వేడి",
     "en": "Scorching heat"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-works",
    "title": {
     "te": "స్థాయి 1 — హిజ్రీ క్యాలెండర్ ఎలా పనిచేస్తుంది",
     "en": "Level 1 — How the Hijri calendar works"
    }
   }
  },
  {
   "q": {
    "te": "తేదీ భేదం ఉన్నప్పుడు సిఫార్సు ఏమిటి?",
    "en": "When dates differ, what is recommended?"
   },
   "options": [
    {
     "te": "స్థానిక సమాజంతో కలిసి ఉండటం",
     "en": "Staying with your local community"
    },
    {
     "te": "సొంతంగా నిర్ణయించుకోవడం",
     "en": "Deciding on your own"
    },
    {
     "te": "ఈద్ వదిలేయడం",
     "en": "Skipping Eid"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "moon-sighting",
    "title": {
     "te": "స్థాయి 2 — చంద్రవంక దర్శనం, ఈద్ తేదీలు వేరవడం",
     "en": "Level 2 — Moon sighting, and why Eid dates differ"
    }
   }
  },
  {
   "q": {
    "te": "ఆషూరా ఏ తేదీన?",
    "en": "On which date does Ashura fall?"
   },
   "options": [
    {
     "te": "ముహర్రం 10",
     "en": "10 Muharram"
    },
    {
     "te": "ముహర్రం 1",
     "en": "1 Muharram"
    },
    {
     "te": "రజబ్ 27",
     "en": "27 Rajab"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "sacred-months",
    "title": {
     "te": "స్థాయి 3 — నాలుగు పవిత్ర మాసాలు",
     "en": "Level 3 — The four sacred months"
    }
   }
  },
  {
   "q": {
    "te": "హిజ్రీ సంవత్సరంలో ఎన్ని రోజులు?",
    "en": "How many days are in a Hijri year?"
   },
   "options": [
    {
     "te": "354 లేదా 355",
     "en": "354 or 355"
    },
    {
     "te": "365 లేదా 366",
     "en": "365 or 366"
    },
    {
     "te": "360 ఖచ్చితంగా",
     "en": "Exactly 360"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "how-it-works",
    "title": {
     "te": "స్థాయి 1 — హిజ్రీ క్యాలెండర్ ఎలా పనిచేస్తుంది",
     "en": "Level 1 — How the Hijri calendar works"
    }
   }
  },
  {
   "q": {
    "te": "ఆకాశం మేఘావృతమైతే ఏమి చేయాలి?",
    "en": "What is done if the sky is obscured?"
   },
   "options": [
    {
     "te": "మాసాన్ని ముప్ఫై రోజులుగా పూర్తి చేయాలి",
     "en": "Complete the month as thirty days"
    },
    {
     "te": "ఉపవాసం వదిలేయాలి",
     "en": "Abandon the fast"
    },
    {
     "te": "ఇరవై ఎనిమిదికి ముగించాలి",
     "en": "End it at twenty-eight"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "moon-sighting",
    "title": {
     "te": "స్థాయి 2 — చంద్రవంక దర్శనం, ఈద్ తేదీలు వేరవడం",
     "en": "Level 2 — Moon sighting, and why Eid dates differ"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 9:36 ప్రకారం ఎన్ని మాసాలు పవిత్రమైనవి?",
    "en": "According to Quran 9:36, how many months are sacred?"
   },
   "options": [
    {
     "te": "నాలుగు",
     "en": "Four"
    },
    {
     "te": "రెండు",
     "en": "Two"
    },
    {
     "te": "ఆరు",
     "en": "Six"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "sacred-months",
    "title": {
     "te": "స్థాయి 3 — నాలుగు పవిత్ర మాసాలు",
     "en": "Level 3 — The four sacred months"
    }
   }
  }
 ],
 "special-prayers": [
  {
   "q": {
    "te": "'విత్ర్' అంటే ఏమిటి?",
    "en": "What does 'Witr' mean?"
   },
   "options": [
    {
     "te": "బేసి",
     "en": "Odd"
    },
    {
     "te": "సరి",
     "en": "Even"
    },
    {
     "te": "రాత్రి",
     "en": "Night"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "night-prayer",
    "title": {
     "te": "స్థాయి 1 — రాత్రి నమాజ్: తహజ్జుద్, విత్ర్, ఖునూత్",
     "en": "Level 1 — The night prayer: Tahajjud, Witr and Qunoot"
    }
   }
  },
  {
   "q": {
    "te": "ఎనిమిది వైపు ఆధారం ఎవరి ఉల్లేఖన?",
    "en": "The case for eight rests on whose narration?"
   },
   "options": [
    {
     "te": "ఆయిషా (ర/అ)",
     "en": "Aisha (RA)"
    },
    {
     "te": "ఉమర్ (ర/అ)",
     "en": "Umar (RA)"
    },
    {
     "te": "అబూ హురైరా (ర/అ)",
     "en": "Abu Hurayrah (RA)"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tarawih",
    "title": {
     "te": "స్థాయి 2 — తరావీహ్: ఎనిమిదా, ఇరవైనా",
     "en": "Level 2 — Tarawih: eight or twenty"
    }
   }
  },
  {
   "q": {
    "te": "జనాజా నమాజులో ఎన్ని తక్బీర్‌లు?",
    "en": "How many takbirs are in the funeral prayer?"
   },
   "options": [
    {
     "te": "నాలుగు",
     "en": "Four"
    },
    {
     "te": "రెండు",
     "en": "Two"
    },
    {
     "te": "ఏడు",
     "en": "Seven"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "janazah",
    "title": {
     "te": "స్థాయి 3 — జనాజా నమాజ్",
     "en": "Level 3 — The funeral prayer"
    }
   }
  },
  {
   "q": {
    "te": "హనఫీ మజ్‌హబ్‌లో ఖునూత్ ఎక్కడ చదువుతారు?",
    "en": "In the Hanafi school, where is Qunoot recited?"
   },
   "options": [
    {
     "te": "మూడో రక్అత్‌లో రుకూకు ముందు",
     "en": "Before the bowing in the third unit"
    },
    {
     "te": "రుకూ తర్వాత",
     "en": "After the bowing"
    },
    {
     "te": "సజ్దా తర్వాత",
     "en": "After the prostration"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "night-prayer",
    "title": {
     "te": "స్థాయి 1 — రాత్రి నమాజ్: తహజ్జుద్, విత్ర్, ఖునూత్",
     "en": "Level 1 — The night prayer: Tahajjud, Witr and Qunoot"
    }
   }
  },
  {
   "q": {
    "te": "హరమ్‌లలో (మక్కా, మదీనా) ఎన్ని రక్అత్‌లు?",
    "en": "How many units are prayed in the Haramayn?"
   },
   "options": [
    {
     "te": "ఇరవై",
     "en": "Twenty"
    },
    {
     "te": "ఎనిమిది",
     "en": "Eight"
    },
    {
     "te": "నలభై",
     "en": "Forty"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tarawih",
    "title": {
     "te": "స్థాయి 2 — తరావీహ్: ఎనిమిదా, ఇరవైనా",
     "en": "Level 2 — Tarawih: eight or twenty"
    }
   }
  },
  {
   "q": {
    "te": "'ఫర్జ్ కిఫాయా' అంటే ఏమిటి?",
    "en": "What does 'fard kifayah' mean?"
   },
   "options": [
    {
     "te": "కొందరు చేస్తే అందరిపై నుండి బాధ్యత తీరుతుంది",
     "en": "If some perform it, the obligation lifts from all"
    },
    {
     "te": "ప్రతి ఒక్కరూ చేయాలి",
     "en": "Every single person must perform it"
    },
    {
     "te": "ఎవరూ చేయనవసరం లేదు",
     "en": "No one needs to perform it"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "janazah",
    "title": {
     "te": "స్థాయి 3 — జనాజా నమాజ్",
     "en": "Level 3 — The funeral prayer"
    }
   }
  },
  {
   "q": {
    "te": "లేవలేనని అనుమానం ఉంటే విత్ర్ ఎప్పుడు చదవాలి?",
    "en": "If you doubt you will wake, when should Witr be prayed?"
   },
   "options": [
    {
     "te": "పడుకునే ముందు, ఇషా తర్వాత",
     "en": "Before sleeping, after Isha"
    },
    {
     "te": "ఫజ్ర్ తర్వాత",
     "en": "After Fajr"
    },
    {
     "te": "అస్ర్ తర్వాత",
     "en": "After Asr"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "night-prayer",
    "title": {
     "te": "స్థాయి 1 — రాత్రి నమాజ్: తహజ్జుద్, విత్ర్, ఖునూత్",
     "en": "Level 1 — The night prayer: Tahajjud, Witr and Qunoot"
    }
   }
  },
  {
   "q": {
    "te": "ఇబ్న్ తైమియా ఏమన్నారు?",
    "en": "What did Ibn Taymiyyah hold?"
   },
   "options": [
    {
     "te": "రెండు ఆచరణలూ చెల్లుతాయి",
     "en": "Both practices are valid"
    },
    {
     "te": "ఎనిమిదే సరైనది",
     "en": "Only eight is correct"
    },
    {
     "te": "ఇరవైయే సరైనది",
     "en": "Only twenty is correct"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tarawih",
    "title": {
     "te": "స్థాయి 2 — తరావీహ్: ఎనిమిదా, ఇరవైనా",
     "en": "Level 2 — Tarawih: eight or twenty"
    }
   }
  },
  {
   "q": {
    "te": "ఖననం వరకు ఉన్నవారికి ఎంత ప్రతిఫలం?",
    "en": "What is the reward for staying until the burial?"
   },
   "options": [
    {
     "te": "రెండు ఖీరాత్‌లు",
     "en": "Two qirat"
    },
    {
     "te": "ఒక ఖీరాత్",
     "en": "One qirat"
    },
    {
     "te": "ప్రతిఫలం లేదు",
     "en": "No reward"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "janazah",
    "title": {
     "te": "స్థాయి 3 — జనాజా నమాజ్",
     "en": "Level 3 — The funeral prayer"
    }
   }
  },
  {
   "q": {
    "te": "ఫర్జ్ నమాజుల తర్వాత అత్యుత్తమ నమాజ్ ఏది?",
    "en": "Which is the best prayer after the obligatory ones?"
   },
   "options": [
    {
     "te": "రాత్రి నమాజ్",
     "en": "The night prayer"
    },
    {
     "te": "ఈద్ నమాజ్",
     "en": "The Eid prayer"
    },
    {
     "te": "ఇష్రాఖ్",
     "en": "The Ishraq prayer"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "night-prayer",
    "title": {
     "te": "స్థాయి 1 — రాత్రి నమాజ్: తహజ్జుద్, విత్ర్, ఖునూత్",
     "en": "Level 1 — The night prayer: Tahajjud, Witr and Qunoot"
    }
   }
  },
  {
   "q": {
    "te": "తరావీహ్ హోదా ఏమిటి?",
    "en": "What is the status of Tarawih?"
   },
   "options": [
    {
     "te": "సున్నత్ ముఅక్కదా — ఫర్జ్ కాదు",
     "en": "Sunnah mu'akkadah, not obligatory"
    },
    {
     "te": "ఫర్జ్",
     "en": "Obligatory"
    },
    {
     "te": "నిషిద్ధం",
     "en": "Forbidden"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "tarawih",
    "title": {
     "te": "స్థాయి 2 — తరావీహ్: ఎనిమిదా, ఇరవైనా",
     "en": "Level 2 — Tarawih: eight or twenty"
    }
   }
  },
  {
   "q": {
    "te": "జనాజా నమాజులో ఏమి ఉండదు?",
    "en": "What does the funeral prayer not contain?"
   },
   "options": [
    {
     "te": "రుకూ మరియు సజ్దా",
     "en": "Bowing and prostration"
    },
    {
     "te": "తక్బీర్",
     "en": "The takbir"
    },
    {
     "te": "సలామ్",
     "en": "The salam"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "janazah",
    "title": {
     "te": "స్థాయి 3 — జనాజా నమాజ్",
     "en": "Level 3 — The funeral prayer"
    }
   }
  }
 ],
 "womens-guidance": [
  {
   "q": {
    "te": "మహర్ ఎవరికి చెందుతుంది?",
    "en": "To whom does the mahr belong?"
   },
   "options": [
    {
     "te": "వధువుకు మాత్రమే",
     "en": "To the bride alone"
    },
    {
     "te": "వధువు తండ్రికి",
     "en": "To the bride's father"
    },
    {
     "te": "వరుడి కుటుంబానికి",
     "en": "To the groom's family"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "nikah",
    "title": {
     "te": "స్థాయి 1 — నికాహ్: ఒప్పందం, మహర్, హక్కులు",
     "en": "Level 1 — Nikah: the contract, the mahr, and rights"
    }
   }
  },
  {
   "q": {
    "te": "భర్త మరణించిన స్త్రీ ఇద్దత్ ఎంతకాలం?",
    "en": "How long is the iddah of a widow?"
   },
   "options": [
    {
     "te": "నాలుగు నెలల పది రోజులు",
     "en": "Four months and ten days"
    },
    {
     "te": "మూడు నెలలు",
     "en": "Three months"
    },
    {
     "te": "ఒక సంవత్సరం",
     "en": "One year"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "iddah",
    "title": {
     "te": "స్థాయి 2 — ఇద్దత్: వేచి ఉండే కాలం",
     "en": "Level 2 — Iddah: the waiting period"
    }
   }
  },
  {
   "q": {
    "te": "హనఫీ మజ్‌హబ్‌లో వయోజన స్త్రీ గురించి ఏమి?",
    "en": "In the Hanafi school, what applies to an adult woman?"
   },
   "options": [
    {
     "te": "ఆమె తనకు తానే ఒప్పందం చేసుకోగలదు",
     "en": "She may contract her own marriage"
    },
    {
     "te": "ఆమెకు ఎప్పుడూ వలీ అవసరం",
     "en": "She always requires a guardian"
    },
    {
     "te": "ఆమె వివాహం చేసుకోలేదు",
     "en": "She cannot marry"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "nikah",
    "title": {
     "te": "స్థాయి 1 — నికాహ్: ఒప్పందం, మహర్, హక్కులు",
     "en": "Level 1 — Nikah: the contract, the mahr, and rights"
    }
   }
  },
  {
   "q": {
    "te": "ఖురాన్ 65:1 దేన్ని నిషేధిస్తుంది?",
    "en": "What does Quran 65:1 forbid?"
   },
   "options": [
    {
     "te": "ఇద్దత్‌లో స్త్రీని ఇంటి నుండి బయటకు పంపడం",
     "en": "Turning a woman out of the home during iddah"
    },
    {
     "te": "ఆమె తిరిగి వివాహం చేసుకోవడం",
     "en": "Her remarrying"
    },
    {
     "te": "ఆమె వారసత్వం పొందడం",
     "en": "Her inheriting"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "iddah",
    "title": {
     "te": "స్థాయి 2 — ఇద్దత్: వేచి ఉండే కాలం",
     "en": "Level 2 — Iddah: the waiting period"
    }
   }
  },
  {
   "q": {
    "te": "ప్రవక్త ﷺ ప్రకారం అత్యంత బరకత్ ఉన్న వివాహం ఏది?",
    "en": "According to the Prophet ﷺ, which marriage is most blessed?"
   },
   "options": [
    {
     "te": "ఖర్చు తక్కువగా ఉండేది",
     "en": "The one with the least expense"
    },
    {
     "te": "అత్యంత ఖరీదైనది",
     "en": "The most expensive one"
    },
    {
     "te": "అత్యధిక అతిథులు ఉన్నది",
     "en": "The one with the most guests"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "nikah",
    "title": {
     "te": "స్థాయి 1 — నికాహ్: ఒప్పందం, మహర్, హక్కులు",
     "en": "Level 1 — Nikah: the contract, the mahr, and rights"
    }
   }
  },
  {
   "q": {
    "te": "ఇద్దత్ ఉద్దేశాల్లో ఒకటి ఏది?",
    "en": "Which is one purpose of the iddah?"
   },
   "options": [
    {
     "te": "వంశ స్పష్టత",
     "en": "Clarity of lineage"
    },
    {
     "te": "శిక్ష",
     "en": "Punishment"
    },
    {
     "te": "ఆస్తి బదిలీ",
     "en": "Transfer of property"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "iddah",
    "title": {
     "te": "స్థాయి 2 — ఇద్దత్: వేచి ఉండే కాలం",
     "en": "Level 2 — Iddah: the waiting period"
    }
   }
  },
  {
   "q": {
    "te": "నికాహ్‌కు ఏది అవసరం?",
    "en": "Which of these is required for a nikah?"
   },
   "options": [
    {
     "te": "ఇద్దరి సమ్మతి",
     "en": "The consent of both parties"
    },
    {
     "te": "ఖరీదైన వేడుక",
     "en": "An expensive celebration"
    },
    {
     "te": "వధువు కుటుంబం నుండి కట్నం",
     "en": "A dowry from the bride's family"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "nikah",
    "title": {
     "te": "స్థాయి 1 — నికాహ్: ఒప్పందం, మహర్, హక్కులు",
     "en": "Level 1 — Nikah: the contract, the mahr, and rights"
    }
   }
  },
  {
   "q": {
    "te": "గర్భవతి స్త్రీ ఇద్దత్ ఎప్పటివరకు?",
    "en": "How long is the iddah of a pregnant woman?"
   },
   "options": [
    {
     "te": "ప్రసవం వరకు",
     "en": "Until she gives birth"
    },
    {
     "te": "మూడు నెలలు",
     "en": "Three months"
    },
    {
     "te": "నాలుగు నెలల పది రోజులు",
     "en": "Four months and ten days"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "iddah",
    "title": {
     "te": "స్థాయి 2 — ఇద్దత్: వేచి ఉండే కాలం",
     "en": "Level 2 — Iddah: the waiting period"
    }
   }
  },
  {
   "q": {
    "te": "ఒత్తిడితో జరిపిన వివాహం గురించి ప్రవక్త ﷺ ఏమి చేశారు?",
    "en": "What did the Prophet ﷺ do about a marriage imposed by force?"
   },
   "options": [
    {
     "te": "దాన్ని రద్దు చేశారు",
     "en": "He annulled it"
    },
    {
     "te": "దాన్ని ఆమోదించారు",
     "en": "He upheld it"
    },
    {
     "te": "ఏమీ చేయలేదు",
     "en": "He did nothing"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "nikah",
    "title": {
     "te": "స్థాయి 1 — నికాహ్: ఒప్పందం, మహర్, హక్కులు",
     "en": "Level 1 — Nikah: the contract, the mahr, and rights"
    }
   }
  },
  {
   "q": {
    "te": "విడాకుల ఇద్దత్ కాలంలో ఖురాన్ దేనికి అవకాశం ఇస్తుంది?",
    "en": "During the iddah of divorce, what does the Quran allow room for?"
   },
   "options": [
    {
     "te": "సర్దుబాటు — తిరిగి కలుసుకోవడం",
     "en": "Reconciliation"
    },
    {
     "te": "వెంటనే మరో వివాహం",
     "en": "Immediate remarriage"
    },
    {
     "te": "ఆస్తి పంపకం",
     "en": "Division of property"
    }
   ],
   "answer": 0,
   "from": {
    "slug": "iddah",
    "title": {
     "te": "స్థాయి 2 — ఇద్దత్: వేచి ఉండే కాలం",
     "en": "Level 2 — Iddah: the waiting period"
    }
   }
  }
 ]
};

export function assessmentFor(portal: string): AssessmentQuestion[] {
  return bank[portal] ?? [];
}
