/* AUTO-GENERATED by scripts/build-lesson-index.mjs — do not edit by hand.

   The minimum LessonIndex needs to render a card: a title, a clipped intro and
   three counts. Importing the full lessons module into that client component
   put every lesson's complete text into the JavaScript of every portal page.

   75 lessons across 13 portals. */

export type Bi = { te: string; en: string };

export type LessonSummary = {
  portal: string;
  slug: string;
  title: Bi;
  intro: Bi | null;
  sections: number;
  quiz: number;
  faqs: number;
  /** Estimated reading time in minutes, measured at build time. */
  minutes: number;
};

export const lessonSummaries: LessonSummary[] = [
  {
    "portal": "learn-quran",
    "slug": "whatis",
    "title": {
      "te": "స్థాయి 1 — ఖురాన్ అంటే ఏమిటి",
      "en": "Level 1 — What the Quran is"
    },
    "intro": {
      "te": "ఖురాన్ అల్లాహ్ వాక్కు, ఇరవై మూడు సంవత్సరాలలో ప్రవక్త ﷺకు అవతరించింది. ఈ పాఠం అది ఎలా అవతరించిందో, ఎలా అమర్చబడిందో, ఎలా మార్పు లేకుండా భద్రపరచబడిందో…",
      "en": "The Quran is the word of Allah, revealed to the Prophet ﷺ across twenty-three years. This lesson covers how it came, how it is arranged, and how it was…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "learn-quran",
    "slug": "begin",
    "title": {
      "te": "స్థాయి 2 — చదవడం ఎలా మొదలుపెట్టాలి",
      "en": "Level 2 — How to begin reading"
    },
    "intro": {
      "te": "ఏ వయసులోనైనా ఖురాన్ చదవడం నేర్చుకోవచ్చు. ముఖ్యమైనది క్రమం: అక్షరాలు, స్వరాలు, కలపడం, తర్వాత చిన్న సూరాలు. దీన్ని దాటవేయడానికి ప్రయత్నించడమే చాలామంది…",
      "en": "Anyone can learn to read the Quran at any age. What matters is the order: letters, vowels, joining, then the short surahs. Trying to skip that order is why…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-quran",
    "slug": "tajweed",
    "title": {
      "te": "స్థాయి 3 — తజ్వీద్",
      "en": "Level 3 — Tajweed"
    },
    "intro": {
      "te": "తజ్వీద్ అంటే ప్రతి అక్షరానికి దాని హక్కు ఇవ్వడం — సరైన స్థానం నుండి, సరైన లక్షణాలతో పలకడం. ఇది అలంకారం కాదు; అర్థాన్ని కాపాడేది.",
      "en": "Tajweed means giving every letter its due: producing it from the right place with its proper qualities. It is not ornament but the thing that protects the…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-quran",
    "slug": "hifz",
    "title": {
      "te": "స్థాయి 4 — హిఫ్జ్: కంఠస్థం",
      "en": "Level 4 — Hifz: memorising"
    },
    "intro": {
      "te": "ఖురాన్ చరిత్రలో అత్యధికంగా కంఠస్థం చేయబడిన గ్రంథం. హిఫ్జ్ ప్రత్యేక ప్రతిభ కాదు — అది ఒక పద్ధతి, మరియు దాని అసలు రహస్యం కంఠస్థం కాదు, పునరావృత్తి.",
      "en": "The Quran is the most memorised book in history. Hifz is not a special talent but a method, and its real secret is not memorising but revision."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-quran",
    "slug": "tafseer",
    "title": {
      "te": "స్థాయి 5 — తఫ్సీర్: అర్థం చేసుకోవడం",
      "en": "Level 5 — Tafsir: understanding"
    },
    "intro": {
      "te": "చదవడం మొదటి మెట్టు; అర్థం చేసుకోవడం లక్ష్యం. కానీ 'నాకు అనిపించింది ఇదే' అనేది తఫ్సీర్ కాదు. ఈ పాఠం తఫ్సీర్ ఏ ఆధారాలపై నిలబడుతుందో, మీరు దాన్ని ఎలా చదవాలో…",
      "en": "Reading is the first step and understanding is the goal. But what a verse seems to say to me is not tafsir. This lesson covers what tafsir actually rests on…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-quran",
    "slug": "adab",
    "title": {
      "te": "స్థాయి 6 — ఖురాన్‌తో జీవించడం",
      "en": "Level 6 — Living with the Quran"
    },
    "intro": {
      "te": "ఖురాన్‌ను ఎలా పట్టుకోవాలి, ఎలా చదవాలి, దానితో ఎలా ఉండాలి — ఈ మర్యాదలు (అదబ్) కేవలం ఆచారాలు కాదు. అవి పఠనాన్ని అలవాటు నుండి సంభాషణగా మారుస్తాయి.",
      "en": "How to hold the Quran, how to read it, how to be with it. These manners are not mere formality; they turn recitation from a habit into a conversation."
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-quran",
    "slug": "words",
    "title": {
      "te": "స్థాయి 7 — ఖురాన్ పదాలను అర్థం చేసుకోవడం",
      "en": "Level 7 — Understanding Quranic words"
    },
    "intro": {
      "te": "ఖురాన్‌లో అత్యధికంగా వచ్చే కొన్ని వందల పదాలు మొత్తం పాఠంలో సగానికిపైగా ఆక్రమిస్తాయి. వాటిని నేర్చుకోవడం అంటే అరబిక్ భాషలో ప్రావీణ్యం కాదు — అది పఠనాన్ని వినడం…",
      "en": "A few hundred of the most frequent words make up over half the text of the Quran. Learning them is not the same as fluency; it is the difference between…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-quran",
    "slug": "daily-quran",
    "title": {
      "te": "స్థాయి 8 — రోజువారీ అలవాటు",
      "en": "Level 8 — A daily habit"
    },
    "intro": {
      "te": "ఖురాన్‌తో సంబంధం ఒక పెద్ద నిర్ణయంతో ఏర్పడదు — చిన్న, పునరావృత అలవాటుతో ఏర్పడుతుంది. ఈ పాఠం ఆ అలవాటును ఎలా నిర్మించాలో, ఎందుకు చాలామందిది విఫలమవుతుందో చెబుతుంది.",
      "en": "A relationship with the Quran is not built by one large decision but by a small, repeated habit. This lesson is about how to build it and why most attempts…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-salah",
    "slug": "why",
    "title": {
      "te": "స్థాయి 1 — మనం ఎందుకు నమాజ్ చేస్తాం",
      "en": "Level 1 — Why we pray"
    },
    "intro": {
      "te": "నమాజ్ ఇస్లాం రెండో స్తంభం, మరియు షహాదా తర్వాత మొదటి ఆచరణ. ఇది ఎందుకు అంత కేంద్ర స్థానంలో ఉందో, రోజుకు ఐదుసార్లు ఎందుకో ఈ పాఠం చెబుతుంది.",
      "en": "Prayer is the second pillar of Islam and the first practical one after the testimony of faith. This lesson is about why it sits so central, and why five times…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "learn-salah",
    "slug": "wudu",
    "title": {
      "te": "స్థాయి 2 — వుజూ",
      "en": "Level 2 — Wudu"
    },
    "intro": {
      "te": "వుజూ నమాజ్‌కు షరతు. ఖురాన్ దాన్ని నేరుగా వివరిస్తుంది, మరియు మిగిలిన వివరాలు సున్నత్ నుండి వస్తాయి. ఈ పాఠం విధులు ఏవి, సున్నత్‌లు ఏవి, దాన్ని ఏవి భంగపరుస్తాయో…",
      "en": "Wudu is a condition for prayer. The Quran describes it directly and the remaining detail comes from the Sunnah. This lesson separates what is obligatory from…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-salah",
    "slug": "ghusl",
    "title": {
      "te": "స్థాయి 3 — ఘుస్ల్",
      "en": "Level 3 — Ghusl"
    },
    "intro": {
      "te": "ఘుస్ల్ అంటే శరీరమంతటినీ కడగడం. ఇది ఎప్పుడు విధి అవుతుందో, ఎలా చేయాలో స్పష్టంగా తెలియడం ముఖ్యం — ఎందుకంటే ఘుస్ల్ లేకుండా నమాజ్ చెల్లదు, మరియు ఈ విషయాన్ని…",
      "en": "Ghusl is washing the whole body. Knowing clearly when it becomes obligatory and how to do it matters, because prayer is not valid without it and many people…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-salah",
    "slug": "howtopray",
    "title": {
      "te": "స్థాయి 4 — నమాజ్ ఎలా చేయాలి",
      "en": "Level 4 — How to pray"
    },
    "intro": {
      "te": "ఒక రక్అత్ మొత్తం క్రమం ఇక్కడ ఉంది — తక్బీర్ నుండి సలామ్ వరకు, ప్రతి స్థానంలో ఏమి చెప్పాలో సహా. మజ్‌హబ్‌ల మధ్య భేదం ఉన్న చోట అది కూడా చెప్పబడింది.",
      "en": "The full sequence of a unit of prayer, from the opening takbir to the closing salam, with what is said in each position. Where the schools differ, that is…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "learn-salah",
    "slug": "fiveprayers",
    "title": {
      "te": "స్థాయి 5 — ఐదు నమాజులు, వాటి సమయాలు",
      "en": "Level 5 — The five prayers and their times"
    },
    "intro": {
      "te": "ప్రతి నమాజుకు ఒక సమయ కిటికీ ఉంది — అది సూర్యుని స్థానం ద్వారా నిర్ణయించబడుతుంది, గడియారం ద్వారా కాదు. అందుకే నమాజ్ సమయాలు ప్రతి రోజూ, ప్రతి ఊళ్ళోనూ కొంచెం…",
      "en": "Each prayer has a window, and it is set by the position of the sun rather than by the clock. That is why prayer times shift a little every day and differ from…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "learn-salah",
    "slug": "khushu",
    "title": {
      "te": "స్థాయి 6 — ఖుషూ: హృదయం హాజరుగా",
      "en": "Level 6 — Khushu: presence of heart"
    },
    "intro": {
      "te": "మీరు నమాజ్‌లో నిలబడి, ఐదు నిమిషాల తర్వాత సలామ్ చెప్పి, మీరు ఏమి చదివారో గుర్తు లేకపోవడం — ఇది అందరికీ జరుగుతుంది. ఖుషూ అంటే ఆ సమస్యకు పరిష్కారం, మరియు దానికి…",
      "en": "Standing in prayer, giving the salam five minutes later, and not remembering a word of what you recited: this happens to everyone. Khushu is the answer to…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "learn-salah",
    "slug": "sunnah-salah",
    "title": {
      "te": "స్థాయి 7 — సున్నత్, నఫిల్ నమాజులు",
      "en": "Level 7 — Sunnah and voluntary prayers"
    },
    "intro": {
      "te": "ఫర్జ్ నమాజులకు మించి ప్రవక్త ﷺ చేసిన అదనపు నమాజులు ఉన్నాయి. ఇవి కేవలం అదనపు ప్రతిఫలం కోసం కాదు — వాటికి ఒక ప్రత్యేకమైన, ఆచరణాత్మకమైన పని ఉంది.",
      "en": "Beyond the obligatory prayers there are the additional ones the Prophet ﷺ kept. They are not only extra reward; they do a specific and practical job."
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "learn-salah",
    "slug": "fixing-salah",
    "title": {
      "te": "స్థాయి 8 — సాధారణ పొరపాట్లను సరిదిద్దడం",
      "en": "Level 8 — Fixing common mistakes"
    },
    "intro": {
      "te": "చాలామంది ఏళ్ళ తరబడి అదే పొరపాట్లతో నమాజ్ చేస్తారు, ఎందుకంటే ఎవరూ చెప్పరు. ఈ పాఠం ఆ పొరపాట్లను వరుసగా చూపుతుంది — నమాజును చెల్లనిదిగా చేసేవి, కేవలం నాణ్యతను…",
      "en": "Many people pray with the same errors for years because no one tells them. This lesson lists them, separating the ones that invalidate a prayer from the ones…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "seerah",
    "slug": "before-prophethood",
    "title": {
      "te": "స్థాయి 1 — ప్రవక్తత్వానికి ముందు",
      "en": "Level 1 — Before prophethood"
    },
    "intro": {
      "te": "నలభై సంవత్సరాలు — ఒక అనాథ బాలుడు, ఒక గొర్రెల కాపరి, ఒక వ్యాపారి. వహీ రావడానికి ముందు ఆ జీవితం ఎలా ఉందో తెలుసుకోవడం ముఖ్యం, ఎందుకంటే ఆ నలభై ఏళ్ళే ఆయన సందేశానికి…",
      "en": "Forty years: an orphaned boy, a shepherd, a trader. Knowing what that life was like before the revelation matters, because those forty years are the strongest…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "seerah",
    "slug": "beginning-of-revelation",
    "title": {
      "te": "స్థాయి 2 — వహీ ఆరంభం",
      "en": "Level 2 — The beginning of revelation"
    },
    "intro": {
      "te": "హిరా గుహలో జరిగినది ఒక ఉన్నత అనుభవం కాదు — అది భయపెట్టేది. ఆ ప్రతిస్పందన, ఆ తర్వాత జరిగినది ఆ సంఘటన నిజమని చెప్పే బలమైన సాక్ష్యాలలో ఒకటి.",
      "en": "What happened in the cave of Hira was not an exalted experience but a terrifying one. That reaction, and what followed it, is among the strongest indications…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "seerah",
    "slug": "the-makkah-period",
    "title": {
      "te": "స్థాయి 3 — మక్కా కాలం",
      "en": "Level 3 — The Makkan period"
    },
    "intro": {
      "te": "పదమూడు సంవత్సరాలు, ఒక్క యుద్ధమూ లేదు. ఈ కాలంలో ముస్లింలు హింసను ఎదుర్కొన్నారు కానీ ప్రతీకారం తీర్చుకోలేదు — ఇది ఇస్లాం చరిత్రలో అత్యంత విస్మరించబడిన భాగం.",
      "en": "Thirteen years, and not one battle. In this period the Muslims endured persecution without retaliating, and it is the most overlooked stretch of Islamic…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "seerah",
    "slug": "hijrah-and-madinah",
    "title": {
      "te": "స్థాయి 4 — హిజ్రత్, మదీనా",
      "en": "Level 4 — The Hijrah and Madinah"
    },
    "intro": {
      "te": "హిజ్రత్ ఒక పలాయనం కాదు — అది ఒక ఆహ్వానానికి సమాధానం, ఒక ప్రణాళిక. మదీనాలో జరిగినది ఇంకా ముఖ్యం: ముస్లింలు మొదటిసారి ఒక సమాజాన్ని నిర్మించారు.",
      "en": "The Hijrah was not flight but the answer to an invitation, and a planned one. What happened in Madinah matters more: for the first time the Muslims built a…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "seerah",
    "slug": "major-events-and-battles",
    "title": {
      "te": "స్థాయి 5 — ప్రధాన సంఘటనలు",
      "en": "Level 5 — The major events"
    },
    "intro": {
      "te": "మదీనా కాలంలోని యుద్ధాలు, ఒప్పందాలు ప్రతిదీ ఒక పాఠాన్ని మోస్తుంది — విజయం, ఓటమి, సంధి, క్షమాభిక్ష. వాటిని సంఘటనలుగా కాక పాఠాలుగా చదవడం ఇక్కడ లక్ష్యం.",
      "en": "Each of the battles and treaties of the Madinan years carries a lesson: victory, setback, truce, amnesty. The aim here is to read them as lessons rather than…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 1,
    "minutes": 6
  },
  {
    "portal": "seerah",
    "slug": "character-and-legacy",
    "title": {
      "te": "స్థాయి 6 — స్వభావం",
      "en": "Level 6 — His character"
    },
    "intro": {
      "te": "ఖురాన్ ఆయన గురించి చెప్పిన అత్యున్నత ప్రశంస ఆయన అద్భుతాల గురించి కాదు: 'నిశ్చయంగా నీవు గొప్ప స్వభావంపై ఉన్నావు' (అల్-ఖలమ్ 68:4). ఈ పాఠం ఆ స్వభావాన్ని నిర్దిష్ట…",
      "en": "The highest praise the Quran gives him is not about miracles: 'Indeed, you are of a great character' (Al-Qalam 68:4). This lesson shows that character through…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "seerah",
    "slug": "the-companions",
    "title": {
      "te": "స్థాయి 7 — సహాబా",
      "en": "Level 7 — The companions"
    },
    "intro": {
      "te": "సహాబా ఒక ఏకరూప సమూహం కాదు. వారిలో ధనవంతులు, బానిసలు, అరబ్బులు, పర్షియన్లు, అబిసీనియన్లు, రోమన్లు, పురుషులు, మహిళలు ఉన్నారు. ఆ వైవిధ్యమే ఇస్లాం సందేశం గురించి…",
      "en": "The companions were not one kind of person. Among them were the wealthy and the enslaved, Arabs, Persians, Abyssinians and Romans, men and women. That range…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "seerah",
    "slug": "applying-the-seerah-today",
    "title": {
      "te": "స్థాయి 8 — సీరత్‌ను నేటికి తీసుకురావడం",
      "en": "Level 8 — Bringing the seerah into now"
    },
    "intro": {
      "te": "సీరత్ చదవడం ఒక చారిత్రక వ్యాయామం కాదు. ఖురాన్ చెబుతుంది: 'నిశ్చయంగా అల్లాహ్ ప్రవక్తలో మీకు ఒక ఉత్తమ ఆదర్శం ఉంది' (అల్-అహ్‌జాబ్ 33:21). ఆదర్శం అంటే…",
      "en": "Reading the seerah is not a historical exercise. The Quran says: 'There is for you in the Messenger of Allah an excellent example' (Al-Ahzab 33:21). An example…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "prearabia",
    "title": {
      "te": "స్థాయి 1 — ఇస్లాంకు ముందటి అరేబియా",
      "en": "Level 1 — Arabia before Islam"
    },
    "intro": {
      "te": "ఇస్లాం ఏ శూన్యంలోనూ రాలేదు. అది ఒక నిర్దిష్ట సమాజంలోకి వచ్చింది — గోత్రాలుగా విడిపోయిన, రాజ్యం లేని, కానీ గర్వం, కవిత్వం, వాణిజ్యం నిండిన అరేబియా. ఆ…",
      "en": "Islam did not arrive into a vacuum. It arrived into a particular society: an Arabia divided into tribes, with no state, but full of pride, poetry and trade.…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "islamic-history",
    "slug": "prophet",
    "title": {
      "te": "స్థాయి 2 — ప్రవక్త ﷺ జీవితం: ఇరవై మూడు సంవత్సరాలు",
      "en": "Level 2 — The Prophet ﷺ: twenty-three years"
    },
    "intro": {
      "te": "ఇరవై మూడు సంవత్సరాలు — ఒక మనిషి జీవితంలో చిన్న భాగం. ఆ కాలంలో అరేబియా గోత్రాల నుండి ఒక సమాజంగా, విగ్రహారాధన నుండి ఏకదైవారాధనగా మారింది. ఈ పాఠం ఆ కాలరేఖను…",
      "en": "Twenty-three years, a small part of one man's life. In that time Arabia went from tribes to a community and from idols to the worship of one God. This lesson…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "islamic-history",
    "slug": "rashidun",
    "title": {
      "te": "స్థాయి 3 — రాషిదూన్ ఖిలాఫత్",
      "en": "Level 3 — The Rashidun Caliphate"
    },
    "intro": {
      "te": "ప్రవక్త ﷺ మరణం తర్వాత ముప్ఫై సంవత్సరాలు (632-661) నలుగురు ఖలీఫాల పాలన. వీరిని 'రాషిదూన్' — సన్మార్గంలో నడిచినవారు — అంటారు. ఈ కాలంలో ఖురాన్ ఒకే పాఠంగా…",
      "en": "The thirty years after the Prophet's death, 632 to 661, under four caliphs called the Rashidun, the rightly guided. In this period the Quran was fixed as one…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "islamic-history",
    "slug": "umayyad",
    "title": {
      "te": "స్థాయి 4 — ఉమయ్యద్ ఖిలాఫత్",
      "en": "Level 4 — The Umayyad Caliphate"
    },
    "intro": {
      "te": "661 నుండి 750 వరకు, డమాస్కస్ నుండి పాలించిన ఉమయ్యద్‌లు ఇస్లామిక్ రాజ్యాన్ని ఆనాటి ప్రపంచపు అతిపెద్ద సామ్రాజ్యంగా మార్చారు — స్పెయిన్ నుండి సింధు వరకు. వారి…",
      "en": "From 661 to 750, ruling from Damascus, the Umayyads turned the Islamic state into the largest empire of its day, from Spain to the Indus. Their period is one…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "wisdom",
    "title": {
      "te": "స్థాయి 5 — అబ్బాసీ స్వర్ణయుగం",
      "en": "Level 5 — The Abbasid Golden Age"
    },
    "intro": {
      "te": "750లో అబ్బాసీయులు అధికారంలోకి వచ్చి బాగ్దాద్‌ను నిర్మించారు. తర్వాతి కొన్ని శతాబ్దాలు ఇస్లామిక్ నాగరికత జ్ఞానంలో ప్రపంచంలో ముందుంది. ఆ కాలానికి కేంద్రం 'బైతుల్…",
      "en": "In 750 the Abbasids took power and built Baghdad. For the centuries that followed, Islamic civilisation led the world in learning, and at the centre of it…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "andalus",
    "title": {
      "te": "స్థాయి 6 — అల్-అందలుస్: ముస్లిం స్పెయిన్",
      "en": "Level 6 — Al-Andalus: Muslim Spain"
    },
    "intro": {
      "te": "711 నుండి 1492 వరకు — దాదాపు ఎనిమిది వందల సంవత్సరాలు — స్పెయిన్‌లో ముస్లిం పాలన కొనసాగింది. కార్డోబా ఆనాటి యూరప్‌లో అత్యంత అభివృద్ధి చెందిన నగరం. కానీ ఈ కథను…",
      "en": "From 711 to 1492, almost eight hundred years of Muslim rule in Spain, with Cordoba the most advanced city in Europe of its day. But the story is worth telling…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "ottoman",
    "title": {
      "te": "స్థాయి 7 — ఒట్టోమన్ సామ్రాజ్యం",
      "en": "Level 7 — The Ottoman Empire"
    },
    "intro": {
      "te": "1299లో ఒక చిన్న అనటోలియన్ రాజ్యంగా మొదలై, ఆరు వందల సంవత్సరాలు మూడు ఖండాలలో విస్తరించిన సామ్రాజ్యం. చరిత్రలో అత్యంత సుదీర్ఘ కాలం నిలిచిన ముస్లిం రాజవంశాలలో ఇది…",
      "en": "Beginning in 1299 as a small Anatolian principality and lasting six centuries across three continents, the Ottomans were among the longest-lived Muslim…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "scholars",
    "title": {
      "te": "స్థాయి 8 — పండితులు, శాస్త్రవేత్తలు",
      "en": "Level 8 — The scholars and scientists"
    },
    "intro": {
      "te": "ముస్లిం నాగరికత ప్రపంచానికి ఇచ్చినవి కేవలం భవనాలు, సామ్రాజ్యాలు కాదు. ఆల్జీబ్రా, ఆల్గరిథమ్, ఆధునిక వైద్యం, ప్రయోగాత్మక పద్ధతి — ఈ పదాల వెనుక నిర్దిష్ట…",
      "en": "What Muslim civilisation gave the world was not only buildings and empires. Algebra, the algorithm, modern medicine, the experimental method: there are…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "colonial",
    "title": {
      "te": "స్థాయి 9 — వలస యుగం",
      "en": "Level 9 — The colonial era"
    },
    "intro": {
      "te": "పద్దెనిమిదో శతాబ్దం నుండి ఇరవయ్యో శతాబ్దం వరకు ముస్లిం ప్రపంచంలో అత్యధిక భాగం యూరోపియన్ పాలనలోకి వెళ్ళింది. ఇది కేవలం రాజకీయ మార్పు కాదు — విద్య, చట్టం, ఆర్థిక…",
      "en": "From the eighteenth to the twentieth century most of the Muslim world came under European rule. This was not only a political change; education, law, economies…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-history",
    "slug": "modern",
    "title": {
      "te": "స్థాయి 10 — నేటి ముస్లిం ప్రపంచం",
      "en": "Level 10 — The Muslim world today"
    },
    "intro": {
      "te": "నేడు ప్రపంచంలో దాదాపు రెండు వందల కోట్ల ముస్లింలు ఉన్నారు — ప్రతి నలుగురిలో ఒకరు. కానీ మనం ఊహించే ముస్లిం ప్రపంచం, వాస్తవంలో ఉన్నది వేరు.",
      "en": "There are close to two billion Muslims in the world today, roughly one person in four. But the Muslim world we picture and the one that exists are not the same."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "my-first-islam",
    "title": {
      "te": "స్థాయి 1 — నా మొదటి ఇస్లాం",
      "en": "Level 1 — My first Islam"
    },
    "intro": {
      "te": "ఇస్లాం అంటే శాంతి. అది అల్లాహ్‌ను తెలుసుకోవడంతో, ఆయనను ప్రేమించడంతో మొదలవుతుంది — ఆయనే అన్నిటినీ సృష్టించాడు.",
      "en": "Islam means peace, and it starts with knowing Allah and loving Him. He is the One who made everything."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "good-manners",
    "title": {
      "te": "స్థాయి 2 — మంచి నడవడిక",
      "en": "Level 2 — Good manners"
    },
    "intro": {
      "te": "మంచి నడవడిక ఒక శక్తి. దయ, నిజాయితీ, గౌరవం — ఇవి అల్లాహ్‌కు ఇష్టం, మరియు మీ చుట్టూ ఉన్నవారిని సంతోషపెడతాయి.",
      "en": "Good manners are a kind of strength. Kindness, honesty and respect please Allah and make the people around you glad."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "daily-duas",
    "title": {
      "te": "స్థాయి 3 — రోజువారీ దుఆలు",
      "en": "Level 3 — Everyday duas"
    },
    "intro": {
      "te": "దుఆ అంటే అల్లాహ్‌తో మాట్లాడటం. దానికి ప్రత్యేక సమయం అవసరం లేదు, ప్రత్యేక చోటు అవసరం లేదు — రోజంతా ఎప్పుడైనా.",
      "en": "A du'a is talking to Allah. It needs no special time and no special place; you can do it at any point in the day."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "stories-of-the-prophets",
    "title": {
      "te": "స్థాయి 4 — ప్రవక్తల కథలు",
      "en": "Level 4 — Stories of the prophets"
    },
    "intro": {
      "te": "అల్లాహ్ చాలామంది ప్రవక్తలను పంపాడు. వారి కథలు కేవలం కథలు కాదు — ప్రతిదానిలో ఒక పాఠం ఉంది.",
      "en": "Allah sent many prophets. Their stories are not just stories; each one carries a lesson."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "salah-and-quran-basics",
    "title": {
      "te": "స్థాయి 5 — నమాజ్, ఖురాన్ ప్రాథమికాలు",
      "en": "Level 5 — Prayer and Quran basics"
    },
    "intro": {
      "te": "నమాజ్ మనం అల్లాహ్‌తో మాట్లాడే విధానం. ఖురాన్ అల్లాహ్ మనతో మాట్లాడే విధానం. రెండూ కలిసి ఒక సంభాషణ.",
      "en": "Prayer is how we talk to Allah. The Quran is how Allah talks to us. Together they make a conversation."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "young-muslim-leadership",
    "title": {
      "te": "స్థాయి 6 — యువ ముస్లిం నాయకత్వం",
      "en": "Level 6 — Young Muslim leadership"
    },
    "intro": {
      "te": "నాయకుడు అంటే ఆజ్ఞలు ఇచ్చేవాడు కాదు. ఇస్లాంలో నాయకుడు అంటే బాధ్యత తీసుకునేవాడు — మరియు మీరు ఇప్పుడే మొదలుపెట్టవచ్చు.",
      "en": "A leader is not someone who gives orders. In Islam a leader is someone who takes responsibility, and you can start now."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "ramadan-and-eid",
    "title": {
      "te": "స్థాయి 7 — రమదాన్, ఈద్",
      "en": "Level 7 — Ramadan and Eid"
    },
    "intro": {
      "te": "రమదాన్ సంవత్సరంలో అత్యంత ప్రత్యేకమైన నెల. దాని చివర ఈద్ — ఒక పండుగ, కానీ కేవలం తినడం, బట్టల కోసం కాదు.",
      "en": "Ramadan is the most special month of the year, and Eid comes at the end of it. Eid is a celebration, though not only about food and new clothes."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "kids-islam",
    "slug": "honesty-and-courage",
    "title": {
      "te": "స్థాయి 8 — నిజాయితీ, ధైర్యం",
      "en": "Level 8 — Honesty and courage"
    },
    "intro": {
      "te": "నిజం చెప్పడానికి కొన్నిసార్లు ధైర్యం కావాలి. అందుకే ఈ రెండూ కలిసి ఉంటాయి.",
      "en": "Telling the truth sometimes takes courage. That is why these two belong together."
    },
    "sections": 7,
    "quiz": 3,
    "faqs": 1,
    "minutes": 5
  },
  {
    "portal": "learn-arabic",
    "slug": "alphabet",
    "title": {
      "te": "స్థాయి 1 — అరబిక్ అక్షరమాల",
      "en": "Level 1 — The Arabic alphabet"
    },
    "intro": {
      "te": "అరబిక్ 28 అక్షరాలతో, కుడి నుండి ఎడమకు, అక్షరాలు ఒకదానితో ఒకటి కలుస్తూ రాయబడుతుంది. ఈ పాఠం అక్షరాల ఆకారాలు ఎందుకు మారతాయో, ఏవి కలవవో, చుక్కలు ఎందుకు అంత ముఖ్యమో…",
      "en": "Arabic is written with 28 letters, right to left, with the letters joined to one another. This lesson explains why letter shapes change, which letters refuse…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-arabic",
    "slug": "harakat",
    "title": {
      "te": "స్థాయి 2 — హరకాత్ మరియు స్వరాలు",
      "en": "Level 2 — Harakat and vowels"
    },
    "intro": {
      "te": "అరబిక్ అక్షరాలు హల్లులు మాత్రమే. ఏ స్వరం రావాలో చెప్పేవి హరకాత్ — అక్షరం పైన కింద పెట్టే చిన్న గుర్తులు. ఇవి లేకపోతే ఒకే మూడు అక్షరాల పదాన్ని 'కతబ', 'కుతుబ',…",
      "en": "Arabic letters are consonants. What tells you which vowel follows are the harakat, small marks placed above and below. Without them the same three letters…"
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-arabic",
    "slug": "vocabulary",
    "title": {
      "te": "స్థాయి 3 — మూలాలు మరియు పదజాలం",
      "en": "Level 3 — Roots and vocabulary"
    },
    "intro": {
      "te": "అరబిక్ పదజాలం యాదృచ్ఛికం కాదు. దాదాపు ప్రతి పదం మూడు హల్లుల మూలం నుండి పుడుతుంది, మరియు ఆ మూలం ఒక నిర్దిష్ట నమూనాలో పెడితే ఊహించదగిన అర్థం వస్తుంది. ఇది…",
      "en": "Arabic vocabulary is not arbitrary. Almost every word grows from a root of three consonants, and putting that root into a given pattern yields a predictable…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-arabic",
    "slug": "grammar",
    "title": {
      "te": "స్థాయి 4 — వ్యాకరణ ప్రాథమికాలు",
      "en": "Level 4 — Grammar basics"
    },
    "intro": {
      "te": "అరబిక్ వ్యాకరణం భయపెట్టేదిగా అనిపిస్తుంది, కానీ దాని పునాది చాలా చిన్నది: ప్రతి పదం మూడు రకాల్లో ఒకటి, మరియు ప్రతి వాక్యం రెండు ఆకారాల్లో ఒకటి. ఇంతే తెలిస్తే…",
      "en": "Arabic grammar sounds forbidding, but its foundation is small: every word is one of three kinds, and every sentence is one of two shapes. Knowing only that…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-arabic",
    "slug": "quranic",
    "title": {
      "te": "స్థాయి 5 — ఖురానిక్ అరబిక్",
      "en": "Level 5 — Quranic Arabic"
    },
    "intro": {
      "te": "ఖురాన్ అర్థం చేసుకోవడానికి అరబిక్ భాషలో ప్రావీణ్యం అవసరం లేదు. ఖురాన్ పదాల్లో అత్యధిక భాగం చాలా చిన్న పదాల సముదాయం నుండే వస్తుంది. ఆ సముదాయాన్ని నేర్చుకోవడమే…",
      "en": "Understanding the Quran does not require fluency in Arabic. A very large share of its words comes from a surprisingly small set. Learning that set is the aim…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-arabic",
    "slug": "daily",
    "title": {
      "te": "స్థాయి 6 — రోజువారీ అరబిక్",
      "en": "Level 6 — Everyday Arabic"
    },
    "intro": {
      "te": "ఈ పాఠం చదవడం గురించి కాదు, మాట్లాడటం గురించి. ముస్లింలు రోజూ ఉపయోగించే పదబంధాలు — పలకరింపులు, కృతజ్ఞత, అల్లాహ్ ఇష్టాన్ని ప్రస్తావించడం — వాటి అర్థం, ఎప్పుడు…",
      "en": "This lesson is about speaking rather than reading: the phrases Muslims use daily, what they actually mean, and when each one is said."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-urdu",
    "slug": "alphabet",
    "title": {
      "te": "స్థాయి 1 — ఉర్దూ అక్షరమాల",
      "en": "Level 1 — The Urdu alphabet"
    },
    "intro": {
      "te": "ఉర్దూ 39 అక్షరాలతో, కుడి నుండి ఎడమకు రాయబడుతుంది. దాని లిపి అరబిక్ నుండి వచ్చినా, దక్షిణాసియా శబ్దాల కోసం అదనపు అక్షరాలు చేర్చుకుంది. మీకు అరబిక్ తెలిస్తే సగం…",
      "en": "Urdu is written with 39 letters, right to left. Its script comes from Arabic but adds letters for sounds South Asian languages need. If you already read…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-urdu",
    "slug": "reading",
    "title": {
      "te": "స్థాయి 2 — చదవడం ప్రాథమికాలు",
      "en": "Level 2 — Reading basics"
    },
    "intro": {
      "te": "అక్షరాలు తెలిసిన తర్వాత అసలు పని మొదలవుతుంది: వాటిని కలిపి పదాలుగా చదవడం. ఉర్దూలో ఇబ్బంది ఏమిటంటే ముద్రిత పాఠంలో స్వర గుర్తులు ఉండవు — వాటిని మీరే ఊహించాలి.",
      "en": "Once you know the letters the real work starts: joining them into words. The difficulty in Urdu is that printed text carries no vowel marks, so you have to…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-urdu",
    "slug": "writing",
    "title": {
      "te": "స్థాయి 3 — రాయడం నేర్చుకోవడం",
      "en": "Level 3 — Learning to write"
    },
    "intro": {
      "te": "ఉర్దూ రాయడం అరబిక్ రాయడం కంటే వేరు, ఎందుకంటే నస్తలీక్ శైలిలో పదం సమతలంగా ఉండదు — అది వాలుతుంది. ఈ పాఠం అక్షర క్రమం, వాలు, చుక్కలు ఎప్పుడు పెట్టాలి అనేవి…",
      "en": "Writing Urdu differs from writing Arabic because in nastaliq a word does not sit level, it slopes. This lesson covers stroke order, the slope, and when to add…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-urdu",
    "slug": "daily",
    "title": {
      "te": "స్థాయి 4 — రోజువారీ ఉర్దూ",
      "en": "Level 4 — Everyday Urdu"
    },
    "intro": {
      "te": "ఉర్దూ వ్యాకరణం తెలుగు మాట్లాడేవారికి ఆశ్చర్యకరంగా సులభం — పదక్రమం దాదాపు ఒకటే. ఈ పాఠం రోజువారీ పదబంధాలతో పాటు ఆ నిర్మాణాన్ని కూడా చూపుతుంది.",
      "en": "Urdu grammar is unexpectedly easy for a Telugu speaker, because the word order is nearly the same. This lesson gives the everyday phrases and shows that…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-urdu",
    "slug": "islamic",
    "title": {
      "te": "స్థాయి 5 — ఇస్లామిక్ ఉర్దూ",
      "en": "Level 5 — Islamic Urdu"
    },
    "intro": {
      "te": "దక్షిణాసియాలో ఇస్లామిక్ జ్ఞానం చాలావరకు ఉర్దూలోనే బోధించబడుతుంది. ఖుత్బాలు, మదరసా పాఠాలు, ఫత్వాలు, తఫ్సీర్ గ్రంథాలు — అన్నీ ఉర్దూలో. అందుకే ఈ పరిభాష తెలియడం…",
      "en": "Most Islamic teaching in South Asia happens in Urdu: sermons, madrasa lessons, fatwas and works of tafsir. Knowing this vocabulary has practical value here."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "learn-urdu",
    "slug": "advanced",
    "title": {
      "te": "స్థాయి 6 — ఉన్నత ఉర్దూ",
      "en": "Level 6 — Advanced Urdu"
    },
    "intro": {
      "te": "ఈ దశలో మీరు గుర్తులు లేని పాఠాన్ని చదవగలరు. ఇక్కడి నుండి ఉర్దూ సాహిత్యం తెరుచుకుంటుంది — ముఖ్యంగా కవిత్వం, ఇది ఈ భాష అత్యంత గొప్ప సంపద.",
      "en": "By this stage you can read unmarked text. From here Urdu literature opens up, and above all its poetry, which is the language's greatest wealth."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hadith",
    "slug": "what-is-hadith",
    "title": {
      "te": "స్థాయి 1 — హదీసు అంటే ఏమిటి",
      "en": "Level 1 — What a hadith is"
    },
    "intro": {
      "te": "ఖురాన్ అల్లాహ్ వాక్కు. హదీసు ప్రవక్త ﷺ మాట, ఆచరణ, లేదా ఆమోదం. రెండూ వేరు, మరియు ఆ తేడా తెలియడం ముఖ్యం.",
      "en": "The Quran is the word of Allah. A hadith is what the Prophet ﷺ said, did, or approved of. They are different things, and the difference matters."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hadith",
    "slug": "how-it-was-checked",
    "title": {
      "te": "స్థాయి 2 — ఉల్లేఖనలు ఎలా పరిశీలించబడ్డాయి",
      "en": "Level 2 — How narrations were checked"
    },
    "intro": {
      "te": "ఒక మాట నిజంగా ప్రవక్త ﷺది అని ఎలా నిర్ధారిస్తారు? దీనికోసం ముస్లిం పండితులు ఒక పూర్తి శాస్త్రాన్ని అభివృద్ధి చేశారు — మరియు అది చాలా కఠినమైనది.",
      "en": "How do you establish that a saying really is the Prophet's? Muslim scholars built a whole discipline for it, and it is a demanding one."
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 6
  },
  {
    "portal": "hadith",
    "slug": "the-six-books",
    "title": {
      "te": "స్థాయి 3 — ఆరు గ్రంథాలు",
      "en": "Level 3 — The six collections"
    },
    "intro": {
      "te": "సున్నీ సంప్రదాయంలో ఆరు ప్రధాన సంకలనాలు ఉన్నాయి. అవన్నీ ఒకే స్థాయివి కావు, మరియు ఏది ఏమిటో తెలియడం ఒక ఉల్లేఖనను ఎలా తీసుకోవాలో నిర్ణయిస్తుంది.",
      "en": "The Sunni tradition has six principal collections. They do not all carry the same standing, and knowing which is which decides how you take a narration."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hadith",
    "slug": "living-by-it",
    "title": {
      "te": "స్థాయి 4 — హదీసుతో జీవించడం",
      "en": "Level 4 — Living by hadith"
    },
    "intro": {
      "te": "హదీసు తెలుసుకోవడం ఒక విషయం; దాని ప్రకారం జీవించడం మరొకటి. మరియు దాన్ని బాధ్యతగా వాడటం ఇంకొకటి — ఇక్కడే చాలామంది తప్పు చేస్తారు.",
      "en": "Knowing a hadith is one thing, living by it another, and using it responsibly a third. That last is where most people go wrong."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hajj-umrah",
    "slug": "why-hajj",
    "title": {
      "te": "స్థాయి 1 — హజ్ ఎందుకు, ఎవరిపై విధి",
      "en": "Level 1 — Why Hajj, and who it is due upon"
    },
    "intro": {
      "te": "హజ్ ఇస్లాం ఐదు స్తంభాలలో ఐదవది. జీవితకాలంలో ఒక్కసారి, సామర్థ్యం ఉన్నవారిపై మాత్రమే విధి. ఈ పాఠం అది ఎవరిపై విధి అవుతుందో, ఎప్పుడు వాయిదా వేయడం సరైనదో…",
      "en": "Hajj is the fifth pillar of Islam: obligatory once in a lifetime, and only upon those with the means. This lesson covers who it falls upon and when delaying it…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hajj-umrah",
    "slug": "ihram",
    "title": {
      "te": "స్థాయి 2 — ఇహ్రామ్ మరియు మీఖాత్",
      "en": "Level 2 — Ihram and the Miqat"
    },
    "intro": {
      "te": "ఇహ్రామ్ కేవలం రెండు తెల్లని వస్త్రాలు కాదు — అది ఒక ఉద్దేశం, ఒక స్థితి. మీఖాత్ దాటే ముందు దానిలో ప్రవేశించాలి. ఈ పాఠం ఎక్కడ, ఎలా, ఏ నియమాలతో అని వివరిస్తుంది.",
      "en": "Ihram is not simply two white cloths; it is an intention and a state you enter. You must be in it before crossing the miqat. This lesson covers where, how, and…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hajj-umrah",
    "slug": "types",
    "title": {
      "te": "స్థాయి 3 — హజ్ మూడు రకాలు",
      "en": "Level 3 — The three types of Hajj"
    },
    "intro": {
      "te": "హజ్‌లో మూడు రకాలు ఉన్నాయి: ఇఫ్రాద్, ఖిరాన్, తమత్తుఅ. ఏది ఎంచుకుంటారో అది మీ ఇహ్రామ్ ఎప్పుడు ముగుస్తుందో, జంతు అర్పణ అవసరమా అనేదాన్ని నిర్ణయిస్తుంది. చాలామంది…",
      "en": "Hajj comes in three forms: ifrad, qiran and tamattu. Which you choose decides when your ihram ends and whether a sacrifice is due. Most pilgrims from India…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 4
  },
  {
    "portal": "hajj-umrah",
    "slug": "tawaf-sai",
    "title": {
      "te": "స్థాయి 4 — తవాఫ్ మరియు సఅయి",
      "en": "Level 4 — Tawaf and Sa'i"
    },
    "intro": {
      "te": "తవాఫ్ కాబా చుట్టూ ఏడు ప్రదక్షిణలు; సఅయి సఫా-మర్వా మధ్య ఏడు నడకలు. ఈ రెండూ ఉమ్రహ్‌లోనూ హజ్‌లోనూ వస్తాయి. ఈ పాఠం వాటిని ఎలా చేయాలో, ఎక్కడ తప్పులు జరుగుతాయో…",
      "en": "Tawaf is seven circuits around the Kaaba; sa'i is seven walks between Safa and Marwah. Both appear in Umrah and in Hajj. This lesson covers how each is…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hajj-umrah",
    "slug": "days-of-hajj",
    "title": {
      "te": "స్థాయి 5 — హజ్ ఐదు రోజులు",
      "en": "Level 5 — The five days of Hajj"
    },
    "intro": {
      "te": "జుల్-హిజ్జా 8 నుండి 12 (లేదా 13) వరకు — మినా, అరఫా, ముజ్దలిఫా, జమారాత్. ఈ పాఠం ప్రతి రోజు ఏమి జరుగుతుందో వరుసగా చెబుతుంది.",
      "en": "From 8 to 12 (or 13) Dhu al-Hijjah: Mina, Arafah, Muzdalifah and the Jamarat. This lesson walks through what happens on each day, in order."
    },
    "sections": 5,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "hajj-umrah",
    "slug": "umrah",
    "title": {
      "te": "స్థాయి 6 — ఉమ్రహ్ దశలవారీగా",
      "en": "Level 6 — Umrah step by step"
    },
    "intro": {
      "te": "ఉమ్రహ్ నాలుగు దశలు మాత్రమే, సంవత్సరంలో ఎప్పుడైనా చేయవచ్చు. హజ్ కంటే చాలా చిన్నది, కానీ అదే ఇహ్రామ్ నియమాలు వర్తిస్తాయి.",
      "en": "Umrah is only four steps and can be performed at any time of year. It is far shorter than Hajj, but the same rules of ihram apply."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 4
  },
  {
    "portal": "names-of-allah",
    "slug": "what-they-are",
    "title": {
      "te": "స్థాయి 1 — అస్మా ఉల్-హుస్నా అంటే ఏమిటి",
      "en": "Level 1 — What the Beautiful Names are"
    },
    "intro": {
      "te": "అల్-అస్మా ఉల్-హుస్నా అంటే 'అత్యంత సుందరమైన పేర్లు'. ఇవి అల్లాహ్ తనను తాను వర్ణించుకున్న పేర్లు. ఈ పాఠం అవి ఎక్కడి నుండి వచ్చాయో, వాటిని ఎందుకు మనం సొంతంగా…",
      "en": "Al-Asma ul-Husna means 'the most beautiful names': the names by which Allah has described Himself. This lesson covers where they come from and why we cannot…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "names-of-allah",
    "slug": "ninety-nine",
    "title": {
      "te": "స్థాయి 2 — తొంభై తొమ్మిది అనే సంఖ్య",
      "en": "Level 2 — The number ninety-nine"
    },
    "intro": {
      "te": "'అల్లాహ్‌కు తొంభై తొమ్మిది పేర్లు ఉన్నాయి' అనే హదీసు అందరికీ తెలుసు. కానీ దాని అర్థం అల్లాహ్‌కు అన్నే పేర్లు ఉన్నాయనా? 'ఇహ్సా' అంటే కేవలం లెక్కపెట్టడమా? ఈ పాఠం…",
      "en": "The hadith that Allah has ninety-nine names is widely known. But does it mean He has only that many? And does 'ihsa' mean simply counting? This lesson answers…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "names-of-allah",
    "slug": "mercy-and-majesty",
    "title": {
      "te": "స్థాయి 3 — కారుణ్యం మరియు గాంభీర్యం",
      "en": "Level 3 — Mercy and majesty"
    },
    "intro": {
      "te": "పండితులు పేర్లను రెండు వర్గాలుగా చూస్తారు: జమాల్ (సౌందర్యం, కారుణ్యం) మరియు జలాల్ (గాంభీర్యం, శక్తి). ఈ రెండింటినీ కలిపి తెలుసుకోవడం ముఖ్యం — ఒక్కదాన్నే చూస్తే…",
      "en": "Scholars group the names into two: jamal, the names of beauty and mercy, and jalal, the names of majesty and power. Holding both together matters, because…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 4
  },
  {
    "portal": "islamic-calendar",
    "slug": "how-it-works",
    "title": {
      "te": "స్థాయి 1 — హిజ్రీ క్యాలెండర్ ఎలా పనిచేస్తుంది",
      "en": "Level 1 — How the Hijri calendar works"
    },
    "intro": {
      "te": "హిజ్రీ సంవత్సరం చంద్రుడిపై ఆధారపడి ఉంటుంది — సూర్యుడిపై కాదు. అందుకే రమజాన్ ప్రతి సంవత్సరం కొంచెం ముందుకు కదులుతుంది. ఈ పాఠం ఆ వ్యవస్థను, అది ఎక్కడి నుండి…",
      "en": "The Hijri year follows the moon, not the sun, which is why Ramadan moves earlier each year. This lesson explains that system and where it began."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 4
  },
  {
    "portal": "islamic-calendar",
    "slug": "moon-sighting",
    "title": {
      "te": "స్థాయి 2 — చంద్రవంక దర్శనం, ఈద్ తేదీలు వేరవడం",
      "en": "Level 2 — Moon sighting, and why Eid dates differ"
    },
    "intro": {
      "te": "ప్రతి సంవత్సరం ఒకే ఊళ్ళో రెండు ఈద్‌లు జరగడం చూస్తాం. ఇది గందరగోళం కలిగిస్తుంది, కొన్నిసార్లు గొడవలకూ దారితీస్తుంది. ఈ పాఠం దాని వెనుక ఉన్న నిజమైన ఫిఖ్హ్…",
      "en": "Most years we see two Eids in the same town. It causes confusion and sometimes argument. This lesson explains the genuine difference of fiqh behind it, rather…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "islamic-calendar",
    "slug": "sacred-months",
    "title": {
      "te": "స్థాయి 3 — నాలుగు పవిత్ర మాసాలు",
      "en": "Level 3 — The four sacred months"
    },
    "intro": {
      "te": "పన్నెండు మాసాల్లో నాలుగు పవిత్రమైనవని ఖురాన్ చెబుతుంది. అవి ఏవి, వాటిలో ఏమి ప్రత్యేకం, ఆచరణలో అది ఏమి కోరుతుంది — ఈ పాఠంలో.",
      "en": "The Quran singles out four of the twelve months as sacred. Which they are, what makes them so, and what that asks of us in practice."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 4
  },
  {
    "portal": "special-prayers",
    "slug": "night-prayer",
    "title": {
      "te": "స్థాయి 1 — రాత్రి నమాజ్: తహజ్జుద్, విత్ర్, ఖునూత్",
      "en": "Level 1 — The night prayer: Tahajjud, Witr and Qunoot"
    },
    "intro": {
      "te": "రాత్రి నమాజ్ (ఖియామ్ అల్-లైల్) ఫర్జ్ నమాజుల తర్వాత అత్యుత్తమ నమాజని ప్రవక్త ﷺ చెప్పారు. ఈ పాఠం తహజ్జుద్, విత్ర్, దుఆ-ఎ-ఖునూత్ — మూడింటినీ కలిపి వివరిస్తుంది.",
      "en": "The Prophet ﷺ said the night prayer is the best prayer after the obligatory ones. This lesson covers Tahajjud, Witr and the du'a al-Qunoot together, since in…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "special-prayers",
    "slug": "tarawih",
    "title": {
      "te": "స్థాయి 2 — తరావీహ్: ఎనిమిదా, ఇరవైనా",
      "en": "Level 2 — Tarawih: eight or twenty"
    },
    "intro": {
      "te": "ప్రతి రమదాన్‌లో ఈ ప్రశ్న సమాజాలను విభజిస్తుంది. ఈ పాఠం రెండు వైపుల ఆధారాలను నిజాయితీగా చూపుతుంది, మరియు పండితులు ఎందుకు రెండింటినీ చెల్లుబాటుగా భావిస్తారో…",
      "en": "This question divides communities every Ramadan. This lesson sets out the evidence on both sides honestly, and explains why scholars hold both to be valid."
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "special-prayers",
    "slug": "janazah",
    "title": {
      "te": "స్థాయి 3 — జనాజా నమాజ్",
      "en": "Level 3 — The funeral prayer"
    },
    "intro": {
      "te": "జనాజా నమాజ్ ఫర్జ్ కిఫాయా — సమాజంలో కొందరు చేస్తే అందరిపై నుండి బాధ్యత తీరుతుంది; ఎవరూ చేయకపోతే అందరూ బాధ్యులు. ఇది చాలా చిన్నది, కానీ చాలామందికి రాదు. ఈ పాఠం…",
      "en": "The funeral prayer is fard kifayah: if some in the community perform it the obligation lifts from all, and if none do, all are answerable. It is very short,…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "womens-guidance",
    "slug": "nikah",
    "title": {
      "te": "స్థాయి 1 — నికాహ్: ఒప్పందం, మహర్, హక్కులు",
      "en": "Level 1 — Nikah: the contract, the mahr, and rights"
    },
    "intro": {
      "te": "నికాహ్ ఒక ఒప్పందం — ఒక వేడుక మాత్రమే కాదు. దానికి నిర్దిష్ట స్తంభాలు, షరతులు ఉన్నాయి, మరియు స్త్రీకి కొన్ని హక్కులు ఉన్నాయి, వాటిని ఎవరూ తీసివేయలేరు. ఈ పాఠం ఆ…",
      "en": "Nikah is a contract, not only a celebration. It has defined pillars and conditions, and it gives a woman rights that no one can take from her. This lesson sets…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  },
  {
    "portal": "womens-guidance",
    "slug": "iddah",
    "title": {
      "te": "స్థాయి 2 — ఇద్దత్: వేచి ఉండే కాలం",
      "en": "Level 2 — Iddah: the waiting period"
    },
    "intro": {
      "te": "విడాకుల తర్వాత లేదా భర్త మరణం తర్వాత స్త్రీ ఒక నిర్ణీత కాలం వేచి ఉంటుంది — దాన్ని ఇద్దత్ అంటారు. దాని వ్యవధులు, దాని ఉద్దేశం, ఆ కాలంలో ఆమె హక్కులు ఏమిటో ఈ…",
      "en": "After divorce or the death of a husband, a woman observes a defined waiting period called the iddah. This lesson covers its durations, its purpose, and her…"
    },
    "sections": 4,
    "quiz": 3,
    "faqs": 2,
    "minutes": 5
  }
];

export const summariesByPortal = (portal: string) =>
  lessonSummaries.filter((l) => l.portal === portal);
