/* Hand-authored lessons.

   src/content/lessons.ts is regenerated by scripts/extract-lessons.mjs from the
   legacy static site, so anything written into it by hand is lost on the next
   run. Lessons written for this site live here instead, and
   src/content/all-lessons.ts merges the two.

   Portals covered here have no counterpart in the legacy site: they shipped as
   single-page guides with a sentence per topic, which is an index rather than
   something a reader can learn from.

   House rules for anything added to this file:
     - Every string carries both `te` and `en`. No English-only fields.
     - State only what is agreed across the four Sunni schools, and where they
       differ, say that they differ rather than picking one silently.
     - Arabic is given with a transliteration and a translation, never alone.
     - No claim of a specific reward or ruling without naming its source.
*/
import type { Lesson } from "./lessons";

export const authoredLessons: Lesson[] = [
  {
    slug: "why-hajj",
    portal: "hajj-umrah",
    title: {
      te: "స్థాయి 1 — హజ్ ఎందుకు, ఎవరిపై విధి",
      en: "Level 1 — Why Hajj, and who it is due upon",
    },
    intro: {
      te: "హజ్ ఇస్లాం ఐదు స్తంభాలలో ఐదవది. జీవితకాలంలో ఒక్కసారి, సామర్థ్యం ఉన్నవారిపై మాత్రమే విధి. ఈ పాఠం అది ఎవరిపై విధి అవుతుందో, ఎప్పుడు వాయిదా వేయడం సరైనదో వివరిస్తుంది.",
      en: "Hajj is the fifth pillar of Islam: obligatory once in a lifetime, and only upon those with the means. This lesson covers who it falls upon and when delaying it is the correct decision.",
    },
    sections: [
      {
        heading: { te: "ఐదవ స్తంభం", en: "The fifth pillar" },
        body: {
          te: "అల్లాహ్ ఖురాన్‌లో అంటున్నాడు: 'ఆ గృహానికి హజ్ చేయడం, అక్కడికి చేరగల శక్తి ఉన్నవారిపై అల్లాహ్ కోసం విధి' (ఆల్-ఇమ్రాన్ 3:97). 'చేరగల శక్తి' అనే షరతు ఆయతులోనే ఉంది — ఇది తర్వాత చేర్చిన మినహాయింపు కాదు.",
          en: "Allah says in the Quran: 'Pilgrimage to the House is a duty owed to Allah by those people who can afford the journey' (Al-Imran 3:97). The condition of being able is in the verse itself; it is not a concession added later.",
        },
        check: {
          question: {
            te: "హజ్ ఎన్నిసార్లు విధి?",
            en: "How many times is Hajj obligatory?",
          },
          options: [
            { te: "జీవితకాలంలో ఒక్కసారి", en: "Once in a lifetime" },
            { te: "ప్రతి సంవత్సరం", en: "Every year" },
            { te: "ప్రతి ఐదేళ్ళకు ఒకసారి", en: "Once every five years" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "సామర్థ్యం అంటే ఏమిటి", en: "What counts as being able" },
        body: {
          te: "పండితులు సామర్థ్యాన్ని మూడు భాగాలుగా చూస్తారు. ఒకటి: ప్రయాణ ఖర్చు, మీరు తిరిగి వచ్చేవరకు కుటుంబ ఖర్చులు — అప్పు తీసుకోకుండా. రెండు: ప్రయాణం, ఆచారాలు తట్టుకునే శారీరక ఆరోగ్యం. మూడు: మార్గం సురక్షితం కావడం, ప్రయాణానికి అనుమతి ఉండటం.",
          en: "Scholars treat ability as three things. First, the cost of the journey and of your family's needs until you return, without taking on debt. Second, the physical health to bear the travel and the rites. Third, that the route is safe and travel is permitted.",
        },
        check: {
          question: {
            te: "హజ్ కోసం అప్పు తీసుకోవడం అవసరమా?",
            en: "Is it required to borrow money in order to perform Hajj?",
          },
          options: [
            { te: "కాదు — అప్పు లేకుండా స్తోమత ఉంటేనే విధి", en: "No, it is only due if you can afford it without debt" },
            { te: "అవును, ఎలాగైనా వెళ్ళాలి", en: "Yes, one must go by any means" },
            { te: "బంగారం అమ్మి అయినా వెళ్ళాలి", en: "Yes, one must sell gold to go" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "మహిళలకు మహ్రమ్ విషయం", en: "The question of a mahram for women" },
        body: {
          te: "ఇక్కడ మజ్‌హబ్‌ల మధ్య భేదం ఉంది, దాన్ని దాచడం సరికాదు. హనఫీ, హంబలీ పండితులు మహిళ హజ్‌కు భర్త లేదా మహ్రమ్ తోడు ఉండాలని అంటారు. షాఫయీ, మాలికీ పండితులు సురక్షితమైన బృందంతో వెళ్ళడం సరిపోతుందని అంటారు. మీ కుటుంబ పరిస్థితికి తగిన మార్గదర్శనం కోసం స్థానిక ఆలిమ్‌ను సంప్రదించండి.",
          en: "The schools differ here, and it would be wrong to hide that. Hanafi and Hanbali scholars hold that a woman travels for Hajj with her husband or a mahram. Shafi'i and Maliki scholars hold that travelling with a safe, trustworthy group suffices. Ask a local scholar for guidance suited to your family's situation.",
        },
      },
      {
        heading: { te: "వాయిదా వేయడం ఎప్పుడు సరైనది", en: "When delaying is the right call" },
        body: {
          te: "సామర్థ్యం లేనప్పుడు హజ్ విధి కాదు — వాయిదా వేయడం పాపం కాదు. కానీ సామర్థ్యం వచ్చిన తర్వాత అకారణంగా ఏళ్ళ తరబడి వాయిదా వేయడాన్ని పండితులు ఇష్టపడరు. ఆరోగ్యం, డబ్బు రెండూ ఉన్నప్పుడు వీలైనంత త్వరగా వెళ్ళడం ఉత్తమం.",
          en: "Hajj is not obligatory on someone without the means, and delaying in that situation is no sin. But scholars discourage postponing year after year without reason once the means are there. When both health and money are present, going sooner is better.",
        },
      },
    ],
    takeaways: [
      {
        te: "హజ్ జీవితకాలంలో ఒక్కసారి, సామర్థ్యం ఉన్నవారిపై మాత్రమే విధి.",
        en: "Hajj is obligatory once in a lifetime, and only on those with the means.",
      },
      {
        te: "సామర్థ్యం అంటే డబ్బు, ఆరోగ్యం, మార్గ భద్రత — మూడూ కలిసి.",
        en: "Ability means money, health and a safe route together, not just one of them.",
      },
      {
        te: "మహిళల ప్రయాణంపై మజ్‌హబ్‌ల మధ్య భేదం ఉంది; స్థానిక ఆలిమ్‌ను అడగండి.",
        en: "The schools differ on how a woman travels for Hajj; ask a local scholar.",
      },
    ],
    didYouKnow: [
      {
        te: "హజ్ ప్రతి సంవత్సరం సుమారు ఇరవై లక్షల మందిని ఒకే చోటికి చేరుస్తుంది — ప్రపంచంలోని అతిపెద్ద వార్షిక సమావేశాలలో ఒకటి.",
        en: "Hajj gathers around two million people in one place each year, one of the largest annual gatherings on earth.",
      },
      {
        te: "ఇహ్రామ్‌లో అందరూ ఒకే రకమైన సాధారణ వస్త్రాలు ధరిస్తారు — ధనవంతుడు, పేదవాడు కనిపించే తేడా ఉండదు.",
        en: "In ihram everyone wears the same plain cloth, so there is no visible difference between the wealthy and the poor.",
      },
    ],
    reflect: [
      {
        te: "మీరు ఈ రోజు హజ్‌కు వెళ్ళగలరా? లేకపోతే, ఏ అడ్డంకిని ముందుగా పరిష్కరించగలరు — డబ్బు, ఆరోగ్యం, లేదా ప్రణాళిక?",
        en: "Could you perform Hajj today? If not, which obstacle could you address first: money, health, or planning?",
      },
    ],
    mistakes: [
      {
        te: "సామర్థ్యం లేకున్నా అప్పు చేసి వెళ్ళడం — ఇది షరీఅత్ కోరేది కాదు.",
        en: "Going into debt to travel when the means are not there. The Shariah does not ask this of anyone.",
      },
      {
        te: "'తర్వాత చేద్దాం' అని ఆరోగ్యం, డబ్బు ఉన్నప్పటికీ ఏళ్ళ తరబడి వాయిదా వేయడం.",
        en: "Saying 'later' year after year while health and money are both available.",
      },
    ],
    faqs: [
      {
        question: {
          te: "ఒకరి తరపున మరొకరు హజ్ చేయవచ్చా?",
          en: "Can one person perform Hajj on behalf of another?",
        },
        answer: {
          te: "అవును — మరణించినవారి తరపున, లేదా కోలుకోలేని అనారోగ్యం, వృద్ధాప్యం వల్ల ఎప్పటికీ ప్రయాణించలేని వారి తరపున. దీన్ని హజ్-ఎ-బదల్ అంటారు. చేసేవారు ముందుగా తమ సొంత హజ్ పూర్తి చేసి ఉండాలి.",
          en: "Yes: on behalf of someone who has died, or someone whose illness or age means they will never be able to travel. This is called Hajj al-badal. The person performing it must have completed their own Hajj first.",
        },
      },
      {
        question: {
          te: "ఉమ్రహ్ చేస్తే హజ్ విధి తీరుతుందా?",
          en: "Does performing Umrah discharge the obligation of Hajj?",
        },
        answer: {
          te: "లేదు. ఉమ్రహ్ ఏ సమయంలోనైనా చేయగల వేరే ఆచారం. హజ్ జుల్-హిజ్జా నెలలో నిర్ణీత రోజుల్లోనే జరుగుతుంది, దాని స్థానంలో ఉమ్రహ్ రాదు.",
          en: "No. Umrah is a separate act that can be performed at any time of year. Hajj takes place on fixed days in Dhu al-Hijjah, and Umrah does not stand in its place.",
        },
      },
    ],
    quiz: [
      {
        question: {
          te: "హజ్ ఇస్లాంలో ఎన్నవ స్తంభం?",
          en: "Which pillar of Islam is Hajj?",
        },
        options: [
          { te: "ఐదవది", en: "The fifth" },
          { te: "మూడవది", en: "The third" },
          { te: "మొదటిది", en: "The first" },
        ],
        answer: 0,
      },
      {
        question: {
          te: "'సామర్థ్యం' లో కింది వాటిలో ఏది కలిసి ఉండదు?",
          en: "Which of these is NOT part of being 'able' to perform Hajj?",
        },
        options: [
          { te: "అరబిక్ భాష తెలిసి ఉండటం", en: "Knowing the Arabic language" },
          { te: "ప్రయాణ ఖర్చు భరించగలగడం", en: "Being able to afford the journey" },
          { te: "మార్గం సురక్షితంగా ఉండటం", en: "The route being safe" },
        ],
        answer: 0,
      },
      {
        question: {
          te: "హజ్-ఎ-బదల్ చేసేవారికి ఏ షరతు ఉంది?",
          en: "What condition applies to someone performing Hajj al-badal?",
        },
        options: [
          { te: "వారు ముందుగా తమ సొంత హజ్ చేసి ఉండాలి", en: "They must have completed their own Hajj first" },
          { te: "వారు మక్కాలో నివసించాలి", en: "They must live in Makkah" },
          { te: "వారు పండితుడై ఉండాలి", en: "They must be a scholar" },
        ],
        answer: 0,
      },
    ],
    revision: [
      { te: "ఖురాన్ 3:97 — 'చేరగల శక్తి ఉన్నవారిపై'.", en: "Quran 3:97 — 'those people who can afford the journey'." },
      { te: "సామర్థ్యం = డబ్బు + ఆరోగ్యం + భద్రత.", en: "Ability = money + health + safety." },
      { te: "హజ్-ఎ-బదల్: మరణించినవారి లేదా శాశ్వతంగా అశక్తుల తరపున.", en: "Hajj al-badal: on behalf of the deceased or the permanently unable." },
    ],
    summary: {
      te: "హజ్ సామర్థ్యం ఉన్నవారిపై జీవితకాలంలో ఒకసారి విధి. సామర్థ్యం అంటే అప్పు లేని ఖర్చు, ఆరోగ్యం, సురక్షిత మార్గం. లేనప్పుడు వాయిదా పాపం కాదు; ఉన్నప్పుడు ఆలస్యం మంచిది కాదు.",
      en: "Hajj is obligatory once in a lifetime for those with the means: the cost without debt, the health, and a safe route. Delaying without the means is no sin; delaying once you have them is not good.",
    },
    apply: {
      te: "ఆచరణ: మీ ప్రస్తుత పరిస్థితిని మూడు షరతులతో సరిపోల్చి రాసుకోండి — ఏది ఇప్పటికే ఉంది, ఏది లేదు.",
      en: "Apply it: write down your current situation against the three conditions, marking which you already meet and which you do not.",
    },
    reading: [
      { label: "Hajj & Umrah portal", url: "/knowledge-center/hajj-umrah" },
      { label: "Islamic calendar — Dhu al-Hijjah", url: "/knowledge-center/islamic-calendar" },
    ],
  },

  {
    slug: "ihram",
    portal: "hajj-umrah",
    title: {
      te: "స్థాయి 2 — ఇహ్రామ్ మరియు మీఖాత్",
      en: "Level 2 — Ihram and the Miqat",
    },
    intro: {
      te: "ఇహ్రామ్ కేవలం రెండు తెల్లని వస్త్రాలు కాదు — అది ఒక ఉద్దేశం, ఒక స్థితి. మీఖాత్ దాటే ముందు దానిలో ప్రవేశించాలి. ఈ పాఠం ఎక్కడ, ఎలా, ఏ నియమాలతో అని వివరిస్తుంది.",
      en: "Ihram is not simply two white cloths; it is an intention and a state you enter. You must be in it before crossing the miqat. This lesson covers where, how, and under what rules.",
    },
    sections: [
      {
        heading: { te: "ఇహ్రామ్ అంటే స్థితి, వస్త్రం కాదు", en: "Ihram is a state, not a garment" },
        body: {
          te: "ఇహ్రామ్ అంటే నియ్యత్ (ఉద్దేశం) చేసి, తల్బియా పలికి, కొన్ని అనుమతించబడిన పనులను తాత్కాలికంగా విడిచిపెట్టే స్థితి. పురుషులు కుట్టని రెండు వస్త్రాలు ధరిస్తారు; అది స్థితి యొక్క గుర్తు మాత్రమే, స్థితి కాదు. వస్త్రం ధరించినా నియ్యత్ లేకపోతే ఇహ్రామ్ లేదు.",
          en: "Ihram is the state you enter by making the intention, saying the talbiyah, and setting aside certain otherwise-permitted acts. Men wear two unstitched cloths, but that is the marker of the state, not the state itself. Wearing the cloth without the intention is not ihram.",
        },
        check: {
          question: {
            te: "ఇహ్రామ్‌లో ప్రవేశించడానికి అవసరమైనది ఏమిటి?",
            en: "What is required to enter the state of ihram?",
          },
          options: [
            { te: "నియ్యత్ (ఉద్దేశం)", en: "The intention (niyyah)" },
            { te: "కేవలం తెల్లని వస్త్రాలు", en: "Only the white cloths" },
            { te: "మక్కాలో ఉండటం", en: "Being inside Makkah" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "ఐదు మీఖాత్ స్థానాలు", en: "The five miqat points" },
        body: {
          te: "ప్రవక్త ﷺ దిక్కుల వారీగా ఐదు మీఖాత్‌లు నిర్ణయించారు: మదీనా వైపు నుండి జుల్-హులైఫా, షామ్ (సిరియా, ఈజిప్ట్) వైపు నుండి జుహ్‌ఫా, నజ్ద్ వైపు నుండి ఖర్న్ అల్-మనాజిల్, యెమెన్ వైపు నుండి యలమ్‌లమ్, ఇరాక్ వైపు నుండి జాతు ఇర్ఖ్. భారతదేశం నుండి వెళ్ళేవారు సాధారణంగా యలమ్‌లమ్ మీదుగా వెళతారు — విమానంలో దాన్ని దాటే ముందు ఇహ్రామ్ ధరించాలి.",
          en: "The Prophet ﷺ fixed five miqat points by direction of approach: Dhul-Hulayfah for those coming from Madinah, Juhfah from Syria and Egypt, Qarn al-Manazil from Najd, Yalamlam from Yemen, and Dhat Irq from Iraq. Pilgrims flying from India usually pass over Yalamlam, and must be in ihram before crossing it.",
        },
        check: {
          question: {
            te: "మీఖాత్ దాటే ముందు ఏమి చేయాలి?",
            en: "What must be done before crossing the miqat?",
          },
          options: [
            { te: "ఇహ్రామ్‌లో ప్రవేశించాలి", en: "Enter the state of ihram" },
            { te: "తవాఫ్ పూర్తి చేయాలి", en: "Complete the tawaf" },
            { te: "జంతువును అర్పించాలి", en: "Offer the sacrifice" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "ఇహ్రామ్‌లో ప్రవేశించే విధానం", en: "How to enter ihram" },
        body: {
          te: "స్నానం చేయడం (ఘుస్ల్) సున్నత్. పురుషులు కుట్టని రెండు వస్త్రాలు ధరిస్తారు; మహిళలు తమ సాధారణ శాలీన దుస్తులే ధరిస్తారు — ప్రత్యేక వస్త్రం లేదు. తర్వాత నియ్యత్ చేసి తల్బియా ప్రారంభిస్తారు: 'లబ్బైక్ అల్లాహుమ్మ లబ్బైక్' — 'ఓ అల్లాహ్, నేను హాజరయ్యాను, నీ పిలుపుకు సమాధానమిస్తున్నాను'.",
          en: "A ghusl beforehand is sunnah. Men wear two unstitched cloths; women wear their ordinary modest clothing, as there is no special garment for them. Then the intention is made and the talbiyah begins: 'Labbayk Allahumma labbayk' — 'Here I am, O Allah, here I am at Your service.'",
        },
      },
      {
        heading: { te: "ఇహ్రామ్‌లో నిషేధాలు", en: "What is set aside in ihram" },
        body: {
          te: "వేటాడటం, సువాసన వాడటం, జుట్టు లేదా గోళ్ళు కత్తిరించడం, భార్యాభర్తల సంబంధం, గొడవ లేదా వాదన — ఇవి ఇహ్రామ్‌లో నిషేధం. పురుషులు కుట్టిన దుస్తులు, తల కప్పడం మానేస్తారు. గమనించండి: స్నానం చేయడం, గొడుగు వాడటం, చెప్పులు వేసుకోవడం, మార్చుకోవడం — ఇవి అనుమతించబడినవి. చాలామంది వీటిని అనవసరంగా నిషేధమనుకుంటారు.",
          en: "Hunting, using perfume, cutting hair or nails, marital relations, and arguing or quarrelling are all set aside in ihram. Men additionally leave off stitched clothing and covering the head. Note what remains permitted: washing, using an umbrella for shade, wearing sandals, and changing your cloths. Many pilgrims wrongly believe these are forbidden.",
        },
      },
    ],
    takeaways: [
      { te: "ఇహ్రామ్ నియ్యత్‌తో మొదలవుతుంది; వస్త్రం దాని గుర్తు మాత్రమే.", en: "Ihram begins with the intention; the cloth is only its marker." },
      { te: "మీఖాత్ దాటే ముందు ఇహ్రామ్‌లో ఉండాలి — విమానంలో అయినా.", en: "You must be in ihram before crossing the miqat, including in the air." },
      { te: "మహిళలకు ప్రత్యేక ఇహ్రామ్ వస్త్రం లేదు; సాధారణ శాలీన దుస్తులే.", en: "There is no special ihram garment for women; ordinary modest dress is what is worn." },
    ],
    didYouKnow: [
      {
        te: "తల్బియా పలికిన వెంటనే హజ్ ప్రయాణం ఆధ్యాత్మికంగా మొదలవుతుంది — పండితులు దీన్ని పిలుపుకు ఇచ్చే సమాధానంగా వర్ణిస్తారు.",
        en: "The journey begins spiritually the moment the talbiyah is said; scholars describe it as answering a call that was made long ago.",
      },
      {
        te: "ఇహ్రామ్‌లో గొడుగు వాడటం అనుమతించబడింది — ఎండ నుండి కాపాడుకోవడం నిషేధం కాదు.",
        en: "Using an umbrella in ihram is permitted. Shading yourself from the sun is not among the prohibitions.",
      },
    ],
    reflect: [
      {
        te: "ఇహ్రామ్‌లో అందరూ ఒకేలా కనిపిస్తారు. హోదా, సంపద కనిపించకపోవడం మీ ప్రార్థనను ఎలా మారుస్తుంది?",
        en: "In ihram everyone looks alike. How would it change your worship if status and wealth were invisible?",
      },
    ],
    mistakes: [
      { te: "మీఖాత్ దాటిన తర్వాత ఇహ్రామ్ ధరించడం — దీనికి పరిహారం (దమ్) అవసరం కావచ్చు.", en: "Entering ihram after crossing the miqat, which may require a compensatory sacrifice (dam)." },
      { te: "సువాసన ఉన్న సబ్బు లేదా క్రీమ్ వాడటం — ఇహ్రామ్‌లో సువాసన నిషేధం.", en: "Using scented soap or cream, when perfume is among the things set aside." },
      { te: "మహిళలు ప్రత్యేక 'ఇహ్రామ్ దుస్తులు' కొనాలని అనుకోవడం.", en: "Believing women must buy special 'ihram clothing', when ordinary modest dress is what is worn." },
    ],
    faqs: [
      {
        question: { te: "విమానంలో మీఖాత్ ఎప్పుడు వస్తుందో ఎలా తెలుసుకోవాలి?", en: "How do I know when the miqat passes during a flight?" },
        answer: {
          te: "చాలా విమానయాన సంస్థలు మీఖాత్ సమీపిస్తున్నప్పుడు ప్రకటన చేస్తాయి. దాన్ని నమ్మి వేచి ఉండకుండా, విమానం ఎక్కే ముందే లేదా ఎక్కిన వెంటనే ఇహ్రామ్ ధరించడం సురక్షితం.",
          en: "Most airlines announce it as the miqat approaches. Rather than rely on that, it is safer to enter ihram before boarding or shortly after take-off.",
        },
      },
      {
        question: { te: "ఇహ్రామ్‌లో ఏదైనా నిషేధం మరచిపోయి చేస్తే?", en: "What if I break one of the prohibitions by mistake?" },
        answer: {
          te: "మరచిపోయి లేదా తెలియక చేసినదానికి సాధారణంగా పరిహారం లేదు — గుర్తు రాగానే ఆపేయాలి. ఉద్దేశపూర్వకంగా చేసినదానికి ఫిద్యా (ఉపవాసం, దానం, లేదా జంతు అర్పణ) ఉండవచ్చు. మీ కేసు కోసం అక్కడి మార్గదర్శకుడిని లేదా ఆలిమ్‌ను అడగండి.",
          en: "Something done forgetfully or in ignorance generally carries no penalty; stop as soon as you realise. Doing it deliberately may require a fidyah of fasting, feeding the poor, or a sacrifice. Ask a guide or scholar about your specific case.",
        },
      },
    ],
    quiz: [
      {
        question: { te: "భారతదేశం నుండి వచ్చేవారు సాధారణంగా ఏ మీఖాత్ మీదుగా వెళతారు?", en: "Which miqat do pilgrims from India usually pass?" },
        options: [
          { te: "యలమ్‌లమ్", en: "Yalamlam" },
          { te: "జుల్-హులైఫా", en: "Dhul-Hulayfah" },
          { te: "జాతు ఇర్ఖ్", en: "Dhat Irq" },
        ],
        answer: 0,
      },
      {
        question: { te: "కింది వాటిలో ఇహ్రామ్‌లో అనుమతించబడినది ఏది?", en: "Which of these is permitted while in ihram?" },
        options: [
          { te: "గొడుగుతో నీడ చేసుకోవడం", en: "Shading yourself with an umbrella" },
          { te: "సువాసన వాడటం", en: "Applying perfume" },
          { te: "గోళ్ళు కత్తిరించడం", en: "Cutting your nails" },
        ],
        answer: 0,
      },
      {
        question: { te: "మహిళలు ఇహ్రామ్‌లో ఏమి ధరిస్తారు?", en: "What do women wear in ihram?" },
        options: [
          { te: "వారి సాధారణ శాలీన దుస్తులు", en: "Their ordinary modest clothing" },
          { te: "రెండు కుట్టని తెల్లని వస్త్రాలు", en: "Two unstitched white cloths" },
          { te: "ప్రత్యేకంగా కొనే ఇహ్రామ్ దుస్తులు", en: "Specially purchased ihram clothing" },
        ],
        answer: 0,
      },
    ],
    revision: [
      { te: "ఇహ్రామ్ = నియ్యత్ + తల్బియా + నిషేధాలు.", en: "Ihram = intention + talbiyah + the things set aside." },
      { te: "ఐదు మీఖాత్: జుల్-హులైఫా, జుహ్‌ఫా, ఖర్న్ అల్-మనాజిల్, యలమ్‌లమ్, జాతు ఇర్ఖ్.", en: "Five miqat: Dhul-Hulayfah, Juhfah, Qarn al-Manazil, Yalamlam, Dhat Irq." },
      { te: "అనుమతి: స్నానం, గొడుగు, చెప్పులు. నిషేధం: సువాసన, జుట్టు, వాదన.", en: "Permitted: washing, umbrella, sandals. Set aside: perfume, cutting hair, arguing." },
    ],
    summary: {
      te: "ఇహ్రామ్ ఒక స్థితి — నియ్యత్‌తో మొదలై తల్బియాతో ప్రకటించబడుతుంది. మీఖాత్ దాటే ముందు దానిలో ప్రవేశించాలి. కొన్ని అనుమతించబడిన పనులు తాత్కాలికంగా వదిలిపెడతారు, కానీ చాలామంది అనుకునేంత కఠినం కాదు.",
      en: "Ihram is a state entered with the intention and announced with the talbiyah, and you must be in it before the miqat. Some otherwise-permitted acts are set aside, but fewer than most pilgrims assume.",
    },
    apply: {
      te: "ఆచరణ: తల్బియాను కంఠస్థం చేసి, దాని అర్థాన్ని మీ మాటల్లో రాయండి.",
      en: "Apply it: memorise the talbiyah and write out what it means in your own words.",
    },
    reading: [
      { label: "Hajj & Umrah portal", url: "/knowledge-center/hajj-umrah" },
      { label: "Why Hajj, and who it is due upon", url: "/knowledge-center/hajj-umrah/why-hajj" },
    ],
  },

  {
    slug: "types",
    portal: "hajj-umrah",
    title: {
      te: "స్థాయి 3 — హజ్ మూడు రకాలు",
      en: "Level 3 — The three types of Hajj",
    },
    intro: {
      te: "హజ్‌లో మూడు రకాలు ఉన్నాయి: ఇఫ్రాద్, ఖిరాన్, తమత్తుఅ. ఏది ఎంచుకుంటారో అది మీ ఇహ్రామ్ ఎప్పుడు ముగుస్తుందో, జంతు అర్పణ అవసరమా అనేదాన్ని నిర్ణయిస్తుంది. చాలామంది భారతీయ యాత్రికులు తమత్తుఅ చేస్తారు.",
      en: "Hajj comes in three forms: ifrad, qiran and tamattu. Which you choose decides when your ihram ends and whether a sacrifice is due. Most pilgrims from India perform tamattu.",
    },
    sections: [
      {
        heading: { te: "తమత్తుఅ — విడివిడిగా", en: "Tamattu — separated" },
        body: {
          te: "మొదట ఉమ్రహ్ కోసం ఇహ్రామ్ ధరించి, ఉమ్రహ్ పూర్తి చేసి, జుట్టు కత్తిరించి ఇహ్రామ్ నుండి బయటకు వస్తారు. తర్వాత జుల్-హిజ్జా 8న మక్కాలోనే మళ్ళీ హజ్ కోసం ఇహ్రామ్ ధరిస్తారు. మధ్యలో సాధారణ దుస్తులు ధరించవచ్చు. దీనికి జంతు అర్పణ (హద్య్) విధి.",
          en: "You first enter ihram for Umrah, complete it, cut your hair and leave ihram. Then on 8 Dhu al-Hijjah you enter ihram again for Hajj, from within Makkah. In between you wear ordinary clothes. A sacrifice (hady) is required for this form.",
        },
        check: {
          question: { te: "తమత్తుఅలో ఉమ్రహ్ తర్వాత ఏమి జరుగుతుంది?", en: "What happens after the Umrah in tamattu?" },
          options: [
            { te: "ఇహ్రామ్ నుండి బయటకు వస్తారు", en: "You leave the state of ihram" },
            { te: "ఇహ్రామ్‌లోనే కొనసాగుతారు", en: "You remain in ihram throughout" },
            { te: "వెంటనే అరఫాకు వెళతారు", en: "You go straight to Arafah" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "ఖిరాన్ — కలిపి", en: "Qiran — combined" },
        body: {
          te: "ఉమ్రహ్, హజ్ రెండింటి కోసం ఒకే ఇహ్రామ్‌లో నియ్యత్ చేస్తారు. ఉమ్రహ్ పూర్తయిన తర్వాత కూడా ఇహ్రామ్ నుండి బయటకు రారు — జుల్-హిజ్జా 10 వరకు అలాగే కొనసాగుతారు. దీనికి కూడా జంతు అర్పణ విధి. ఇహ్రామ్ ఎక్కువ కాలం ఉంటుంది కాబట్టి ఇది కష్టతరమైనది.",
          en: "You make the intention for both Umrah and Hajj in a single ihram. You do not leave ihram after the Umrah, but stay in it until 10 Dhu al-Hijjah. A sacrifice is also required. Because the ihram lasts far longer, this is the harder form.",
        },
      },
      {
        heading: { te: "ఇఫ్రాద్ — హజ్ ఒక్కటే", en: "Ifrad — Hajj alone" },
        body: {
          te: "హజ్ కోసం మాత్రమే ఇహ్రామ్ ధరిస్తారు; ఉమ్రహ్ కలపరు. దీనికి జంతు అర్పణ విధి కాదు. మక్కా నివాసులు, లేదా మీఖాత్ లోపల నివసించేవారు సాధారణంగా ఈ రూపాన్ని ఎంచుకుంటారు.",
          en: "You enter ihram for Hajj only, without combining an Umrah. No sacrifice is required for this form. Residents of Makkah, or those living inside the miqat boundary, generally choose it.",
        },
        check: {
          question: { te: "ఏ రూపానికి జంతు అర్పణ విధి కాదు?", en: "Which form does not require a sacrifice?" },
          options: [
            { te: "ఇఫ్రాద్", en: "Ifrad" },
            { te: "తమత్తుఅ", en: "Tamattu" },
            { te: "ఖిరాన్", en: "Qiran" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "మీరు ఏది ఎంచుకోవాలి", en: "Which one to choose" },
        body: {
          te: "భారతదేశం నుండి ముందుగా వెళ్ళి కొన్ని వారాలు ఉండేవారికి తమత్తుఅ సాధారణంగా సులభం — ఉమ్రహ్ పూర్తయ్యాక ఇహ్రామ్ నియమాల నుండి విశ్రాంతి దొరుకుతుంది. ప్రవక్త ﷺ వీడ్కోలు హజ్‌లో తన సహచరులకు తమత్తుఅ చేయమని ఆదేశించారు. మీ ప్రయాణ షెడ్యూల్‌ను బట్టి మీ గ్రూప్ మార్గదర్శకుడితో నిర్ణయించండి.",
          en: "For pilgrims travelling from India and staying some weeks, tamattu is usually easier: once the Umrah is done you are released from the restrictions for a time. On his farewell Hajj the Prophet ﷺ instructed his companions to perform tamattu. Decide with your group's guide based on your travel schedule.",
        },
      },
    ],
    takeaways: [
      { te: "తమత్తుఅ: ఉమ్రహ్, తర్వాత విడిగా హజ్. అర్పణ విధి.", en: "Tamattu: Umrah, then Hajj separately. Sacrifice required." },
      { te: "ఖిరాన్: రెండూ ఒకే ఇహ్రామ్‌లో. అర్పణ విధి.", en: "Qiran: both in one ihram. Sacrifice required." },
      { te: "ఇఫ్రాద్: హజ్ ఒక్కటే. అర్పణ విధి కాదు.", en: "Ifrad: Hajj alone. No sacrifice required." },
    ],
    didYouKnow: [
      {
        te: "వీడ్కోలు హజ్‌లో ప్రవక్త ﷺ స్వయంగా ఖిరాన్ చేశారు, కానీ తన సహచరులలో చాలామందికి తమత్తుఅ చేయమని చెప్పారు.",
        en: "On the farewell Hajj the Prophet ﷺ himself performed qiran, yet instructed many of his companions to perform tamattu.",
      },
    ],
    reflect: [
      {
        te: "మూడు రూపాలూ చెల్లుబాటు అవుతాయి. ఎంపిక ఉండటం షరీఅత్ సౌలభ్యాన్ని ఎలా చూపుతుంది?",
        en: "All three forms are valid. What does having a choice tell you about the ease built into the Shariah?",
      },
    ],
    mistakes: [
      { te: "తమత్తుఅ చేస్తూ, ఉమ్రహ్ తర్వాత జుట్టు కత్తిరించడం మరచిపోవడం — అప్పుడు ఇహ్రామ్ ముగియదు.", en: "Performing tamattu but forgetting to cut the hair after the Umrah, so the ihram never actually ends." },
      { te: "తమత్తుఅ లేదా ఖిరాన్ చేసి, అర్పణ (హద్య్) విధి అని తెలియకపోవడం.", en: "Performing tamattu or qiran without knowing that the sacrifice is obligatory." },
    ],
    faqs: [
      {
        question: { te: "అర్పణ చేయలేకపోతే ఏమిటి?", en: "What if I cannot afford the sacrifice?" },
        answer: {
          te: "ఖురాన్ దీనికి సమాధానం ఇచ్చింది: 'ఎవరికి సాధ్యం కాదో వారు హజ్‌లో మూడు రోజులు, ఇంటికి తిరిగి వచ్చాక ఏడు రోజులు — మొత్తం పది రోజులు ఉపవాసం ఉండాలి' (అల్-బఖరా 2:196).",
          en: "The Quran answers this directly: 'Whoever cannot afford it should fast three days during the pilgrimage and seven on his return, making ten days in all' (Al-Baqarah 2:196).",
        },
      },
      {
        question: { te: "ఒకసారి ఎంచుకున్న రూపాన్ని మార్చవచ్చా?", en: "Can I change the form once I have chosen it?" },
        answer: {
          te: "కొన్ని పరిస్థితుల్లో ఇఫ్రాద్ లేదా ఖిరాన్ నుండి తమత్తుఅకు మారవచ్చు, కానీ నియమాలు వివరమైనవి. అక్కడి మార్గదర్శకుడిని లేదా ఆలిమ్‌ను అడగకుండా సొంతంగా మార్చవద్దు.",
          en: "In some circumstances one may shift from ifrad or qiran to tamattu, but the rules are detailed. Do not change on your own without asking a guide or scholar there.",
        },
      },
    ],
    quiz: [
      {
        question: { te: "భారతీయ యాత్రికులు సాధారణంగా ఏ రూపం చేస్తారు?", en: "Which form do pilgrims from India usually perform?" },
        options: [
          { te: "తమత్తుఅ", en: "Tamattu" },
          { te: "ఇఫ్రాద్", en: "Ifrad" },
          { te: "ఖిరాన్", en: "Qiran" },
        ],
        answer: 0,
      },
      {
        question: { te: "ఖిరాన్‌లో ఇహ్రామ్ ఎప్పటివరకు కొనసాగుతుంది?", en: "In qiran, how long does the ihram last?" },
        options: [
          { te: "జుల్-హిజ్జా 10 వరకు", en: "Until 10 Dhu al-Hijjah" },
          { te: "ఉమ్రహ్ పూర్తయ్యేవరకు", en: "Until the Umrah is complete" },
          { te: "మీఖాత్ వరకు", en: "Until the miqat" },
        ],
        answer: 0,
      },
      {
        question: { te: "అర్పణ చేయలేనివారు ఎన్ని రోజులు ఉపవాసం ఉండాలి?", en: "How many days must someone fast who cannot afford the sacrifice?" },
        options: [
          { te: "పది — మూడు హజ్‌లో, ఏడు ఇంటికి వచ్చాక", en: "Ten: three during Hajj and seven after returning" },
          { te: "మూడు మాత్రమే", en: "Three only" },
          { te: "ముప్ఫై", en: "Thirty" },
        ],
        answer: 0,
      },
    ],
    revision: [
      { te: "తమత్తుఅ = ఉమ్రహ్ + విరామం + హజ్; అర్పణ విధి.", en: "Tamattu = Umrah + a break + Hajj; sacrifice due." },
      { te: "ఖిరాన్ = ఒకే ఇహ్రామ్‌లో రెండూ; అర్పణ విధి.", en: "Qiran = both in one ihram; sacrifice due." },
      { te: "ఇఫ్రాద్ = హజ్ ఒక్కటే; అర్పణ లేదు.", en: "Ifrad = Hajj alone; no sacrifice." },
      { te: "ఖురాన్ 2:196 — అర్పణ సాధ్యం కానప్పుడు పది రోజుల ఉపవాసం.", en: "Quran 2:196 — ten days of fasting when the sacrifice is beyond reach." },
    ],
    summary: {
      te: "మూడు రూపాలూ చెల్లుతాయి. తమత్తుఅ, ఖిరాన్‌లకు జంతు అర్పణ విధి; ఇఫ్రాద్‌కు కాదు. అర్పణ సాధ్యం కానప్పుడు పది రోజుల ఉపవాసం దాని స్థానంలో వస్తుంది.",
      en: "All three forms are valid. Tamattu and qiran require a sacrifice; ifrad does not. Where the sacrifice is beyond reach, ten days of fasting takes its place.",
    },
    apply: {
      te: "ఆచరణ: మీ ప్రయాణ తేదీలను చూసి, మీకు ఏ రూపం సరిపోతుందో ఎందుకో ఒక వాక్యంలో రాయండి.",
      en: "Apply it: look at your travel dates and write one sentence on which form suits you and why.",
    },
    reading: [
      { label: "Hajj & Umrah portal", url: "/knowledge-center/hajj-umrah" },
      { label: "Ihram and the Miqat", url: "/knowledge-center/hajj-umrah/ihram" },
    ],
  },

  {
    slug: "tawaf-sai",
    portal: "hajj-umrah",
    title: {
      te: "స్థాయి 4 — తవాఫ్ మరియు సఅయి",
      en: "Level 4 — Tawaf and Sa'i",
    },
    intro: {
      te: "తవాఫ్ కాబా చుట్టూ ఏడు ప్రదక్షిణలు; సఅయి సఫా-మర్వా మధ్య ఏడు నడకలు. ఈ రెండూ ఉమ్రహ్‌లోనూ హజ్‌లోనూ వస్తాయి. ఈ పాఠం వాటిని ఎలా చేయాలో, ఎక్కడ తప్పులు జరుగుతాయో చెబుతుంది.",
      en: "Tawaf is seven circuits around the Kaaba; sa'i is seven walks between Safa and Marwah. Both appear in Umrah and in Hajj. This lesson covers how each is performed and where pilgrims commonly go wrong.",
    },
    sections: [
      {
        heading: { te: "తవాఫ్ ఎలా చేయాలి", en: "How tawaf is performed" },
        body: {
          te: "హజర్ అల్-అస్వద్ (నల్లరాయి) వద్ద మొదలుపెట్టి, కాబాను మీ ఎడమవైపు ఉంచుకుని అపసవ్య దిశలో ఏడు ప్రదక్షిణలు చేస్తారు. ప్రతి ప్రదక్షిణ ప్రారంభంలో రాయి వైపు చేయి ఎత్తి 'బిస్మిల్లాహి అల్లాహు అక్బర్' అంటారు. రాయిని ముద్దు పెట్టుకోవడం సున్నత్ — కానీ రద్దీలో దగ్గరకు వెళ్ళడానికి ఎవరినీ నెట్టకూడదు. దూరం నుండి సైగ చేస్తే సరిపోతుంది.",
          en: "You begin at the Hajar al-Aswad, keep the Kaaba on your left, and make seven circuits anti-clockwise. At the start of each circuit you raise your hand towards the stone and say 'Bismillahi Allahu akbar'. Kissing the stone is sunnah, but no one should push through a crowd to reach it; gesturing from a distance is enough.",
        },
        check: {
          question: { te: "తవాఫ్‌లో కాబా ఏ వైపు ఉండాలి?", en: "During tawaf, which side is the Kaaba on?" },
          options: [
            { te: "ఎడమవైపు", en: "On your left" },
            { te: "కుడివైపు", en: "On your right" },
            { te: "వెనుక", en: "Behind you" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "తవాఫ్‌కు షరతులు", en: "Conditions for tawaf" },
        body: {
          te: "తవాఫ్ ప్రార్థన లాంటిది — వుజూ అవసరం అని మెజారిటీ పండితుల అభిప్రాయం. ఏడు ప్రదక్షిణలూ పూర్తి చేయాలి; సందేహం వస్తే తక్కువ సంఖ్యను తీసుకుని మిగిలినది పూర్తి చేయాలి. హతీమ్ (కాబా పక్కన అర్ధవృత్తాకార గోడ) కాబాలో భాగం — దాని లోపలి నుండి కాదు, బయటి నుండి ప్రదక్షిణ చేయాలి.",
          en: "Tawaf is treated like prayer, and the majority of scholars require wudu for it. All seven circuits must be completed; if you lose count, take the lower number and make up the rest. The Hateem, the low semicircular wall beside the Kaaba, is part of the Kaaba, so you must walk outside it rather than cut through.",
        },
        check: {
          question: { te: "హతీమ్ గురించి ఏది సరైనది?", en: "Which is correct about the Hateem?" },
          options: [
            { te: "అది కాబాలో భాగం — బయటి నుండి ప్రదక్షిణ చేయాలి", en: "It is part of the Kaaba, so walk outside it" },
            { te: "దాని లోపలి నుండి వెళ్ళవచ్చు", en: "You may cut through the inside of it" },
            { te: "అది తవాఫ్‌కు సంబంధించినది కాదు", en: "It has nothing to do with tawaf" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "సఅయి — సఫా నుండి మర్వా", en: "Sa'i — from Safa to Marwah" },
        body: {
          te: "తవాఫ్ తర్వాత సఫా కొండ వద్ద మొదలుపెట్టి మర్వా వరకు నడుస్తారు — అది ఒకటి. మర్వా నుండి సఫాకు తిరిగి రావడం రెండు. ఇలా ఏడు — సఫాలో మొదలై మర్వాలో ముగుస్తుంది. పురుషులు ఆకుపచ్చ గుర్తుల మధ్య కొంచెం వేగంగా నడుస్తారు; మహిళలు సాధారణ వేగంతోనే నడుస్తారు.",
          en: "After tawaf you begin at Safa and walk to Marwah, and that is one. Marwah back to Safa is two. Seven in all, beginning at Safa and ending at Marwah. Men walk briskly between the two green markers; women walk at their normal pace.",
        },
      },
      {
        heading: { te: "సఅయి వెనుక కథ", en: "The story behind sa'i" },
        body: {
          te: "ఇది హాజర్ (ర/అ) జ్ఞాపకం. ఎడారిలో శిశువు ఇస్మాయీల్‌తో ఒంటరిగా మిగిలిపోయినప్పుడు, ఆమె నీటి కోసం ఈ రెండు కొండల మధ్య ఏడుసార్లు పరుగెత్తారు. జమ్‌జమ్ ఊట పుట్టింది. ప్రతి సంవత్సరం లక్షలాది మంది ఒక తల్లి నిస్సహాయ పరుగును పునరావృతం చేస్తారు — ప్రయత్నం, తవక్కుల్ రెండూ కలిసిన పాఠం.",
          en: "It commemorates Hajar (RA). Left alone in the desert with the infant Ismail, she ran seven times between these two hills looking for water, and the spring of Zamzam appeared. Every year millions retrace one mother's desperate search: a lesson in effort and reliance on Allah held together.",
        },
      },
    ],
    takeaways: [
      { te: "తవాఫ్: ఏడు ప్రదక్షిణలు, కాబా ఎడమవైపు, హజర్ అల్-అస్వద్ వద్ద మొదలు.", en: "Tawaf: seven circuits, Kaaba on your left, beginning at the Hajar al-Aswad." },
      { te: "సఅయి: సఫాలో మొదలై మర్వాలో ముగిసే ఏడు నడకలు.", en: "Sa'i: seven walks, beginning at Safa and ending at Marwah." },
      { te: "రాయిని ముద్దుపెట్టడం కోసం ఎవరినీ నెట్టవద్దు — సైగ సరిపోతుంది.", en: "Never push anyone to reach the stone; a gesture from a distance suffices." },
    ],
    didYouKnow: [
      { te: "జమ్‌జమ్ ఊట సుమారు నాలుగు వేల సంవత్సరాలుగా ప్రవహిస్తూనే ఉంది.", en: "The spring of Zamzam has been flowing for roughly four thousand years." },
      { te: "సఅయి ఏడు నడకలు సుమారు మూడున్నర కిలోమీటర్లు అవుతాయి.", en: "The seven walks of sa'i come to roughly three and a half kilometres." },
    ],
    reflect: [
      { te: "హాజర్ (ర/అ) పరుగెత్తారు, కానీ నీరు ఆమె పరుగు వల్ల రాలేదు — అల్లాహ్ ఇచ్చాడు. ప్రయత్నం, భరోసా మీ జీవితంలో ఎలా కలుస్తాయి?", en: "Hajar (RA) ran, yet the water did not come from her running; Allah gave it. How do effort and trust meet in your own life?" },
    ],
    mistakes: [
      { te: "నల్లరాయి దగ్గరకు వెళ్ళడానికి జనాన్ని నెట్టడం — ఇది సున్నత్ కోసం ఒక విధిని (ఇతరులకు హాని చేయకపోవడం) ఉల్లంఘించడం.", en: "Shoving through the crowd to reach the black stone, breaking an obligation (not harming others) for the sake of a sunnah." },
      { te: "సఅయిని మర్వాలో మొదలుపెట్టడం — అది సఫాలోనే మొదలవ్వాలి.", en: "Starting sa'i at Marwah when it must begin at Safa." },
      { te: "హతీమ్ లోపలి నుండి వెళ్ళి ప్రదక్షిణను చెల్లనిదిగా చేయడం.", en: "Cutting through the Hateem, which invalidates that circuit." },
    ],
    faqs: [
      {
        question: { te: "తవాఫ్ మధ్యలో వుజూ పోతే?", en: "What if my wudu breaks during tawaf?" },
        answer: {
          te: "మెజారిటీ అభిప్రాయం ప్రకారం వుజూ చేసుకుని వచ్చి, ఎక్కడ ఆగారో అక్కడి నుండి కొనసాగించాలి — మొదటి నుండి కాదు. హనఫీ మజ్‌హబ్‌లో వుజూ లేకుండా చేసిన తవాఫ్ చెల్లుతుంది కానీ పరిహారం ఉంటుంది.",
          en: "In the majority view you renew your wudu and continue from where you stopped rather than starting over. In the Hanafi school a tawaf performed without wudu is valid but carries a penalty.",
        },
      },
      {
        question: { te: "వీల్‌చైర్‌లో తవాఫ్, సఅయి చేయవచ్చా?", en: "Can tawaf and sa'i be done in a wheelchair?" },
        answer: {
          te: "అవును. వృద్ధులు, అనారోగ్యులు, నడవలేనివారు వీల్‌చైర్ ఉపయోగించవచ్చు — ఇది పూర్తిగా అనుమతించబడింది, ఆచారం చెల్లుతుంది. మస్జిద్ అల్-హరామ్‌లో దీనికి ప్రత్యేక మార్గాలు ఉన్నాయి.",
          en: "Yes. The elderly, the ill and those who cannot walk may use a wheelchair; this is fully permitted and the rite is valid. The Masjid al-Haram has dedicated levels for it.",
        },
      },
    ],
    quiz: [
      {
        question: { te: "తవాఫ్ ఎక్కడ మొదలవుతుంది?", en: "Where does tawaf begin?" },
        options: [
          { te: "హజర్ అల్-అస్వద్ వద్ద", en: "At the Hajar al-Aswad" },
          { te: "మఖామ్ ఇబ్రాహీమ్ వద్ద", en: "At the Maqam Ibrahim" },
          { te: "సఫా వద్ద", en: "At Safa" },
        ],
        answer: 0,
      },
      {
        question: { te: "సఅయి ఎక్కడ ముగుస్తుంది?", en: "Where does sa'i end?" },
        options: [
          { te: "మర్వా వద్ద", en: "At Marwah" },
          { te: "సఫా వద్ద", en: "At Safa" },
          { te: "కాబా వద్ద", en: "At the Kaaba" },
        ],
        answer: 0,
      },
      {
        question: { te: "సఅయి దేని జ్ఞాపకం?", en: "What does sa'i commemorate?" },
        options: [
          { te: "హాజర్ (ర/అ) నీటి కోసం పరుగు", en: "Hajar's (RA) search for water" },
          { te: "బద్ర్ యుద్ధం", en: "The battle of Badr" },
          { te: "హిజ్రత్", en: "The Hijrah" },
        ],
        answer: 0,
      },
    ],
    revision: [
      { te: "తవాఫ్ 7 ప్రదక్షిణలు, కాబా ఎడమవైపు, హతీమ్ బయటి నుండి.", en: "Tawaf: 7 circuits, Kaaba on the left, outside the Hateem." },
      { te: "సఅయి 7 నడకలు: సఫా → మర్వా = 1.", en: "Sa'i: 7 walks; Safa to Marwah counts as one." },
      { te: "వీల్‌చైర్ అనుమతించబడింది; ఆచారం చెల్లుతుంది.", en: "A wheelchair is permitted and the rite remains valid." },
    ],
    summary: {
      te: "తవాఫ్ ఏడు ప్రదక్షిణలు, హజర్ అల్-అస్వద్ వద్ద మొదలై కాబాను ఎడమవైపు ఉంచుకుని. సఅయి ఏడు నడకలు, సఫాలో మొదలై మర్వాలో ముగుస్తుంది — హాజర్ (ర/అ) పరుగుకు జ్ఞాపకం.",
      en: "Tawaf is seven circuits from the Hajar al-Aswad with the Kaaba on your left. Sa'i is seven walks from Safa to Marwah, retracing Hajar's (RA) search for water.",
    },
    apply: {
      te: "ఆచరణ: తవాఫ్ ఏడు ప్రదక్షిణలను లెక్కపెట్టే ఒక సులభ పద్ధతిని ముందుగా నిర్ణయించుకోండి — వేళ్ళు, ఉంగరం, లేదా టాలీ.",
      en: "Apply it: decide in advance on a simple way to keep count of the seven circuits, whether fingers, a ring, or a tally.",
    },
    reading: [
      { label: "Hajj & Umrah portal", url: "/knowledge-center/hajj-umrah" },
      { label: "The three types of Hajj", url: "/knowledge-center/hajj-umrah/types" },
    ],
  },

  {
    slug: "days-of-hajj",
    portal: "hajj-umrah",
    title: {
      te: "స్థాయి 5 — హజ్ ఐదు రోజులు",
      en: "Level 5 — The five days of Hajj",
    },
    intro: {
      te: "జుల్-హిజ్జా 8 నుండి 12 (లేదా 13) వరకు — మినా, అరఫా, ముజ్దలిఫా, జమారాత్. ఈ పాఠం ప్రతి రోజు ఏమి జరుగుతుందో వరుసగా చెబుతుంది.",
      en: "From 8 to 12 (or 13) Dhu al-Hijjah: Mina, Arafah, Muzdalifah and the Jamarat. This lesson walks through what happens on each day, in order.",
    },
    sections: [
      {
        heading: { te: "8వ రోజు — మినా", en: "Day 8 — Mina" },
        body: {
          te: "యౌమ్ అత్-తర్వియా. హజ్ కోసం ఇహ్రామ్ ధరించి మినాకు వెళతారు. అక్కడ జుహ్ర్, అస్ర్, మఘ్రిబ్, ఇషా, మరుసటి రోజు ఫజ్ర్ — ఐదు నమాజులు చదువుతారు. నాలుగు రక్అత్ నమాజులను రెండుగా కుదిస్తారు (ఖస్ర్), కానీ కలిపి చదవరు. ఈ రోజు ఎక్కువగా విశ్రాంతి, దుఆ.",
          en: "Yawm at-Tarwiyah. You enter ihram for Hajj and go to Mina, praying five prayers there: Zuhr, Asr, Maghrib, Isha, and the next morning's Fajr. Four-unit prayers are shortened to two (qasr) but not combined. The day is largely rest and supplication.",
        },
      },
      {
        heading: { te: "9వ రోజు — అరఫా", en: "Day 9 — Arafah" },
        body: {
          te: "ఇదే హజ్. ప్రవక్త ﷺ అన్నారు: 'హజ్ అంటే అరఫా.' సూర్యుడు నడినెత్తిన దాటిన తర్వాత సూర్యాస్తమయం వరకు అరఫాత్ మైదానంలో నిలబడతారు. జుహ్ర్, అస్ర్ కలిపి కుదించి చదువుతారు. మిగిలిన సమయమంతా దుఆ — నిలబడి, చేతులు ఎత్తి. ఎవరైనా అరఫాలో నిలబడటం తప్పితే వారి హజ్ చెల్లదు.",
          en: "This is the Hajj. The Prophet ﷺ said: 'Hajj is Arafah.' From just after midday until sunset you stand on the plain of Arafat. Zuhr and Asr are combined and shortened, and the rest of the day is supplication, standing with hands raised. Anyone who misses the standing at Arafah has not performed Hajj.",
        },
        check: {
          question: { te: "ఏ ఆచారం తప్పితే హజ్ చెల్లదు?", en: "Missing which rite means the Hajj is not valid?" },
          options: [
            { te: "అరఫాలో నిలబడటం", en: "Standing at Arafah" },
            { te: "మినాలో ఉండటం", en: "Staying at Mina" },
            { te: "వీడ్కోలు తవాఫ్", en: "The farewell tawaf" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "9వ రాత్రి — ముజ్దలిఫా", en: "Night of the 9th — Muzdalifah" },
        body: {
          te: "సూర్యాస్తమయం తర్వాత అరఫా నుండి ముజ్దలిఫాకు బయలుదేరతారు — అక్కడే మఘ్రిబ్, ఇషా కలిపి చదువుతారు. రాత్రి ఆరుబయట గడుపుతారు, జమారాత్ కోసం రాళ్ళు ఏరుకుంటారు. బలహీనులు, మహిళలు, వృద్ధులు అర్ధరాత్రి తర్వాత మినాకు ముందుగా వెళ్ళవచ్చు — ప్రవక్త ﷺ దీనికి అనుమతి ఇచ్చారు.",
          en: "After sunset you leave Arafah for Muzdalifah, where Maghrib and Isha are prayed together on arrival. You spend the night in the open and gather pebbles for the Jamarat. The weak, women and the elderly may leave for Mina after midnight; the Prophet ﷺ granted this concession.",
        },
      },
      {
        heading: { te: "10వ రోజు — రమీ, అర్పణ, జుట్టు, తవాఫ్", en: "Day 10 — stoning, sacrifice, hair, tawaf" },
        body: {
          te: "ఈదుల్ అద్హా. నాలుగు పనులు: జమరత్ అల్-అఖబాను ఏడు రాళ్ళతో కొట్టడం, జంతు అర్పణ, జుట్టు గొరిగించడం లేదా కత్తిరించడం, తవాఫ్ అల్-ఇఫాదా. మొదటి మూడింటిలో ఏవైనా రెండు పూర్తయ్యాక ఇహ్రామ్ నుండి పాక్షికంగా బయటకు వస్తారు (భార్యాభర్తల సంబంధం తప్ప అన్నీ అనుమతి). నాలుగూ పూర్తయ్యాక పూర్తిగా.",
          en: "Eid al-Adha. Four acts: stoning the Jamrat al-Aqabah with seven pebbles, the sacrifice, shaving or cutting the hair, and the tawaf al-ifadah. After any two of the first three you leave ihram partially, with everything permitted again except marital relations. After all four, you leave it completely.",
        },
        check: {
          question: { te: "10వ రోజు జమరత్ అల్-అఖబాకు ఎన్ని రాళ్ళు?", en: "How many pebbles are thrown at Jamrat al-Aqabah on day 10?" },
          options: [
            { te: "ఏడు", en: "Seven" },
            { te: "ఇరవై ఒకటి", en: "Twenty-one" },
            { te: "మూడు", en: "Three" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "11–13 రోజులు — తష్రీఖ్", en: "Days 11-13 — the days of Tashreeq" },
        body: {
          te: "మినాలో ఉండి ప్రతిరోజూ మూడు జమారాత్‌లను ఏడేసి రాళ్ళతో కొడతారు — చిన్నది, మధ్యది, పెద్దది ఈ వరుసలో. 12వ రోజు సూర్యాస్తమయానికి ముందు బయలుదేరితే సరిపోతుంది (నఫర్ అవ్వల్); ఆగితే 13వ రోజు కూడా రమీ చేయాలి. చివరగా, మక్కా వదిలే ముందు తవాఫ్ అల్-విదా — వీడ్కోలు ప్రదక్షిణ.",
          en: "You stay at Mina and stone all three Jamarat each day with seven pebbles each, in order: small, middle, large. Leaving before sunset on the 12th is sufficient (nafar awwal); staying means stoning on the 13th too. Finally, before leaving Makkah, comes the tawaf al-wida, the farewell circuit.",
        },
      },
    ],
    takeaways: [
      { te: "'హజ్ అంటే అరఫా' — 9వ రోజు నిలబడటం తప్పితే హజ్ లేదు.", en: "'Hajj is Arafah.' Miss the standing on day 9 and there is no Hajj." },
      { te: "10వ రోజు నాలుగు పనులు: రమీ, అర్పణ, జుట్టు, తవాఫ్ అల్-ఇఫాదా.", en: "Day 10 has four acts: stoning, sacrifice, hair, and tawaf al-ifadah." },
      { te: "బలహీనులు ముజ్దలిఫా నుండి అర్ధరాత్రి తర్వాత ముందుగా వెళ్ళవచ్చు.", en: "The weak may leave Muzdalifah after midnight." },
    ],
    didYouKnow: [
      { te: "అరఫా రోజు ఉపవాసం — యాత్రికులు కానివారికి — రెండు సంవత్సరాల పాపాలకు పరిహారమని ప్రవక్త ﷺ చెప్పారు (ముస్లిం).", en: "The Prophet ﷺ said fasting the day of Arafah, for those not on Hajj, expiates two years of sins (Muslim)." },
      { te: "అరఫాలో నిలబడటానికి మస్జిద్ అవసరం లేదు — మైదానంలో ఎక్కడైనా సరిపోతుంది.", en: "The standing at Arafah needs no mosque; anywhere on the plain counts." },
    ],
    reflect: [
      { te: "అరఫా రోజు మధ్యాహ్నం నుండి సాయంత్రం వరకు మీరు ఏమి అడుగుతారు? ఇప్పుడే మూడు దుఆలు రాసుకోండి.", en: "What will you ask for from midday to sunset on Arafah? Write down three supplications now." },
    ],
    mistakes: [
      { te: "సూర్యాస్తమయానికి ముందే అరఫా వదిలివేయడం — నిలబడటం సూర్యాస్తమయం వరకు ఉండాలి.", en: "Leaving Arafah before sunset, when the standing must last until then." },
      { te: "జమారాత్ వద్ద రద్దీ సమయంలో నెట్టుకుంటూ వెళ్ళడం — ఆలస్యంగా వెళ్ళడం సురక్షితం, అనుమతించబడింది.", en: "Forcing through the crush at the Jamarat, when going at a quieter hour is safer and permitted." },
      { te: "రాళ్ళను స్తంభంపైకి కోపంగా విసరడం — ఇది జికర్‌తో చేసే ఆచారం, ఆగ్రహ ప్రదర్శన కాదు.", en: "Hurling stones at the pillar in anger. It is a rite performed with dhikr, not a display of rage." },
    ],
    faqs: [
      {
        question: { te: "రద్దీ వల్ల నిర్ణీత సమయంలో రమీ చేయలేకపోతే?", en: "What if crowds prevent me stoning at the prescribed time?" },
        answer: {
          te: "రమీ సమయం విస్తృతమైనది — చాలామంది పండితులు రాత్రి వరకు అనుమతిస్తారు. భద్రత కోసం ఆలస్యంగా వెళ్ళడం సరైనది. ప్రాణానికి ప్రమాదం కలిగించే రద్దీలోకి వెళ్ళాల్సిన అవసరం లేదు.",
          en: "The window for stoning is wide, and many scholars permit it through the night. Going later for safety is the correct choice; no one is required to enter a crush that endangers life.",
        },
      },
      {
        question: { te: "ఎవరైనా తరపున రమీ చేయవచ్చా?", en: "Can someone stone on another's behalf?" },
        answer: {
          te: "అవును — అనారోగ్యం, వృద్ధాప్యం, లేదా చిన్నపిల్లల విషయంలో మరొకరు వారి తరపున రాళ్ళు వేయవచ్చు. చేసేవారు ముందుగా తమ సొంత రమీ పూర్తి చేయాలి.",
          en: "Yes. For the ill, the elderly, or young children, another person may stone on their behalf, having first completed their own.",
        },
      },
    ],
    quiz: [
      {
        question: { te: "అరఫాలో నిలబడటం ఎప్పటివరకు?", en: "The standing at Arafah lasts until when?" },
        options: [
          { te: "సూర్యాస్తమయం వరకు", en: "Until sunset" },
          { te: "అస్ర్ వరకు", en: "Until Asr" },
          { te: "మధ్యాహ్నం వరకు", en: "Until midday" },
        ],
        answer: 0,
      },
      {
        question: { te: "ముజ్దలిఫాలో ఏ నమాజులు కలిపి చదువుతారు?", en: "Which prayers are combined at Muzdalifah?" },
        options: [
          { te: "మఘ్రిబ్ మరియు ఇషా", en: "Maghrib and Isha" },
          { te: "జుహ్ర్ మరియు అస్ర్", en: "Zuhr and Asr" },
          { te: "ఫజ్ర్ మరియు జుహ్ర్", en: "Fajr and Zuhr" },
        ],
        answer: 0,
      },
      {
        question: { te: "తష్రీఖ్ రోజుల్లో ప్రతిరోజూ ఎన్ని జమారాత్‌లను కొడతారు?", en: "How many Jamarat are stoned each day of Tashreeq?" },
        options: [
          { te: "మూడు — చిన్నది, మధ్యది, పెద్దది", en: "Three: small, middle, large" },
          { te: "ఒకటి మాత్రమే", en: "Only one" },
          { te: "ఏడు", en: "Seven" },
        ],
        answer: 0,
      },
    ],
    revision: [
      { te: "8 మినా → 9 అరఫా → 9 రాత్రి ముజ్దలిఫా → 10 రమీ/అర్పణ/జుట్టు/తవాఫ్ → 11-13 మినా.", en: "8 Mina, 9 Arafah, night of 9 Muzdalifah, 10 stoning/sacrifice/hair/tawaf, 11-13 Mina." },
      { te: "అరఫా తప్పితే హజ్ లేదు.", en: "Miss Arafah and there is no Hajj." },
      { te: "12వ రోజు సూర్యాస్తమయానికి ముందు వెళ్ళవచ్చు (నఫర్ అవ్వల్).", en: "You may leave before sunset on the 12th (nafar awwal)." },
    ],
    summary: {
      te: "హజ్ ఐదు రోజులు మినాతో మొదలై, అరఫాలో గరిష్ఠస్థాయికి చేరి, ముజ్దలిఫా రాత్రి తర్వాత ఈద్ రోజు నాలుగు పనులతో కొనసాగి, తష్రీఖ్ రోజుల రమీతో ముగుస్తుంది.",
      en: "The five days begin at Mina, peak at Arafah, pass through the night at Muzdalifah, continue with the four acts of Eid day, and close with the stoning of the Tashreeq days.",
    },
    apply: {
      te: "ఆచరణ: ఐదు రోజుల వరుసను చూడకుండా రాయగలిగే వరకు సాధన చేయండి.",
      en: "Apply it: practise writing out the order of the five days until you can do it without looking.",
    },
    reading: [
      { label: "Hajj & Umrah portal", url: "/knowledge-center/hajj-umrah" },
      { label: "Tawaf and Sa'i", url: "/knowledge-center/hajj-umrah/tawaf-sai" },
    ],
  },

  {
    slug: "umrah",
    portal: "hajj-umrah",
    title: {
      te: "స్థాయి 6 — ఉమ్రహ్ దశలవారీగా",
      en: "Level 6 — Umrah step by step",
    },
    intro: {
      te: "ఉమ్రహ్ నాలుగు దశలు మాత్రమే, సంవత్సరంలో ఎప్పుడైనా చేయవచ్చు. హజ్ కంటే చాలా చిన్నది, కానీ అదే ఇహ్రామ్ నియమాలు వర్తిస్తాయి.",
      en: "Umrah is only four steps and can be performed at any time of year. It is far shorter than Hajj, but the same rules of ihram apply.",
    },
    sections: [
      {
        heading: { te: "నాలుగు దశలు", en: "The four steps" },
        body: {
          te: "ఒకటి: మీఖాత్ వద్ద ఇహ్రామ్, నియ్యత్, తల్బియా. రెండు: కాబా చుట్టూ ఏడు ప్రదక్షిణలు (తవాఫ్). మూడు: సఫా-మర్వా మధ్య ఏడు నడకలు (సఅయి). నాలుగు: జుట్టు గొరిగించడం లేదా కత్తిరించడం (హలఖ్ లేదా తఖ్సీర్). అంతే — ఇహ్రామ్ ముగుస్తుంది.",
          en: "One: ihram at the miqat with the intention and the talbiyah. Two: seven circuits of the Kaaba (tawaf). Three: seven walks between Safa and Marwah (sa'i). Four: shaving or cutting the hair (halq or taqsir). That is all, and the ihram ends.",
        },
        check: {
          question: { te: "ఉమ్రహ్ చివరి దశ ఏది?", en: "What is the final step of Umrah?" },
          options: [
            { te: "జుట్టు గొరిగించడం లేదా కత్తిరించడం", en: "Shaving or cutting the hair" },
            { te: "అరఫాలో నిలబడటం", en: "Standing at Arafah" },
            { te: "జమారాత్ రమీ", en: "Stoning the Jamarat" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "జుట్టు — పురుషులు, మహిళలు", en: "The hair, for men and women" },
        body: {
          te: "పురుషులు తల పూర్తిగా గొరిగించడం (హలఖ్) ఉత్తమం; కత్తిరించడం (తఖ్సీర్) కూడా చెల్లుతుంది. ప్రవక్త ﷺ గొరిగించినవారి కోసం మూడుసార్లు దుఆ చేసి, కత్తిరించినవారి కోసం ఒకసారి చేశారు. మహిళలు తల గొరిగించరు — జుట్టు కొన నుండి ఒక వేలి పొడవు (సుమారు 2.5 సెం.మీ) కత్తిరిస్తారు, అంతే.",
          en: "For men, shaving the head (halq) is better, though cutting (taqsir) is also valid; the Prophet ﷺ prayed three times for those who shaved and once for those who cut. Women do not shave. They cut about a fingertip's length, roughly two and a half centimetres, from the ends, and that is all.",
        },
        check: {
          question: { te: "మహిళలు ఉమ్రహ్ చివర ఏమి చేస్తారు?", en: "What do women do at the end of Umrah?" },
          options: [
            { te: "జుట్టు కొన నుండి ఒక వేలి పొడవు కత్తిరిస్తారు", en: "Cut about a fingertip's length from the ends" },
            { te: "తల పూర్తిగా గొరిగించుకుంటారు", en: "Shave the head completely" },
            { te: "ఏమీ చేయరు", en: "Nothing at all" },
          ],
          answer: 0,
        },
      },
      {
        heading: { te: "ఎప్పుడు చేయవచ్చు", en: "When it can be performed" },
        body: {
          te: "ఉమ్రహ్‌కు నిర్ణీత సమయం లేదు — సంవత్సరంలో ఏ రోజైనా చేయవచ్చు. రమజాన్‌లో చేసే ఉమ్రహ్ గురించి ప్రవక్త ﷺ ప్రత్యేకంగా చెప్పారు; అందుకే ఆ నెలలో రద్దీ ఎక్కువ. హజ్ రోజుల్లో (జుల్-హిజ్జా 9-13) మాత్రం ఉమ్రహ్ చేయరు.",
          en: "Umrah has no fixed time and may be performed on any day of the year. The Prophet ﷺ spoke particularly of Umrah in Ramadan, which is why that month is the busiest. It is not performed during the days of Hajj itself, 9 to 13 Dhu al-Hijjah.",
        },
      },
      {
        heading: { te: "ఉమ్రహ్‌లో లేనివి", en: "What Umrah does not include" },
        body: {
          te: "గందరగోళం తగ్గించడానికి: ఉమ్రహ్‌లో అరఫా లేదు, ముజ్దలిఫా లేదు, మినా లేదు, జమారాత్ రమీ లేదు, జంతు అర్పణ విధి కాదు. ఇవన్నీ హజ్‌కు మాత్రమే. ఉమ్రహ్ ఒక్క రోజులో — కొన్ని గంటల్లోనే — పూర్తవుతుంది.",
          en: "To remove a common confusion: Umrah has no Arafah, no Muzdalifah, no Mina, no stoning, and no obligatory sacrifice. Those belong to Hajj alone. Umrah is completed in a single day, often within a few hours.",
        },
      },
    ],
    takeaways: [
      { te: "ఉమ్రహ్ = ఇహ్రామ్ + తవాఫ్ + సఅయి + జుట్టు. నాలుగే దశలు.", en: "Umrah = ihram + tawaf + sa'i + hair. Four steps only." },
      { te: "సంవత్సరంలో ఎప్పుడైనా చేయవచ్చు; హజ్ రోజుల్లో తప్ప.", en: "It may be performed any time of year, except during the days of Hajj." },
      { te: "మహిళలు తల గొరిగించరు — కొన నుండి కొంచెం కత్తిరిస్తారు.", en: "Women do not shave; they trim a small length from the ends." },
    ],
    didYouKnow: [
      { te: "ఉమ్రహ్‌ను 'చిన్న హజ్' అని పిలుస్తారు, కానీ అది హజ్ విధిని తీర్చదు.", en: "Umrah is called the 'lesser pilgrimage', but it does not discharge the obligation of Hajj." },
    ],
    reflect: [
      { te: "ఉమ్రహ్ కొన్ని గంటల్లో ముగుస్తుంది. ఆ కొన్ని గంటలు మీ తర్వాతి సంవత్సరాన్ని ఎలా మార్చాలని కోరుకుంటారు?", en: "Umrah is over in a few hours. How would you want those few hours to change the year that follows?" },
    ],
    mistakes: [
      { te: "సఅయిని తవాఫ్ ముందు చేయడం — వరుస: తవాఫ్, తర్వాత సఅయి.", en: "Performing sa'i before tawaf. The order is tawaf, then sa'i." },
      { te: "జుట్టు కత్తిరించకుండా ఇహ్రామ్ నుండి బయటకు వచ్చినట్లు భావించడం.", en: "Assuming the ihram has ended without cutting the hair." },
      { te: "ఉమ్రహ్ చేస్తే హజ్ విధి తీరిందని అనుకోవడం.", en: "Believing that performing Umrah discharges the obligation of Hajj." },
    ],
    faqs: [
      {
        question: { te: "ఒకే ప్రయాణంలో ఎన్నిసార్లు ఉమ్రహ్ చేయవచ్చు?", en: "How many times may Umrah be performed in one trip?" },
        answer: {
          te: "పరిమితి లేదు — మీఖాత్‌కు (లేదా తన్‌ఈమ్ వంటి హిల్ ప్రాంతానికి) తిరిగి వెళ్ళి కొత్త ఇహ్రామ్ ధరిస్తే మళ్ళీ చేయవచ్చు. అయితే కొందరు పండితులు పదేపదే చేయడం కంటే మక్కాలో తవాఫ్, ఇబాదత్‌లో గడపడం మేలని అంటారు.",
          en: "There is no fixed limit: you return to the miqat, or to a boundary point such as Tan'im, and enter a fresh ihram. Some scholars hold that spending the time in tawaf and worship in Makkah is better than repeating it many times.",
        },
      },
      {
        question: { te: "ఉమ్రహ్‌కు ఎంత సమయం పడుతుంది?", en: "How long does Umrah take?" },
        answer: {
          te: "రద్దీని బట్టి సాధారణంగా రెండు నుండి నాలుగు గంటలు — తవాఫ్, సఅయి కలిపి. రమజాన్‌లో లేదా హజ్ కాలానికి ముందు ఇది చాలా ఎక్కువ కావచ్చు.",
          en: "Usually two to four hours for the tawaf and sa'i together, depending on crowds. In Ramadan or just before the Hajj season it can take considerably longer.",
        },
      },
    ],
    quiz: [
      {
        question: { te: "ఉమ్రహ్‌లో ఎన్ని దశలు?", en: "How many steps does Umrah have?" },
        options: [
          { te: "నాలుగు", en: "Four" },
          { te: "ఏడు", en: "Seven" },
          { te: "రెండు", en: "Two" },
        ],
        answer: 0,
      },
      {
        question: { te: "ఉమ్రహ్‌లో కింది వాటిలో ఏది ఉండదు?", en: "Which of these is NOT part of Umrah?" },
        options: [
          { te: "అరఫాలో నిలబడటం", en: "Standing at Arafah" },
          { te: "తవాఫ్", en: "Tawaf" },
          { te: "సఅయి", en: "Sa'i" },
        ],
        answer: 0,
      },
      {
        question: { te: "సరైన వరుస ఏది?", en: "Which is the correct order?" },
        options: [
          { te: "ఇహ్రామ్ → తవాఫ్ → సఅయి → జుట్టు", en: "Ihram, tawaf, sa'i, hair" },
          { te: "ఇహ్రామ్ → సఅయి → తవాఫ్ → జుట్టు", en: "Ihram, sa'i, tawaf, hair" },
          { te: "తవాఫ్ → ఇహ్రామ్ → జుట్టు → సఅయి", en: "Tawaf, ihram, hair, sa'i" },
        ],
        answer: 0,
      },
    ],
    revision: [
      { te: "నాలుగు దశలు: ఇహ్రామ్, తవాఫ్, సఅయి, జుట్టు.", en: "Four steps: ihram, tawaf, sa'i, hair." },
      { te: "ఏ సమయంలోనైనా; హజ్ రోజుల్లో తప్ప.", en: "Any time of year, except the days of Hajj." },
      { te: "ఉమ్రహ్ హజ్ విధిని తీర్చదు.", en: "Umrah does not discharge the obligation of Hajj." },
    ],
    summary: {
      te: "ఉమ్రహ్ నాలుగు దశల చిన్న యాత్ర — ఇహ్రామ్, తవాఫ్, సఅయి, జుట్టు — సంవత్సరంలో ఎప్పుడైనా చేయవచ్చు. ఇందులో అరఫా, మినా, రమీ ఉండవు, ఇది హజ్ స్థానంలో రాదు.",
      en: "Umrah is a short pilgrimage of four steps, ihram, tawaf, sa'i and the hair, performable any time of year. It has no Arafah, Mina or stoning, and it does not stand in place of Hajj.",
    },
    apply: {
      te: "ఆచరణ: నాలుగు దశలను వరుసగా ఒక కార్డుపై రాసి, ప్రయాణంలో మీ వద్ద ఉంచుకోండి.",
      en: "Apply it: write the four steps in order on a card and keep it with you for the journey.",
    },
    reading: [
      { label: "Hajj & Umrah portal", url: "/knowledge-center/hajj-umrah" },
      { label: "The five days of Hajj", url: "/knowledge-center/hajj-umrah/days-of-hajj" },
    ],
  },
];
