/* AUTO-GENERATED by scripts/extract-portals.mjs — do not edit by hand.
   Source: the legacy static site's Seerah, Islamic History and Kids portals.
   Re-run to refresh.

   Entries are loosely typed on purpose: each legacy array carries a different
   set of fields, and forcing them into one rigid shape would mean either
   dropping data or inventing empty values. Consumers read the fields they
   need and check for presence. */

export type Bi = { te: string; en: string };
export type PortalEntry = { arabic?: string } & Record<string, Bi | string | undefined>;

/** seerah · EVENTS — 10 entries.
    Fields: arabic, title, yr, s, l */
export const seerahEvents: PortalEntry[] = [
  {
    arabic: "المولد",
    title: { te: "ప్రవక్త ﷺ జననం", en: "Birth of the Prophet ﷺ" },
    yr: { te: "570 సా.శ. · ఏనుగు సంవత్సరం", en: "570 CE · Year of the Elephant" },
    s: { te: "మక్కాలో గౌరవనీయ బనూ హాషిం వంశంలో జన్మించారు; ఆయన జననానికి ముందే తండ్రి మరణించారు.", en: "Born in Makkah into the noble Banu Hashim; his father had passed away before his birth." },
    l: { te: "ప్రతి గొప్ప లక్ష్యం వినయపూర్వక, కష్టమైన ఆరంభం నుండి మొదలవవచ్చు.", en: "Every great mission can begin from humble, difficult beginnings." },
  },
  {
    arabic: "نزول الوحي",
    title: { te: "మొదటి వహీ", en: "First Revelation" },
    yr: { te: "610 సా.శ. · హిరా గుహ", en: "610 CE · Cave of Hira" },
    s: { te: "హిరా గుహలో దైవదూత జిబ్రయీల్ ఖురాన్ తొలి పదాలను — “ఇఖ్రా” (చదువు) — తీసుకువచ్చారు.", en: "Angel Jibreel brought the first words of the Quran — “Iqra” (Read) — in the Cave of Hira." },
    l: { te: "జ్ఞానం, పఠనమే మార్గదర్శనానికి మొట్టమొదటి అడుగు.", en: "Knowledge and reading are the very first step of guidance." },
  },
  {
    arabic: "الهجرة",
    title: { te: "మదీనాకు హిజ్రా", en: "Hijrah to Madinah" },
    yr: { te: "622 సా.శ. · హిజ్రీ క్యాలెండర్ ఆరంభం", en: "622 CE · Start of Hijri calendar" },
    s: { te: "మక్కా నుండి మదీనాకు వలస; ఇది ఇస్లామిక్ క్యాలెండర్ ఆరంభాన్ని సూచిస్తుంది.", en: "The migration from Makkah to Madinah; it marks the start of the Islamic calendar." },
    l: { te: "త్యాగం, అల్లాహ్‌పై నమ్మకం కొత్త ఆరంభానికి ద్వారం తెరుస్తాయి.", en: "Sacrifice and trust in Allah open the door to a new beginning." },
  },
  {
    arabic: "غزوة بدر",
    title: { te: "బద్ర్ యుద్ధం", en: "Battle of Badr" },
    yr: { te: "624 సా.శ. · 2 హిజ్రీ", en: "624 CE · 2 AH" },
    s: { te: "మొదటి పెద్ద యుద్ధం — సుమారు 313 మంది ముస్లింలకు చాలా పెద్ద సైన్యంపై విజయం లభించింది.", en: "The first major battle — about 313 Muslims were given victory over a far larger army." },
    l: { te: "సంఖ్య తక్కువైనా, అల్లాహ్ నిష్కపటులకు సహాయం చేస్తాడు.", en: "Allah aids the sincere, even when they are few in number." },
  },
  {
    arabic: "غزوة أحد",
    title: { te: "ఉహుద్ యుద్ధం", en: "Battle of Uhud" },
    yr: { te: "625 సా.శ. · 3 హిజ్రీ", en: "625 CE · 3 AH" },
    s: { te: "నియమించిన స్థానాన్ని వదలడం ఆధిక్యతను ఎదురుదెబ్బగా మార్చిన కఠిన పరీక్ష.", en: "A hard test in which leaving an assigned post turned an advantage into a setback." },
    l: { te: "క్రమశిక్షణ, ఆదేశాలను పాటించడం నష్టం నుండి కాపాడతాయి.", en: "Discipline and obeying instructions protect us from loss." },
  },
  {
    arabic: "غزوة الخندق",
    title: { te: "ఖందఖ్ యుద్ధం", en: "Battle of Khandaq" },
    yr: { te: "627 సా.శ. · 5 హిజ్రీ", en: "627 CE · 5 AH" },
    s: { te: "కందక యుద్ధం — తెలివైన రక్షణ వ్యూహంతో మదీనా రక్షించబడింది.", en: "The Battle of the Trench — Madinah was defended with a clever defensive strategy." },
    l: { te: "తెలివైన ప్రణాళికతో పాటు అల్లాహ్‌పై నమ్మకం రక్షణను తెస్తుంది.", en: "Wise planning combined with reliance on Allah brings safety." },
  },
  {
    arabic: "صلح الحديبية",
    title: { te: "హుదైబియా ఒప్పందం", en: "Treaty of Hudaybiyyah" },
    yr: { te: "628 సా.శ. · 6 హిజ్రీ", en: "628 CE · 6 AH" },
    s: { te: "అననుకూలంగా కనిపించిన శాంతి ఒప్పందం, కానీ ఖురాన్ దీన్ని “స్పష్టమైన విజయం” అని పిలిచింది.", en: "A peace treaty that seemed unfavourable but the Quran called it a “clear victory”." },
    l: { te: "ఓర్పు, శాంతి సంఘర్షణ కంటే ఎక్కువ సాధించగలవు.", en: "Patience and peace can achieve more than conflict." },
  },
  {
    arabic: "فتح مكة",
    title: { te: "మక్కా విజయం", en: "Conquest of Makkah" },
    yr: { te: "630 సా.శ. · 8 హిజ్రీ", en: "630 CE · 8 AH" },
    s: { te: "మక్కాలోకి శాంతియుతంగా ప్రవేశించారు, పూర్వ శత్రువులకు సాధారణ క్షమాభిక్ష ఇవ్వబడింది.", en: "Makkah was entered peacefully and a general amnesty was granted to former enemies." },
    l: { te: "అధికారం చేతిలో ఉన్నప్పుడు క్షమించడమే నిజమైన బలం.", en: "True strength is to forgive when you hold the power." },
  },
  {
    arabic: "حجة الوداع",
    title: { te: "వీడ్కోలు హజ్", en: "Farewell Pilgrimage" },
    yr: { te: "632 సా.శ. · 10 హిజ్రీ", en: "632 CE · 10 AH" },
    s: { te: "సుమారు 1,24,000 మంది సహచరుల ముందు వీడ్కోలు ప్రసంగం సమానత్వం, హక్కులు, పరిపూర్ణ ధర్మాన్ని ధృవీకరించింది.", en: "The Final Sermon before ~124,000 companions affirmed equality, rights, and the completed religion." },
    l: { te: "మానవులందరూ సమానం; ముఖ్యంగా బలహీనుల హక్కులను గౌరవించండి.", en: "All people are equal; honour rights, especially of the weak." },
  },
  {
    arabic: "وفاة النبي ﷺ",
    title: { te: "ప్రవక్త ﷺ మరణం", en: "Passing of the Prophet ﷺ" },
    yr: { te: "632 సా.శ. · 11 హిజ్రీ", en: "632 CE · 11 AH" },
    s: { te: "సందేశాన్ని పూర్తిగా అందించి, పూర్తి చేసిన తర్వాత ప్రవక్త ﷺ మదీనాలో మరణించారు.", en: "The Prophet ﷺ passed away in Madinah after completing and conveying the message in full." },
    l: { te: "సందేశం సజీవంగా ఉంది — ఇది ఇప్పుడు ప్రతి విశ్వాసిపై ఉన్న అమానత్.", en: "The message lives on — it is now a trust upon every believer." },
  },
];

/** seerah · CHAR — 10 entries.
    Fields: arabic, title, ex, ap */
export const seerahCharacter: PortalEntry[] = [
  {
    arabic: "الرَّحْمَة",
    title: { te: "దయ", en: "Mercy" },
    ex: { te: "ఆయన పిల్లలతో మృదువుగా, జంతువులపై దయగా ఉండేవారు; తాయిఫ్‌లో హాని చేసినవారికీ కోసం దుఆ చేశారు.", en: "He was gentle with children, kind to animals, and prayed for those who harmed him at Taif." },
    ap: { te: "కుటుంబంతో, చిన్నవారితో, బలహీనులతో మృదువుగా ఉండండి.", en: "Be gentle with family, the young, and the weak." },
  },
  {
    arabic: "الأَمَانَة",
    title: { te: "నిజాయితీ", en: "Honesty" },
    ex: { te: "ప్రవక్తత్వానికి ముందే మక్కా ప్రజలు ఆయనను అల్-అమీన్ — నమ్మకస్థుడు — అని పిలిచేవారు.", en: "Even before prophethood the people of Makkah called him Al-Ameen — the Trustworthy." },
    ap: { te: "ఎల్లప్పుడూ మాట నిలబెట్టుకోండి, మీకు అప్పగించినదాన్ని కాపాడండి.", en: "Always keep your word and guard what is entrusted to you." },
  },
  {
    arabic: "الصَّبْر",
    title: { te: "ఓర్పు", en: "Patience" },
    ex: { te: "ఆయన ఆశ కోల్పోకుండా ఏళ్ల తరబడి హింసను, ప్రియమైనవారిని కోల్పోవడాన్ని ఓర్చుకున్నారు.", en: "He endured years of persecution and the loss of loved ones without losing hope." },
    ap: { te: "కష్ట సమయంలో స్థిరంగా ఉండండి, అల్లాహ్‌పై నమ్మకం ఉంచండి.", en: "Stay steadfast and trust Allah during hardship." },
  },
  {
    arabic: "التَّوَاضُع",
    title: { te: "వినయం", en: "Humility" },
    ex: { te: "ఆయన తన దుస్తులను తానే కుట్టుకునేవారు, ఇంటి పనుల్లో సహాయం చేసేవారు, పేదలతో సమానంగా కూర్చునేవారు.", en: "He mended his own clothes, helped at home, and sat among the poor as an equal." },
    ap: { te: "ఇతరులకు సంతోషంగా సేవ చేయండి, ఎవరినీ చిన్నచూపు చూడకండి.", en: "Serve others gladly and never look down on anyone." },
  },
  {
    arabic: "القِيَادَة",
    title: { te: "నాయకత్వం", en: "Leadership" },
    ex: { te: "ఆయన సహచరులతో సంప్రదించేవారు, వారి కష్టాలను పంచుకునేవారు, ఆదర్శంగా నడిపించేవారు.", en: "He consulted his companions, shared their hardships, and led by personal example." },
    ap: { te: "సంప్రదింపులు, న్యాయం, సేవతో నడిపించండి.", en: "Lead with consultation, fairness, and service." },
  },
  {
    arabic: "الكَرَم",
    title: { te: "దానశీలత", en: "Generosity" },
    ex: { te: "ఆయన ఉదారంగా ఇచ్చేవారు; ఏదైనా అడిగినవారిని తిరస్కరించడం ఎన్నడూ తెలియదు.", en: "He gave freely and was never known to refuse a person who asked him for something." },
    ap: { te: "మీ దగ్గర కొంచెమే ఉన్నా సంతోషంగా దానం చేయండి.", en: "Give cheerfully, even when you have little." },
  },
  {
    arabic: "العَفْو",
    title: { te: "క్షమాపణ", en: "Forgiveness" },
    ex: { te: "మక్కాలోకి ప్రవేశించినప్పుడు, ఆయనతో పోరాడి తరిమివేసిన ప్రజలనే ఆయన క్షమించారు.", en: "On entering Makkah he forgave the very people who had fought and driven him out." },
    ap: { te: "మీకు అన్యాయం చేసినవారిని క్షమించండి, ద్వేషాన్ని వదిలేయండి.", en: "Pardon those who wrong you and let go of grudges." },
  },
  {
    arabic: "الشَّجَاعَة",
    title: { te: "ధైర్యం", en: "Courage" },
    ex: { te: "ఆయన యుద్ధంలో స్థిరంగా నిలిచారు, ఒంటరిగా ఉన్నా సత్యాన్ని ధైర్యంగా పలికారు.", en: "He stood firm in battle and spoke the truth boldly, even when he stood alone." },
    ap: { te: "కష్టమైనా సరే, సరైనదాని కోసం నిలబడండి.", en: "Stand for what is right, even when it is hard." },
  },
  {
    arabic: "حُسْنُ العِشْرَة",
    title: { te: "కుటుంబ సంబంధాలు", en: "Family Relations" },
    ex: { te: "ఆయన ఇంటి పనుల్లో సహాయం చేసేవారు, భార్యలతో మృదువుగా ఉండేవారు, మనవళ్లతో ఆడుకునేవారు.", en: "He helped with housework, was tender with his wives, and played with his grandchildren." },
    ap: { te: "మీ కుటుంబానికి ఉత్తమంగా ఉండండి — ఇంట్లో దయగా, చేరువగా, న్యాయంగా.", en: "Be the best to your family — kind, present, and fair at home." },
  },
  {
    arabic: "الأَمَانَة فِي التِّجَارَة",
    title: { te: "వ్యాపార నీతి", en: "Business Ethics" },
    ex: { te: "వ్యాపారిగా ఆయన వస్తువుల గురించి నిజాయితీగా ఉండేవారు, ఎన్నడూ మోసం చేయలేదు, ప్రతి వాగ్దానాన్ని నిలబెట్టుకునేవారు — పూర్తి నమ్మకాన్ని సంపాదించారు.", en: "As a trader he was honest about goods, never cheated, and kept every promise — earning total trust." },
    ap: { te: "సంపాదనలో నిజాయితీగా, న్యాయంగా ఉండండి — మోసం లేదు, వాగ్దాన భంగం లేదు.", en: "Be honest and fair in earning — no cheating, no broken promises." },
  },
];

/** islamic-history · EVENTS — 9 entries.
    Fields: arabic, title, pr, s, l */
export const historyEras: PortalEntry[] = [
  {
    arabic: "الخلافة الراشدة",
    title: { te: "రాషిదూన్ ఖిలాఫత్", en: "Rashidun Caliphate" },
    pr: { te: "632–661 సా.శ.", en: "632–661 CE" },
    s: { te: "నలుగురు సన్మార్గ ఖలీఫాలు న్యాయమైన, వేగంగా విస్తరించే రాజ్యాన్ని నడిపి, ఖురాన్‌ను ఒకే గ్రంథంగా సంకలనం చేశారు.", en: "The four Rightly Guided Caliphs led a just, rapidly expanding state and compiled the Quran into one book." },
    l: { te: "న్యాయమైన నాయకత్వం, సంప్రదింపులు (షూరా) బలమైన సమాజాన్ని నిర్మిస్తాయి.", en: "Just leadership and consultation (shura) build a strong society." },
  },
  {
    arabic: "الدولة الأموية",
    title: { te: "ఉమయ్యద్ ఖిలాఫత్", en: "Umayyad Caliphate" },
    pr: { te: "661–750 సా.శ.", en: "661–750 CE" },
    s: { te: "డమాస్కస్ నుండి రాజ్యం స్పెయిన్, భారత సరిహద్దుల వరకు విస్తరించింది; అరబిక్ పరిపాలనా భాషగా మారింది.", en: "From Damascus the state expanded to Spain and the borders of India, with Arabic as the language of administration." },
    l: { te: "బలమైన వ్యవస్థ నమ్మకాన్ని విస్తృత ప్రభావంగా మారుస్తుంది.", en: "Strong organization turns conviction into far-reaching impact." },
  },
  {
    arabic: "الدولة العباسية",
    title: { te: "అబ్బాసీద్ ఖిలాఫత్", en: "Abbasid Caliphate" },
    pr: { te: "750–1258 సా.శ.", en: "750–1258 CE" },
    s: { te: "బాగ్దాద్ కేంద్రంగా అబ్బాసీదులు బైతుల్ హిక్మాను స్థాపించి, జ్ఞానం, అనువాదాల గొప్ప యుగాన్ని నడిపారు.", en: "Centred in Baghdad, the Abbasids founded the House of Wisdom and led a great age of learning and translation." },
    l: { te: "జ్ఞానంలో పెట్టుబడి పెట్టడం అంటే నాగరికతలోనే పెట్టుబడి పెట్టడం.", en: "Investing in knowledge is investing in civilization itself." },
  },
  {
    arabic: "العصر الذهبي",
    title: { te: "ఇస్లామిక్ స్వర్ణయుగం", en: "Islamic Golden Age" },
    pr: { te: "8–13 శతాబ్దాలు", en: "8th–13th century" },
    s: { te: "ముస్లిం పండితులు గణితం, వైద్యం, ఖగోళశాస్త్రం మొదలైనవాటిని అభివృద్ధి చేసి, ప్రపంచ జ్ఞానాన్ని కాపాడి ముందుకు తీసుకెళ్లారు.", en: "Muslim scholars advanced mathematics, medicine, astronomy, and more, preserving and building on world knowledge." },
    l: { te: "విశ్వాసం, వివేచన ఒకదానికొకటి విరుద్ధంగా కాక కలిసి ముందుకు సాగుతాయి.", en: "Faith and reason advance together, not against each other." },
  },
  {
    arabic: "الأندلس",
    title: { te: "ముస్లిం స్పెయిన్ (అల్-అందలూస్)", en: "Muslim Spain (Al-Andalus)" },
    pr: { te: "711–1492 సా.శ.", en: "711–1492 CE" },
    s: { te: "కార్డోబా జ్ఞానం, గ్రంథాలయాలు, సహజీవనానికి కేంద్రంగా మారి మధ్యయుగ ఐరోపాకు వెలుగునిచ్చింది.", en: "Cordoba became a centre of learning, libraries, and coexistence that lit up medieval Europe." },
    l: { te: "జ్ఞానం, సహనం గొప్పతనాన్ని నిర్మిస్తాయి; విభజన దాన్ని నాశనం చేస్తుంది.", en: "Knowledge and tolerance build greatness; division destroys it." },
  },
  {
    arabic: "الدولة العثمانية",
    title: { te: "ఉస్మానీయ సామ్రాజ్యం", en: "Ottoman Empire" },
    pr: { te: "1299–1924 సా.శ.", en: "1299–1924 CE" },
    s: { te: "600 ఏళ్లకు పైగా కొనసాగిన ఉస్మానీయులు 1453లో కాన్‌స్టాంటినోపుల్‌ను జయించి మూడు ఖండాలను పాలించారు.", en: "Spanning over 600 years, the Ottomans conquered Constantinople in 1453 and ruled three continents." },
    l: { te: "దృష్టి, క్రమశిక్షణ సామ్రాజ్యాలను నిర్మిస్తాయి; సంస్కరణను నిర్లక్ష్యం చేస్తే అవి ముగుస్తాయి.", en: "Vision and discipline build empires; neglecting reform ends them." },
  },
  {
    arabic: "الإمبراطورية المغولية",
    title: { te: "మొఘల్ సామ్రాజ్యం", en: "Mughal Empire" },
    pr: { te: "1526–1857 సా.శ.", en: "1526–1857 CE" },
    s: { te: "భారతదేశంలో మొఘలులు వాస్తుశిల్పం (తాజ్ మహల్), కళలు మరియు బలమైన పరిపాలనా వారసత్వాన్ని మిగిల్చారు.", en: "In India the Mughals left a legacy of architecture (the Taj Mahal), the arts, and strong administration." },
    l: { te: "బలం ఒక్కటే కంటే న్యాయం, సంస్కృతి పాలనను ఎక్కువ కాలం నిలబెడతాయి.", en: "Justice and culture sustain rule longer than force alone." },
  },
  {
    arabic: "نهاية الخلافة",
    title: { te: "ఖిలాఫత్ ముగింపు", en: "End of the Caliphate" },
    pr: { te: "1924 సా.శ.", en: "1924 CE" },
    s: { te: "వలసవాద ఒత్తిడి మధ్య ఉస్మానీయ ఖిలాఫత్ రద్దు చేయబడి, శతాబ్దాల ఐక్య ముస్లిం నాయకత్వం ముగిసింది.", en: "The Ottoman Caliphate was abolished amid colonial pressure, ending centuries of unified Muslim leadership." },
    l: { te: "విభజన, పరాధీనత బలమైన ఉమ్మత్‌ను కూడా బలహీనపరుస్తాయి.", en: "Disunity and dependence weaken even the strongest Ummah." },
  },
  {
    arabic: "العصر الحديث",
    title: { te: "ఆధునిక యుగం", en: "Modern Era" },
    pr: { te: "1924 – నేటి వరకు", en: "1924 – present" },
    s: { te: "స్వాతంత్ర్య ఉద్యమాలు ఆధునిక ముస్లిం దేశ-రాజ్యాలకు జన్మనిచ్చాయి; అవి ఇప్పుడు పునరుజ్జీవనం, పురోగతిని కోరుతున్నాయి.", en: "Independence movements gave rise to modern Muslim nation-states now seeking renewal and progress." },
    l: { te: "పునరుజ్జీవనం జ్ఞానం, ఐక్యత మరియు మంచి స్వభావం ద్వారా వస్తుంది.", en: "Renewal comes through knowledge, unity, and good character." },
  },
];

/** islamic-history · PEOPLE — 10 entries.
    Fields: arabic, title, role, bio, leg */
export const historyPeople: PortalEntry[] = [
  {
    arabic: "أبو بكر الصِّدِّيق",
    title: { te: "అబూ బక్ర్ (రజి)", en: "Abu Bakr (RA)" },
    role: { te: "1వ ఖలీఫా · 632–634 సా.శ.", en: "1st Caliph · 632–634 CE" },
    bio: { te: "ప్రవక్త అత్యంత సన్నిహిత సహచరుడు; అరేబియాను ఏకం చేసి ఖురాన్ తొలి సంకలనానికి ఆదేశించారు.", en: "The Prophet’s closest companion; he united Arabia and ordered the first compilation of the Quran." },
    leg: { te: "సత్యంపై అచంచల విశ్వాసం మరియు స్థిరమైన విధేయత.", en: "Steadfast loyalty and unshakeable conviction in truth." },
  },
  {
    arabic: "عُمر بن الخطّاب",
    title: { te: "ఉమర్ (రజి)", en: "Umar (RA)" },
    role: { te: "2వ ఖలీఫా · 634–644 సా.శ.", en: "2nd Caliph · 634–644 CE" },
    bio: { te: "ఆయన న్యాయపాలనలో రాజ్యం విస్తృతంగా విస్తరించింది; పరిపాలనా వ్యవస్థను నిర్మించి, హిజ్రీ క్యాలెండర్‌ను ప్రారంభించారు.", en: "Under his just rule the state expanded vastly; he built administration and began the Hijri calendar." },
    leg: { te: "న్యాయం, జవాబుదారీతనం నాయకత్వానికి హృదయం.", en: "Justice and accountability are the heart of leadership." },
  },
  {
    arabic: "عُثمان بن عفّان",
    title: { te: "ఉస్మాన్ (రజి)", en: "Uthman (RA)" },
    role: { te: "3వ ఖలీఫా · 644–656 సా.శ.", en: "3rd Caliph · 644–656 CE" },
    bio: { te: "గొప్ప దానశీలతకు పేరొందారు; ఉమ్మత్ కోసం ఖురాన్‌ను ఒకే ప్రామాణిక గ్రంథంగా నియమబద్ధం చేశారు.", en: "Known for great generosity; he standardised the Quran into a single authoritative text for the Ummah." },
    leg: { te: "దానశీలత, వినయం మరియు ఖురాన్‌ను శాశ్వతంగా సంరక్షించడం.", en: "Generosity, modesty, and preserving the Quran for all time." },
  },
  {
    arabic: "علي بن أبي طالب",
    title: { te: "అలీ (రజి)", en: "Ali (RA)" },
    role: { te: "4వ ఖలీఫా · 656–661 సా.శ.", en: "4th Caliph · 656–661 CE" },
    bio: { te: "ప్రవక్త ﷺ వద్ద పెరిగారు; లోతైన జ్ఞానం, న్యాయం, ధైర్యం మరియు వాగ్ధాటికి పేరొందారు.", en: "Raised by the Prophet ﷺ, he was renowned for deep knowledge, justice, bravery, and eloquence." },
    leg: { te: "ధైర్యం, నిష్కపట భక్తితో కలిసిన జ్ఞానం.", en: "Knowledge joined with courage and sincere devotion." },
  },
  {
    arabic: "صلاح الدين الأيوبي",
    title: { te: "సలాహుద్దీన్ అయ్యూబీ", en: "Salahuddin Ayyubi" },
    role: { te: "సుల్తాన్ · 12వ శతాబ్దం", en: "Sultan · 12th century" },
    bio: { te: "ముస్లిం భూములను ఏకం చేసి జెరూసలేంను విముక్తం చేశారు; శత్రువుల మధ్యలోనూ ఆయన దయ, వీరత్వానికి పేరొందారు.", en: "United Muslim lands and liberated Jerusalem, famed even among foes for his chivalry and mercy." },
    leg: { te: "శత్రువుల పట్ల కూడా దయతో కూడిన ఏకోన్ముఖ లక్ష్యం.", en: "Unity of purpose with mercy, even toward enemies." },
  },
  {
    arabic: "محمد الفاتح",
    title: { te: "ముహమ్మద్ అల్-ఫాతిహ్", en: "Muhammad Al-Fatih" },
    role: { te: "ఉస్మానీయ సుల్తాన్ · 1453", en: "Ottoman Sultan · 1453" },
    bio: { te: "కేవలం 21 ఏళ్లకే కాన్‌స్టాంటినోపుల్‌ను జయించి, ఒక ప్రవచనాన్ని నెరవేర్చి చరిత్రలో కొత్త అధ్యాయాన్ని తెరిచారు.", en: "At just 21 he conquered Constantinople, fulfilling a prophecy and opening a new chapter of history." },
    leg: { te: "దృష్టి, జాగ్రత్తైన సన్నద్ధత మరియు అచంచల సంకల్పం.", en: "Vision, careful preparation, and unshakeable determination." },
  },
  {
    arabic: "ابن سينا",
    title: { te: "ఇబ్న్ సీనా", en: "Ibn Sina (Avicenna)" },
    role: { te: "వైద్యుడు · 980–1037 సా.శ.", en: "Physician · 980–1037 CE" },
    bio: { te: "వైద్యుడు, తత్త్వవేత్త; ఆయన ‘ఖానూన్ ఫిల్ తిబ్’ ఐరోపాలో 600 ఏళ్లకు పైగా బోధించబడింది.", en: "Physician and philosopher; his “Canon of Medicine” was taught in Europe for over 600 years." },
    leg: { te: "శతాబ్దాలపాటు ప్రపంచానికి మార్గనిర్దేశం చేసిన వైద్యం, వివేచన.", en: "Medicine and reasoning that guided the world for centuries." },
  },
  {
    arabic: "الخوارزمي",
    title: { te: "అల్-ఖ్వారిజ్మీ", en: "Al-Khwarizmi" },
    role: { te: "గణితవేత్త · 9వ శతాబ్దం", en: "Mathematician · 9th century" },
    bio: { te: "బీజగణిత పితామహుడు; ‘అల్గోరిథమ్’, ‘ఆల్జీబ్రా’ పదాలు ఆయన రచనల నుండే వచ్చాయి.", en: "The father of algebra; the words “algorithm” and “algebra” come from his work." },
    leg: { te: "ఆధునిక కంప్యూటింగ్‌కు ఆధారమైన గణిత పునాదులు.", en: "Foundations of mathematics that power modern computing." },
  },
  {
    arabic: "ابن خلدون",
    title: { te: "ఇబ్న్ ఖల్దూన్", en: "Ibn Khaldun" },
    role: { te: "చరిత్రకారుడు · 1332–1406 సా.శ.", en: "Historian · 1332–1406 CE" },
    bio: { te: "సామాజిక శాస్త్రం, చరిత్ర శాస్త్రీయ అధ్యయనానికి ఆద్యుడు; ప్రఖ్యాత ‘ముఖద్దిమా’ రచయిత.", en: "Founder of sociology and the scientific study of history; author of the famed “Muqaddimah”." },
    leg: { te: "జాతుల ఉన్నతి, పతనాన్ని అర్థం చేసుకునే శాస్త్రీయ పద్ధతి.", en: "A scientific way to understand the rise and fall of nations." },
  },
  {
    arabic: "أورنكزيب",
    title: { te: "ఔరంగజేబు", en: "Aurangzeb" },
    role: { te: "మొఘల్ చక్రవర్తి · 1618–1707", en: "Mughal Emperor · 1618–1707" },
    bio: { te: "మొఘల్ సామ్రాజ్యాన్ని దాని శిఖరంలో పాలించి, ‘ఫతావా ఆలంగిరి’ న్యాయ సంకలనాన్ని పర్యవేక్షించారు.", en: "Ruled the vast Mughal realm at its peak and oversaw the legal compilation “Fatawa Alamgiri”." },
    leg: { te: "పరిపాలన, న్యాయంలో విస్తృతంగా అధ్యయనం, చర్చ జరిగే వ్యక్తి.", en: "A widely studied, debated figure in administration and law." },
  },
];

/** islamic-history · EMPIRES — 5 entries.
    Fields: arabic, title, pr, rise, ach, leg */
export const historyEmpires: PortalEntry[] = [
  {
    arabic: "الأمويون",
    title: { te: "ఉమయ్యద్ ఖిలాఫత్", en: "Umayyad Caliphate" },
    pr: { te: "661–750 సా.శ.", en: "661–750 CE" },
    rise: { te: "డమాస్కస్ నుండి ఉద్భవించి, విస్తృత రాజ్యాన్ని వ్యవస్థీకరించిన మొదటి వంశపారంపర్య ఖిలాఫత్‌గా మారింది.", en: "Rose from Damascus and became the first hereditary caliphate, organising a vast new state." },
    ach: { te: "స్పెయిన్, సింధు వరకు విస్తరించి, అరబిక్‌ను పరిపాలనా భాషగా చేసి, ఇస్లామిక్ నాణేలను ముద్రించింది.", en: "Expanded to Spain and the Indus, made Arabic the language of administration, and minted Islamic coinage." },
    leg: { te: "బలమైన వ్యవస్థ విశ్వాసాన్ని విస్తృత నాగరికతగా ఎలా మారుస్తుందో చూపింది.", en: "Showed how strong organisation turns faith into a far-reaching civilization." },
  },
  {
    arabic: "العباسيون",
    title: { te: "అబ్బాసీద్ ఖిలాఫత్", en: "Abbasid Caliphate" },
    pr: { te: "750–1258 సా.శ.", en: "750–1258 CE" },
    rise: { te: "అధికారంలోకి వచ్చి, జ్ఞానం, వాణిజ్యానికి కేంద్రంగా బాగ్దాద్ నగరాన్ని స్థాపించారు.", en: "Came to power and founded Baghdad as a round city of learning and trade." },
    ach: { te: "బైతుల్ హిక్మాను నిర్మించి, విజ్ఞానం, వైద్యం, అనువాదాల స్వర్ణయుగాన్ని నడిపారు.", en: "Built the House of Wisdom and led the Golden Age of science, medicine, and translation." },
    leg: { te: "జ్ఞానంలో పెట్టుబడి అంటే నాగరికతలోనే పెట్టుబడి అని నిరూపించారు.", en: "Proved that investing in knowledge is investing in civilization itself." },
  },
  {
    arabic: "العثمانيون",
    title: { te: "ఉస్మానీయ సామ్రాజ్యం", en: "Ottoman Empire" },
    pr: { te: "1299–1924 సా.శ.", en: "1299–1924 CE" },
    rise: { te: "ఒక చిన్న అనటోలియన్ రాజ్యం నుండి మూడు ఖండాలలో విస్తరించిన శక్తిగా ఎదిగింది.", en: "Grew from a small Anatolian state into a power spanning three continents." },
    ach: { te: "1453లో కాన్‌స్టాంటినోపుల్‌ను జయించి, 600 ఏళ్లపాటు వాస్తుశిల్పం, న్యాయం, పరిపాలనను అభివృద్ధి చేసింది.", en: "Conquered Constantinople in 1453, advanced architecture, law, and administration for 600 years." },
    leg: { te: "దృష్టి, క్రమశిక్షణ సామ్రాజ్యాలను నిర్మిస్తాయని, సంస్కరణ నిర్లక్ష్యం వాటిని ముగిస్తుందని చూపింది.", en: "Showed that vision and discipline build empires, while neglecting reform ends them." },
  },
  {
    arabic: "المغول",
    title: { te: "మొఘల్ సామ్రాజ్యం", en: "Mughal Empire" },
    pr: { te: "1526–1857 సా.శ.", en: "1526–1857 CE" },
    rise: { te: "భారతదేశంలో స్థాపించబడి, తన యుగంలోని అత్యంత సంపన్న రాజ్యాలలో ఒకటిగా ఎదిగింది.", en: "Founded in India and grew into one of the wealthiest realms of its age." },
    ach: { te: "వాస్తుశిల్పం (తాజ్ మహల్), కళలు మరియు బలమైన పరిపాలనా వారసత్వాన్ని మిగిల్చింది.", en: "Left a legacy of architecture (the Taj Mahal), the arts, and a strong administration." },
    leg: { te: "బలం ఒక్కటే కంటే న్యాయం, సంస్కృతి పాలనను ఎక్కువ కాలం నిలబెడతాయని చూపింది.", en: "Showed that justice and culture sustain rule longer than force alone." },
  },
  {
    arabic: "الأندلس",
    title: { te: "అల్-అందలూస్ (ముస్లిం స్పెయిన్)", en: "Al-Andalus (Muslim Spain)" },
    pr: { te: "711–1492 సా.శ.", en: "711–1492 CE" },
    rise: { te: "ఐబీరియాలోకి ప్రవేశంతో మొదలై, కార్డోబా నగరం చుట్టూ వర్ధిల్లింది.", en: "Began with the crossing into Iberia and flourished around the city of Cordoba." },
    ach: { te: "కార్డోబా గ్రంథాలయాలు, విజ్ఞానం, సహజీవనానికి కేంద్రంగా మారి మధ్యయుగ ఐరోపాకు వెలుగునిచ్చింది.", en: "Cordoba became a centre of libraries, science, and coexistence that enlightened medieval Europe." },
    leg: { te: "జ్ఞానం, సహనం గొప్పతనాన్ని నిర్మిస్తాయని, విభజన దాన్ని నాశనం చేస్తుందని చూపింది.", en: "Showed that knowledge and tolerance build greatness, while division destroys it." },
  },
];

/** islamic-history · CITIES — 7 entries.
    Fields: title, reg, imp, sig */
export const historyCities: PortalEntry[] = [
  {
    title: { te: "మక్కా", en: "Makkah" },
    reg: { te: "అరేబియా · పవిత్ర నగరం", en: "Arabia · Holy City" },
    imp: { te: "ప్రవక్త ﷺ జన్మస్థలం, కాబా నిలయం — ఇస్లాం ఖిబ్లా మరియు ఆధ్యాత్మిక హృదయం.", en: "The birthplace of the Prophet ﷺ and home of the Kaaba — the qiblah and spiritual heart of Islam." },
    sig: { te: "ప్రతి జాతి నుండి లక్షలాది మందిని ఏకం చేసే వార్షిక హజ్ గమ్యస్థానం.", en: "The destination of the annual Hajj that unites millions from every nation." },
  },
  {
    title: { te: "మదీనా", en: "Madinah" },
    reg: { te: "అరేబియా · ప్రవక్త నగరం", en: "Arabia · City of the Prophet" },
    imp: { te: "హిజ్రా నగరం, మస్జిద్ నబవీ నిలయం మరియు మొదటి వ్యవస్థీకృత ముస్లిం సమాజం.", en: "The city of the Hijrah, home of the Prophet’s Mosque and the first organised Muslim community." },
    sig: { te: "మొదటి ఇస్లామిక్ రాజ్యం, దాని ఒడంబడిక, సామాజిక జీవనం రూపుదిద్దుకున్న చోటు.", en: "Where the first Islamic state, its constitution, and community life took shape." },
  },
  {
    title: { te: "బాగ్దాద్", en: "Baghdad" },
    reg: { te: "ఇరాక్ · అబ్బాసీద్ రాజధాని", en: "Iraq · Abbasid Capital" },
    imp: { te: "అబ్బాసీద్ రాజధాని, బైతుల్ హిక్మా నిలయం — ప్రపంచంలోనే గొప్ప జ్ఞాన కేంద్రం.", en: "The Abbasid capital and home of the House of Wisdom, the world’s greatest centre of learning." },
    sig: { te: "స్వర్ణయుగ హృదయం — గ్రీకు, భారతీయ, పర్షియన్ జ్ఞానం కాపాడబడి, ముందుకు సాగిన చోటు.", en: "Heart of the Golden Age, where Greek, Indian, and Persian knowledge was preserved and advanced." },
  },
  {
    title: { te: "డమాస్కస్", en: "Damascus" },
    reg: { te: "సిరియా · ఉమయ్యద్ రాజధాని", en: "Syria · Umayyad Capital" },
    imp: { te: "ఉమయ్యద్ రాజధాని, ప్రపంచంలో నిరంతరం నివాసమున్న అత్యంత పురాతన నగరాలలో ఒకటి.", en: "The Umayyad capital, one of the oldest continuously inhabited cities in the world." },
    sig: { te: "మొదటి గొప్ప ముస్లిం సామ్రాజ్య కేంద్రం, చారిత్రక ఉమయ్యద్ మస్జిద్ నిలయం.", en: "Centre of the first great Muslim empire and home of the historic Umayyad Mosque." },
  },
  {
    title: { te: "కార్డోబా", en: "Cordoba" },
    reg: { te: "స్పెయిన్ · అల్-అందలూస్", en: "Spain · Al-Andalus" },
    imp: { te: "ముస్లిం స్పెయిన్ రత్నం — తారు రోడ్లు, వీధి దీపాలు, లక్షలాది గ్రంథాల గ్రంథాలయాలు.", en: "The jewel of Muslim Spain, with paved, lit streets and libraries holding hundreds of thousands of books." },
    sig: { te: "ఐరోపా తదుపరి పునరుజ్జీవనానికి దోహదపడిన విజ్ఞానం, సహజీవనం దీపం.", en: "A beacon of science and coexistence that helped spark Europe’s later revival." },
  },
  {
    title: { te: "ఇస్తాంబుల్", en: "Istanbul" },
    reg: { te: "టర్కీ · ఉస్మానీయ రాజధాని", en: "Turkey · Ottoman Capital" },
    imp: { te: "1453లో జయించబడి, ఐరోపా, ఆసియాను కలిపే ఉస్మానీయ రాజధానిగా మారింది.", en: "Conquered in 1453, it became the Ottoman capital bridging Europe and Asia." },
    sig: { te: "దాదాపు ఐదు శతాబ్దాలపాటు ఉస్మానీయ కళ, వాస్తుశిల్పం, పరిపాలన కేంద్రం.", en: "Centre of Ottoman art, architecture, and administration for nearly five centuries." },
  },
  {
    title: { te: "ఢిల్లీ", en: "Delhi" },
    reg: { te: "భారతదేశం · మొఘల్ రాజధాని", en: "India · Mughal Capital" },
    imp: { te: "ముస్లిం భారతదేశ గొప్ప రాజధాని, మొఘల్ కళలు, విద్య, వాస్తుశిల్ప కేంద్రం.", en: "A great capital of Muslim India and a centre of the Mughal arts, learning, and architecture." },
    sig: { te: "నేటికీ నిలిచే స్మారకాలు, సుసంపన్న ఇండో-ఇస్లామిక్ సంస్కృతికి నిలయం.", en: "Home to monuments and a rich Indo-Islamic culture that endures today." },
  },
];

/** kids-islam · PROPHETS — 7 entries.
    Fields: arabic, title, sum, les, act */
export const kidsProphets: PortalEntry[] = [
  {
    arabic: "آدم",
    title: { te: "ఆదమ్ (అ.స)", en: "Adam (AS)" },
    sum: { te: "అల్లాహ్ ఆదమ్ (అ.స)ను మొదటి మానవునిగా, మొదటి ప్రవక్తగా సృష్టించి, దైవదూతల కంటే ఆయనను గౌరవించాడు.", en: "Allah created Adam ﷺ as the first human and the first prophet, and honoured him above the angels." },
    les: { te: "అందరూ తప్పులు చేస్తారు — అల్లాహ్‌ను క్షమాపణ కోరితే ఆయన క్షమిస్తాడు.", en: "Everyone makes mistakes — say sorry to Allah and He forgives." },
    act: { te: "నేడు ఎవరికైనా క్షమాపణ చెప్పి, అల్లాహ్‌ను క్షమించమని కోరండి.", en: "Say sorry to someone today and ask Allah to forgive you." },
  },
  {
    arabic: "نوح",
    title: { te: "నూహ్ (అ.స)", en: "Nuh (AS)" },
    sum: { te: "నూహ్ (అ.స) చాలా ఏళ్లపాటు తన ప్రజలను అల్లాహ్ వైపు పిలిచి, విశ్వాసులను కాపాడటానికి ఒక పెద్ద ఓడను నిర్మించారు.", en: "Nuh ﷺ called his people to Allah for many years and built a great ark to save the believers." },
    les: { te: "ఇతరులు నవ్వినా ఓర్పుగా ఉండి అల్లాహ్‌పై నమ్మకం ఉంచండి.", en: "Be patient and keep trusting Allah, even when others laugh." },
    act: { te: "నేడు ఒక కష్టమైన పనిని వదలకుండా పూర్తి చేయండి.", en: "Finish one hard task today without giving up." },
  },
  {
    arabic: "إبراهيم",
    title: { te: "ఇబ్రాహీమ్ (అ.స)", en: "Ibrahim (AS)" },
    sum: { te: "ఇబ్రాహీమ్ (అ.స) విగ్రహాలను పగలగొట్టారు, అల్లాహ్ ఆయనను అగ్ని నుండి కాపాడాడు, తన కుమారునితో కలిసి కాబాను నిర్మించారు.", en: "Ibrahim ﷺ broke the idols, was saved from the fire by Allah, and built the Kaaba with his son." },
    les: { te: "సత్యం కోసం నిలబడండి, అల్లాహ్‌పై పూర్తి నమ్మకం ఉంచండి.", en: "Stand up for the truth and trust Allah completely." },
    act: { te: "కొంచెం భయమనిపించినా నేడు నిజం చెప్పండి.", en: "Tell the truth today, even if it feels a little scary." },
  },
  {
    arabic: "يوسف",
    title: { te: "యూసుఫ్ (అ.స)", en: "Yusuf (AS)" },
    sum: { te: "యూసుఫ్ (అ.స)ను ఆయన సోదరులు చెడుగా చూశారు, కానీ ఆయన ఓర్పుగా ఉండి తర్వాత ఈజిప్టులో గొప్ప నాయకుడయ్యారు.", en: "Yusuf ﷺ was treated badly by his brothers but stayed patient and later became a great leader in Egypt." },
    les: { te: "ఓర్పుగా ఉండి ఇతరులను క్షమించండి — అల్లాహ్ ప్రణాళికే ఎల్లప్పుడూ ఉత్తమం.", en: "Be patient and forgive others — Allah's plan is always best." },
    act: { te: "మిమ్మల్ని బాధపెట్టిన సోదరుడు, సోదరి లేదా స్నేహితుడిని క్షమించండి.", en: "Forgive a brother, sister, or friend who upset you." },
  },
  {
    arabic: "موسى",
    title: { te: "మూసా (అ.స)", en: "Musa (AS)" },
    sum: { te: "మూసా (అ.స) క్రూరమైన ఫిరౌన్‌ను ధైర్యంగా ఎదిరించారు, అల్లాహ్ ఆయన ప్రజలను కాపాడటానికి సముద్రాన్ని చీల్చాడు.", en: "Musa ﷺ bravely stood up to the cruel Pharaoh, and Allah parted the sea to save his people." },
    les: { te: "అల్లాహ్ సహాయంతో ధైర్యంగా ఉండండి, సరైనదాని కోసం ఎన్నడూ వదలకండి.", en: "Be brave with Allah's help and never give up on what is right." },
    act: { te: "నేడు ఒక ధైర్యమైన మంచి పని చేయండి — అవసరంలో ఉన్నవారికి సహాయం చేయండి.", en: "Do one brave good thing today, like helping someone in need." },
  },
  {
    arabic: "عيسى",
    title: { te: "ఈసా (అ.స)", en: "Isa (AS)" },
    sum: { te: "ఈసా (అ.స) మర్యమ్‌కు అద్భుతంగా జన్మించారు, శిశువుగా మాట్లాడారు, అల్లాహ్ అనుమతితో అద్భుతాలు చేశారు.", en: "Isa ﷺ was born miraculously to Maryam, spoke as a baby, and did wonderful miracles by Allah's permission." },
    les: { te: "అల్లాహ్ ఏదైనా చేయగలడు — ఎల్లప్పుడూ వినయంగా, దయగా ఉండండి.", en: "Allah can do anything — always be humble and kind." },
    act: { te: "నేడు మీరు కలిసే ప్రతి ఒక్కరితో మృదువుగా, వినయంగా ఉండండి.", en: "Be gentle and humble with everyone you meet today." },
  },
  {
    arabic: "محمد ﷺ",
    title: { te: "ముహమ్మద్ ﷺ", en: "Muhammad ﷺ" },
    sum: { te: "ముహమ్మద్ ﷺ చివరి ప్రవక్త, అల్-అమీన్‌గా పేరొందారు, ఖురాన్‌తో సర్వలోకాలకు కారుణ్యంగా పంపబడ్డారు.", en: "Muhammad ﷺ is the final prophet, known as Al-Ameen, sent as a mercy to the whole world with the Quran." },
    les: { te: "నిజాయితీగా, దయగా ఉండి ఆయన అందమైన ఆదర్శాన్ని అనుసరించండి.", en: "Be honest and kind, and follow his beautiful example." },
    act: { te: "ఎవరికైనా చిరునవ్వుతో ఒక మంచి మాట చెప్పండి — అది ఆయన సున్నత్.", en: "Smile and say a kind word to someone — that is his Sunnah." },
  },
];
