/* Generated by scripts/build-quran.mjs -- do not edit.

   Metadata for all 114 surahs. The text itself is not here: it lives in
   public/quran/NNN.json and is fetched when a surah is opened. This file is
   bundled, so it has to stay small enough to be worth bundling.

   Arabic text: Tanzil.net / King Fahad Quran Complex (CC BY-ND)
   Telugu: Abdul Raheem Mohammad Moulana
   English: Mufti Taqi Usmani */

export type SurahMeta = {
  n: number;
  /** Arabic name, as written on the surah heading of a mushaf. */
  ar: string;
  en: string;
  te: string;
  /** What the name means, in English. */
  meaning: string;
  ayahs: number;
  revealed: "makkah" | "madinah";
  /** Opening page and juz in a standard 604-page mushaf. */
  page: number;
  juz: number;
};

export const surahIndex: SurahMeta[] = [
  {"n":1,"ar":"سُوْرَةُ الْفَاتِحَةِ","en":"Al-Fatihah","te":"అల్-ఫాతిహా","meaning":"The Opening","ayahs":7,"revealed":"makkah","page":1,"juz":1},
  {"n":2,"ar":"سُوْرَةُ البَقَرَةِ","en":"Al-Baqarah","te":"అల్-బఖరా","meaning":"The Cow","ayahs":286,"revealed":"madinah","page":2,"juz":1},
  {"n":3,"ar":"سُوْرَةُ اٰلِ عِمْرٰنَ","en":"Aal-Imran","te":"ఆల్-ఇమ్రాన్","meaning":"The Family of Imraan","ayahs":200,"revealed":"madinah","page":50,"juz":3},
  {"n":4,"ar":"سُوْرَةُ النِّسَآءِ","en":"An-Nisa","te":"అన్-నిసా","meaning":"The Women","ayahs":176,"revealed":"madinah","page":77,"juz":4},
  {"n":5,"ar":"سُوْرَةُ المَآئِدَةِ","en":"Al-Ma'idah","te":"అల్-మాయిదా","meaning":"The Table","ayahs":120,"revealed":"madinah","page":106,"juz":6},
  {"n":6,"ar":"سُوْرَةُ الْاَنْعَامِ","en":"Al-An'am","te":"అల్-అన్ఆమ్","meaning":"The Cattle","ayahs":165,"revealed":"makkah","page":128,"juz":7},
  {"n":7,"ar":"سُوْرَةُ الْاَعْرَافِ","en":"Al-A'raf","te":"అల్-అఅరాఫ్","meaning":"The Heights","ayahs":206,"revealed":"makkah","page":151,"juz":8},
  {"n":8,"ar":"سُوْرَةُ الْاَنْفَالِ","en":"Al-Anfal","te":"అల్-అన్ఫాల్","meaning":"The Spoils of War","ayahs":75,"revealed":"madinah","page":177,"juz":9},
  {"n":9,"ar":"سُوْرَةُ التَّوْبَةِ","en":"At-Tawbah","te":"అత్-తౌబా","meaning":"The Repentance","ayahs":129,"revealed":"madinah","page":187,"juz":10},
  {"n":10,"ar":"سُوْرَةُ يُوْنُسَ","en":"Yunus","te":"యూనుస్","meaning":"Jonas","ayahs":109,"revealed":"makkah","page":208,"juz":11},
  {"n":11,"ar":"سُوْرَةُ هُوْدٍ","en":"Hud","te":"హూద్","meaning":"Hud","ayahs":123,"revealed":"makkah","page":221,"juz":11},
  {"n":12,"ar":"سُوْرَةُ يُوسُفَ","en":"Yusuf","te":"యూసుఫ్","meaning":"Joseph","ayahs":111,"revealed":"makkah","page":235,"juz":12},
  {"n":13,"ar":"سُوْرَةُ الرَّعْدِ","en":"Ar-Ra'd","te":"అర్-రఅద్","meaning":"The Thunder","ayahs":43,"revealed":"madinah","page":249,"juz":13},
  {"n":14,"ar":"سُوْرَةُ اِبْرَاهِيْمَ","en":"Ibrahim","te":"ఇబ్రాహీమ్","meaning":"Abraham","ayahs":52,"revealed":"makkah","page":255,"juz":13},
  {"n":15,"ar":"سُوْرَةُ الْحِجْرِ","en":"Al-Hijr","te":"అల్-హిజ్ర్","meaning":"The Rock","ayahs":99,"revealed":"makkah","page":262,"juz":14},
  {"n":16,"ar":"سُوْرَةُ النَّحْلِ","en":"An-Nahl","te":"అన్-నహ్ల్","meaning":"The Bee","ayahs":128,"revealed":"makkah","page":267,"juz":14},
  {"n":17,"ar":"سُوْرَةُ الإِسۡرَاءِ","en":"Al-Isra","te":"అల్-ఇస్రా","meaning":"The Night Journey","ayahs":111,"revealed":"makkah","page":282,"juz":15},
  {"n":18,"ar":"سُوْرَةُ الْكَهْفِ","en":"Al-Kahf","te":"అల్-కహ్ఫ్","meaning":"The Cave","ayahs":110,"revealed":"makkah","page":293,"juz":15},
  {"n":19,"ar":"سُوْرَةُ مَرْيَمَ","en":"Maryam","te":"మర్యమ్","meaning":"Mary","ayahs":98,"revealed":"makkah","page":305,"juz":16},
  {"n":20,"ar":"سُوْرَةُ طٰهٰ","en":"Ta-Ha","te":"తా-హా","meaning":"Taa-Haa","ayahs":135,"revealed":"makkah","page":312,"juz":16},
  {"n":21,"ar":"سُوْرَةُ الْاَنْۣبِيَآءِ","en":"Al-Anbiya","te":"అల్-అంబియా","meaning":"The Prophets","ayahs":112,"revealed":"makkah","page":322,"juz":17},
  {"n":22,"ar":"سُوْرَةُ الْحَجِّ","en":"Al-Hajj","te":"అల్-హజ్","meaning":"The Pilgrimage","ayahs":78,"revealed":"madinah","page":332,"juz":17},
  {"n":23,"ar":"سُوْرَةُ الْمُؤْمِنُوْنَ","en":"Al-Mu'minun","te":"అల్-మూమినూన్","meaning":"The Believers","ayahs":118,"revealed":"makkah","page":342,"juz":18},
  {"n":24,"ar":"سُوْرَةُ النُّوْرِ","en":"An-Nur","te":"అన్-నూర్","meaning":"The Light","ayahs":64,"revealed":"madinah","page":350,"juz":18},
  {"n":25,"ar":"سُوْرَةُ الْفُرْقَانِ","en":"Al-Furqan","te":"అల్-ఫుర్ఖాన్","meaning":"The Criterion","ayahs":77,"revealed":"makkah","page":359,"juz":18},
  {"n":26,"ar":"سُوْرَةُ الشُّعَرَآءِ","en":"Ash-Shu'ara","te":"అష్-షుఅరా","meaning":"The Poets","ayahs":227,"revealed":"makkah","page":367,"juz":19},
  {"n":27,"ar":"سُوْرَةُ النَّمْلِ","en":"An-Naml","te":"అన్-నమ్ల్","meaning":"The Ant","ayahs":93,"revealed":"makkah","page":377,"juz":19},
  {"n":28,"ar":"سُوْرَةُ الْقَصَصِ","en":"Al-Qasas","te":"అల్-ఖసస్","meaning":"The Stories","ayahs":88,"revealed":"makkah","page":385,"juz":20},
  {"n":29,"ar":"سُوْرَةُ الْعَنْكَبُوْتِ","en":"Al-Ankabut","te":"అల్-అన్కబూత్","meaning":"The Spider","ayahs":69,"revealed":"makkah","page":396,"juz":20},
  {"n":30,"ar":"سُوْرَةُ الرُّوْمِ","en":"Ar-Rum","te":"అర్-రూమ్","meaning":"The Romans","ayahs":60,"revealed":"makkah","page":404,"juz":21},
  {"n":31,"ar":"سُوْرَةُ لُقْمَانَ","en":"Luqman","te":"లుఖ్మాన్","meaning":"Luqman","ayahs":34,"revealed":"makkah","page":411,"juz":21},
  {"n":32,"ar":"سُوْرَةُ السَّجْدَةِ","en":"As-Sajdah","te":"అస్-సజ్దా","meaning":"The Prostration","ayahs":30,"revealed":"makkah","page":415,"juz":21},
  {"n":33,"ar":"سُوْرَةُ الْاَحْزَابِ","en":"Al-Ahzab","te":"అల్-అహ్జాబ్","meaning":"The Clans","ayahs":73,"revealed":"madinah","page":418,"juz":21},
  {"n":34,"ar":"سُوْرَةُ سَبَاٍ","en":"Saba","te":"సబా","meaning":"Sheba","ayahs":54,"revealed":"makkah","page":428,"juz":22},
  {"n":35,"ar":"سُوْرَةُ فَاطِرٍ","en":"Fatir","te":"ఫాతిర్","meaning":"The Originator","ayahs":45,"revealed":"makkah","page":434,"juz":22},
  {"n":36,"ar":"سُوْرَةُ يٰسٓ","en":"Ya-Sin","te":"యాసీన్","meaning":"Yaseen","ayahs":83,"revealed":"makkah","page":440,"juz":22},
  {"n":37,"ar":"سُوْرَةُ الصَّافَّاتِ","en":"As-Saffat","te":"అస్-సాఫ్ఫాత్","meaning":"Those drawn up in Ranks","ayahs":182,"revealed":"makkah","page":446,"juz":23},
  {"n":38,"ar":"سُوْرَةُ صٓ","en":"Sad","te":"సాద్","meaning":"The letter Saad","ayahs":88,"revealed":"makkah","page":453,"juz":23},
  {"n":39,"ar":"سُوْرَةُ الزُّمَرِ","en":"Az-Zumar","te":"అజ్-జుమర్","meaning":"The Groups","ayahs":75,"revealed":"makkah","page":458,"juz":23},
  {"n":40,"ar":"سُوْرَةُ الْمُؤْمِنِ","en":"Ghafir","te":"ఘాఫిర్","meaning":"The Forgiver","ayahs":85,"revealed":"makkah","page":467,"juz":24},
  {"n":41,"ar":"سُوْرَةُ فُصِّلَتۡ","en":"Fussilat","te":"ఫుస్సిలత్","meaning":"Explained in detail","ayahs":54,"revealed":"makkah","page":477,"juz":24},
  {"n":42,"ar":"سُوْرَةُ الشُّوْرٰي","en":"Ash-Shura","te":"అష్-షూరా","meaning":"Consultation","ayahs":53,"revealed":"makkah","page":483,"juz":25},
  {"n":43,"ar":"سُوْرَةُ الزُّخْرُفِ","en":"Az-Zukhruf","te":"అజ్-జుఖ్రుఫ్","meaning":"Ornaments of gold","ayahs":89,"revealed":"makkah","page":489,"juz":25},
  {"n":44,"ar":"سُوْرَةُ الدُّخَانِ","en":"Ad-Dukhan","te":"అద్-దుఖాన్","meaning":"The Smoke","ayahs":59,"revealed":"makkah","page":496,"juz":25},
  {"n":45,"ar":"سُوْرَةُ الْجَاثِيَةِ","en":"Al-Jathiyah","te":"అల్-జాసియా","meaning":"Crouching","ayahs":37,"revealed":"makkah","page":499,"juz":25},
  {"n":46,"ar":"سُوْرَةُ الْاَحْقَافِ","en":"Al-Ahqaf","te":"అల్-అహ్ఖాఫ్","meaning":"The Dunes","ayahs":35,"revealed":"makkah","page":502,"juz":26},
  {"n":47,"ar":"سُوْرَةُ مُحَمَّدٍ","en":"Muhammad","te":"ముహమ్మద్","meaning":"Muhammad","ayahs":38,"revealed":"madinah","page":507,"juz":26},
  {"n":48,"ar":"سُوْرَةُ الْفَتْحِ","en":"Al-Fath","te":"అల్-ఫత్హ్","meaning":"The Victory","ayahs":29,"revealed":"madinah","page":511,"juz":26},
  {"n":49,"ar":"سُوْرَةُ الْحُجُراتِ","en":"Al-Hujurat","te":"అల్-హుజురాత్","meaning":"The Inner Apartments","ayahs":18,"revealed":"madinah","page":515,"juz":26},
  {"n":50,"ar":"سُوْرَةُ قٓ","en":"Qaf","te":"ఖాఫ్","meaning":"The letter Qaaf","ayahs":45,"revealed":"makkah","page":518,"juz":26},
  {"n":51,"ar":"سُوْرَةُ الذَّارِياتِ","en":"Adh-Dhariyat","te":"అజ్-జారియాత్","meaning":"The Winnowing Winds","ayahs":60,"revealed":"makkah","page":520,"juz":26},
  {"n":52,"ar":"سُوْرَةُ الطُّوْرِ","en":"At-Tur","te":"అత్-తూర్","meaning":"The Mount","ayahs":49,"revealed":"makkah","page":523,"juz":27},
  {"n":53,"ar":"سُوْرَةُ النَّجْمِ","en":"An-Najm","te":"అన్-నజ్మ్","meaning":"The Star","ayahs":62,"revealed":"makkah","page":526,"juz":27},
  {"n":54,"ar":"سُوْرَةُ الْقَمَرِ","en":"Al-Qamar","te":"అల్-ఖమర్","meaning":"The Moon","ayahs":55,"revealed":"makkah","page":528,"juz":27},
  {"n":55,"ar":"سُوْرَةُ الرَّحْمٰنِ","en":"Ar-Rahman","te":"అర్-రహ్మాన్","meaning":"The Beneficent","ayahs":78,"revealed":"madinah","page":531,"juz":27},
  {"n":56,"ar":"سُوْرَةُ الْوَاقِعَةِ","en":"Al-Waqi'ah","te":"అల్-వాఖియా","meaning":"The Inevitable","ayahs":96,"revealed":"makkah","page":534,"juz":27},
  {"n":57,"ar":"سُوْرَةُ الْحَدِيْدِ","en":"Al-Hadid","te":"అల్-హదీద్","meaning":"The Iron","ayahs":29,"revealed":"madinah","page":537,"juz":27},
  {"n":58,"ar":"سُوْرَةُ الْمُجَادَلَةِ","en":"Al-Mujadilah","te":"అల్-ముజాదిలా","meaning":"The Pleading Woman","ayahs":22,"revealed":"madinah","page":542,"juz":28},
  {"n":59,"ar":"سُوْرَةُ الْحَشْرِ","en":"Al-Hashr","te":"అల్-హష్ర్","meaning":"The Exile","ayahs":24,"revealed":"madinah","page":545,"juz":28},
  {"n":60,"ar":"سُوْرَةُ الْمُمْتَحِنَةِ","en":"Al-Mumtahanah","te":"అల్-ముమ్తహినా","meaning":"She that is to be examined","ayahs":13,"revealed":"madinah","page":549,"juz":28},
  {"n":61,"ar":"سُوْرَةُ الصَّفِّ","en":"As-Saff","te":"అస్-సఫ్","meaning":"The Ranks","ayahs":14,"revealed":"madinah","page":551,"juz":28},
  {"n":62,"ar":"سُوْرَةُ الْجُمُعَةِ","en":"Al-Jumu'ah","te":"అల్-జుముఆ","meaning":"Friday","ayahs":11,"revealed":"madinah","page":553,"juz":28},
  {"n":63,"ar":"سُوْرَةُ الْمُنَافِقُوْنَ","en":"Al-Munafiqun","te":"అల్-మునాఫిఖూన్","meaning":"The Hypocrites","ayahs":11,"revealed":"madinah","page":554,"juz":28},
  {"n":64,"ar":"سُوْرَةُ التَّغَابُنِ","en":"At-Taghabun","te":"అత్-తగాబున్","meaning":"Mutual Disillusion","ayahs":18,"revealed":"madinah","page":556,"juz":28},
  {"n":65,"ar":"سُوْرَةُ الطَّلَاقِ","en":"At-Talaq","te":"అత్-తలాఖ్","meaning":"Divorce","ayahs":12,"revealed":"madinah","page":558,"juz":28},
  {"n":66,"ar":"سُوْرَةُ التَّحْرِيْمِ","en":"At-Tahrim","te":"అత్-తహ్రీమ్","meaning":"The Prohibition","ayahs":12,"revealed":"madinah","page":560,"juz":28},
  {"n":67,"ar":"سُوْرَةُ الْمُلْكِ","en":"Al-Mulk","te":"అల్-ముల్క్","meaning":"The Sovereignty","ayahs":30,"revealed":"makkah","page":562,"juz":29},
  {"n":68,"ar":"سُوْرَةُ الْقَلَمِ","en":"Al-Qalam","te":"అల్-ఖలమ్","meaning":"The Pen","ayahs":52,"revealed":"makkah","page":564,"juz":29},
  {"n":69,"ar":"سُوْرَةُ الْحَآقَّةِ","en":"Al-Haqqah","te":"అల్-హాఖ్ఖా","meaning":"The Reality","ayahs":52,"revealed":"makkah","page":566,"juz":29},
  {"n":70,"ar":"سُوْرَةُ الْمَعَارِجِ","en":"Al-Ma'arij","te":"అల్-మఆరిజ్","meaning":"The Ascending Stairways","ayahs":44,"revealed":"makkah","page":568,"juz":29},
  {"n":71,"ar":"سُوْرَةُ نُوْحٍ","en":"Nuh","te":"నూహ్","meaning":"Noah","ayahs":28,"revealed":"makkah","page":570,"juz":29},
  {"n":72,"ar":"سُوْرَةُ الْجِنِّ","en":"Al-Jinn","te":"అల్-జిన్న్","meaning":"The Jinn","ayahs":28,"revealed":"makkah","page":572,"juz":29},
  {"n":73,"ar":"سُوْرَةُ الْمُزَّمِّلِ","en":"Al-Muzzammil","te":"అల్-ముజ్జమ్మిల్","meaning":"The Enshrouded One","ayahs":20,"revealed":"makkah","page":574,"juz":29},
  {"n":74,"ar":"سُوْرَةُ الْمُدَّثِّرِ","en":"Al-Muddaththir","te":"అల్-ముద్దస్సిర్","meaning":"The Cloaked One","ayahs":56,"revealed":"makkah","page":575,"juz":29},
  {"n":75,"ar":"سُوْرَةُ الْقِيَامَةِ","en":"Al-Qiyamah","te":"అల్-ఖియామా","meaning":"The Resurrection","ayahs":40,"revealed":"makkah","page":577,"juz":29},
  {"n":76,"ar":"سُوْرَةُ الدَّهْرِ","en":"Al-Insan","te":"అల్-ఇన్సాన్","meaning":"Man","ayahs":31,"revealed":"madinah","page":578,"juz":29},
  {"n":77,"ar":"سُوْرَةُ الْمُرْسَلَاتِ","en":"Al-Mursalat","te":"అల్-ముర్సలాత్","meaning":"The Emissaries","ayahs":50,"revealed":"makkah","page":580,"juz":29},
  {"n":78,"ar":"سُوْرَةُ النَّبَاِ","en":"An-Naba","te":"అన్-నబా","meaning":"The Announcement","ayahs":40,"revealed":"makkah","page":582,"juz":30},
  {"n":79,"ar":"سُوْرَةُ النَّازِعَاتِ","en":"An-Nazi'at","te":"అన్-నాజిఆత్","meaning":"Those who drag forth","ayahs":46,"revealed":"makkah","page":583,"juz":30},
  {"n":80,"ar":"سُوْرَةُ عَبَسَ","en":"Abasa","te":"అబస","meaning":"He frowned","ayahs":42,"revealed":"makkah","page":585,"juz":30},
  {"n":81,"ar":"سُوْرَةُ التَّكْوِيْرِ","en":"At-Takwir","te":"అత్-తక్వీర్","meaning":"The Overthrowing","ayahs":29,"revealed":"makkah","page":586,"juz":30},
  {"n":82,"ar":"سُوْرَةُ الْاِنْفِطَارِ","en":"Al-Infitar","te":"అల్-ఇన్ఫితార్","meaning":"The Cleaving","ayahs":19,"revealed":"makkah","page":587,"juz":30},
  {"n":83,"ar":"سُوْرَةُ المُطَفِّفِيْنَ","en":"Al-Mutaffifin","te":"అల్-ముతఫ్ఫిఫీన్","meaning":"Defrauding","ayahs":36,"revealed":"makkah","page":587,"juz":30},
  {"n":84,"ar":"سُوْرَةُ الاِنْشِقَاقِ","en":"Al-Inshiqaq","te":"అల్-ఇన్షిఖాఖ్","meaning":"The Splitting Open","ayahs":25,"revealed":"makkah","page":589,"juz":30},
  {"n":85,"ar":"سُوْرَةُ الْبُرُوْجِ","en":"Al-Buruj","te":"అల్-బురూజ్","meaning":"The Constellations","ayahs":22,"revealed":"makkah","page":590,"juz":30},
  {"n":86,"ar":"سُوْرَةُ الطَّارِقِ","en":"At-Tariq","te":"అత్-తారిఖ్","meaning":"The Morning Star","ayahs":17,"revealed":"makkah","page":591,"juz":30},
  {"n":87,"ar":"سُوْرَةُ الْاَعْلٰي","en":"Al-A'la","te":"అల్-అఅలా","meaning":"The Most High","ayahs":19,"revealed":"makkah","page":591,"juz":30},
  {"n":88,"ar":"سُوْرَةُ الْغَاشِيَةِ","en":"Al-Ghashiyah","te":"అల్-గాషియా","meaning":"The Overwhelming","ayahs":26,"revealed":"makkah","page":592,"juz":30},
  {"n":89,"ar":"سُوْرَةُ الْفَجْرِ","en":"Al-Fajr","te":"అల్-ఫజ్ర్","meaning":"The Dawn","ayahs":30,"revealed":"makkah","page":593,"juz":30},
  {"n":90,"ar":"سُوْرَةُ الْبَلَدِ","en":"Al-Balad","te":"అల్-బలద్","meaning":"The City","ayahs":20,"revealed":"makkah","page":594,"juz":30},
  {"n":91,"ar":"سُوْرَةُ الشَّمْسِ","en":"Ash-Shams","te":"అష్-షమ్స్","meaning":"The Sun","ayahs":15,"revealed":"makkah","page":595,"juz":30},
  {"n":92,"ar":"سُوْرَةُ الَّيْلِ","en":"Al-Layl","te":"అల్-లైల్","meaning":"The Night","ayahs":21,"revealed":"makkah","page":595,"juz":30},
  {"n":93,"ar":"سُوْرَةُ الضُّحٰي","en":"Ad-Duha","te":"అద్-దుహా","meaning":"The Morning Hours","ayahs":11,"revealed":"makkah","page":596,"juz":30},
  {"n":94,"ar":"سُوْرَةُ الشَّرْحِ","en":"Ash-Sharh","te":"అష్-షర్హ్","meaning":"The Consolation","ayahs":8,"revealed":"makkah","page":596,"juz":30},
  {"n":95,"ar":"سُوْرَةُ التِّيْنِ","en":"At-Tin","te":"అత్-తీన్","meaning":"The Fig","ayahs":8,"revealed":"makkah","page":597,"juz":30},
  {"n":96,"ar":"سُوْرَةُ الْعَلَقِ","en":"Al-Alaq","te":"అల్-అలఖ్","meaning":"The Clot","ayahs":19,"revealed":"makkah","page":597,"juz":30},
  {"n":97,"ar":"سُوْرَةُ الْقَدْرِ","en":"Al-Qadr","te":"అల్-ఖద్ర్","meaning":"The Power, Fate","ayahs":5,"revealed":"makkah","page":598,"juz":30},
  {"n":98,"ar":"سُوْرَةُ الْبَيِّنَةِ","en":"Al-Bayyinah","te":"అల్-బయ్యినా","meaning":"The Evidence","ayahs":8,"revealed":"madinah","page":598,"juz":30},
  {"n":99,"ar":"سُوْرَةُ الزِّلْزَالِ","en":"Az-Zalzalah","te":"అజ్-జల్జలా","meaning":"The Earthquake","ayahs":8,"revealed":"madinah","page":599,"juz":30},
  {"n":100,"ar":"سُوْرَةُ العٰدِيٰتِ","en":"Al-Adiyat","te":"అల్-ఆదియాత్","meaning":"The Chargers","ayahs":11,"revealed":"makkah","page":599,"juz":30},
  {"n":101,"ar":"سُوْرَةُ الْقَارِعَةِ","en":"Al-Qari'ah","te":"అల్-ఖారిఆ","meaning":"The Calamity","ayahs":11,"revealed":"makkah","page":600,"juz":30},
  {"n":102,"ar":"سُوْرَةُ التَّكَاثُرِ","en":"At-Takathur","te":"అత్-తకాసుర్","meaning":"Competition","ayahs":8,"revealed":"makkah","page":600,"juz":30},
  {"n":103,"ar":"سُوْرَةُ الْعَصْرِ","en":"Al-Asr","te":"అల్-అస్ర్","meaning":"The Declining Day, Epoch","ayahs":3,"revealed":"makkah","page":601,"juz":30},
  {"n":104,"ar":"سُوْرَةُ الْهُمَزَةِ","en":"Al-Humazah","te":"అల్-హుమజా","meaning":"The Traducer","ayahs":9,"revealed":"makkah","page":601,"juz":30},
  {"n":105,"ar":"سُوْرَةُ الْفِيْلِ","en":"Al-Fil","te":"అల్-ఫీల్","meaning":"The Elephant","ayahs":5,"revealed":"makkah","page":601,"juz":30},
  {"n":106,"ar":"سُوْرَةُ قُرَيْشٍ","en":"Quraysh","te":"ఖురైష్","meaning":"Quraysh","ayahs":4,"revealed":"makkah","page":602,"juz":30},
  {"n":107,"ar":"سُوْرَةُ الْمَاعُوْنِ","en":"Al-Ma'un","te":"అల్-మాఊన్","meaning":"Almsgiving","ayahs":7,"revealed":"makkah","page":602,"juz":30},
  {"n":108,"ar":"سُوْرَةُ الْكَوْثَرِ","en":"Al-Kawthar","te":"అల్-కౌసర్","meaning":"Abundance","ayahs":3,"revealed":"makkah","page":602,"juz":30},
  {"n":109,"ar":"سُوْرَةُ الْكَافِرُوْنَ","en":"Al-Kafirun","te":"అల్-కాఫిరూన్","meaning":"The Disbelievers","ayahs":6,"revealed":"makkah","page":603,"juz":30},
  {"n":110,"ar":"سُوْرَةُ النَّصْرِ","en":"An-Nasr","te":"అన్-నస్ర్","meaning":"Divine Support","ayahs":3,"revealed":"madinah","page":603,"juz":30},
  {"n":111,"ar":"سُوْرَةُ المَسَدِ","en":"Al-Masad","te":"అల్-మసద్","meaning":"The Palm Fibre","ayahs":5,"revealed":"makkah","page":603,"juz":30},
  {"n":112,"ar":"سُوْرَةُ الْاِخْلَاصِ","en":"Al-Ikhlas","te":"అల్-ఇఖ్లాస్","meaning":"Sincerity","ayahs":4,"revealed":"makkah","page":604,"juz":30},
  {"n":113,"ar":"سُوْرَةُ الْفَلَقِ","en":"Al-Falaq","te":"అల్-ఫలఖ్","meaning":"The Dawn","ayahs":5,"revealed":"makkah","page":604,"juz":30},
  {"n":114,"ar":"سُوْرَةُ النَّاسِ","en":"An-Nas","te":"అన్-నాస్","meaning":"Mankind","ayahs":6,"revealed":"makkah","page":604,"juz":30},
];

export const TOTAL_AYAHS = 6236;

export const QURAN_SOURCES = {
  "arabic": "Tanzil.net / King Fahad Quran Complex (CC BY-ND)",
  "telugu": "Abdul Raheem Mohammad Moulana",
  "english": "Mufti Taqi Usmani",
  "translit": "Quran phonetic transliteration"
};
