/* AUTO-GENERATED by scripts/extract-vocab.mjs — do not edit by hand.
   Source: the legacy static site's language portals. Re-run to refresh. */

export type Bi = { te: string; en: string };

export type VocabWord = {
  glyph: string;
  translit: string;
  meaning: Bi;
  /** Why this word is worth knowing — usage, Quranic frequency, nuance. */
  note: Bi;
};

export type Phrase = {
  glyph: string;
  translit: Bi;
  meaning: Bi;
};

export const arabicWords: VocabWord[] = [
  {
    glyph: "رَحْمَة",
    translit: "Raḥmah",
    meaning: { te: "కరుణ", en: "Mercy" },
    note: { te: "ఖురాన్‌లో 114 సార్లు వాడబడింది — ప్రతి బిస్మిల్లాహ్‌లో ఒకసారి.", en: "Used 114 times in the Quran — once in every Bismillah." },
  },
  {
    glyph: "صَبْر",
    translit: "Ṣabr",
    meaning: { te: "సహనం", en: "Patience" },
    note: { te: "అల్లాహ్ సహనం గలవారితో ఉంటాడు (ఖుర్ఆన్ 2:153).", en: "Allah is with the patient (Quran 2:153)." },
  },
  {
    glyph: "إِيمَان",
    translit: "Īmān",
    meaning: { te: "విశ్వాసం", en: "Faith" },
    note: { te: "ముస్లిం జీవితానికి పునాది.", en: "The foundation of a Muslim's life." },
  },
  {
    glyph: "تَوْبَة",
    translit: "Tawbah",
    meaning: { te: "పశ్చాత్తాపం", en: "Repentance" },
    note: { te: "అల్లాహ్ పశ్చాత్తాప పడేవారిని ప్రేమిస్తాడు (ఖుర్ఆన్ 2:222).", en: "Allah loves those who repent (Quran 2:222)." },
  },
  {
    glyph: "شُكْر",
    translit: "Shukr",
    meaning: { te: "కృతజ్ఞత", en: "Gratitude" },
    note: { te: "మీరు కృతజ్ఞులైతే నేను మీకు మరింత ఇస్తాను (ఖుర్ఆన్ 14:7).", en: "If you are grateful, I will give you more (Quran 14:7)." },
  },
  {
    glyph: "نِيَّة",
    translit: "Niyyah",
    meaning: { te: "ఉద్దేశ్యం", en: "Intention" },
    note: { te: "చర్యలు వాటి ఉద్దేశ్యాలచే తీర్మానించబడతాయి (హదీస్).", en: "Actions are judged by their intentions (Hadith)." },
  },
  {
    glyph: "جَنَّة",
    translit: "Jannah",
    meaning: { te: "స్వర్గం", en: "Paradise" },
    note: { te: "సద్గుణవంతుల శాశ్వత నివాసం.", en: "The eternal abode of the righteous." },
  },
  {
    glyph: "تَقْوَى",
    translit: "Taqwā",
    meaning: { te: "అల్లాహ్ భయం", en: "God-consciousness" },
    note: { te: "ఉత్తమ వనరు తఖ్వా (ఖుర్ఆన్ 2:197).", en: "The best provision is taqwā (Quran 2:197)." },
  },
  {
    glyph: "عِلْم",
    translit: "ʿIlm",
    meaning: { te: "జ్ఞానం", en: "Knowledge" },
    note: { te: "జ్ఞానాన్వేషణ ప్రతి ముస్లిముపై విధి.", en: "Seeking knowledge is an obligation on every Muslim." },
  },
  {
    glyph: "ذِكْر",
    translit: "Dhikr",
    meaning: { te: "స్మరణ", en: "Remembrance" },
    note: { te: "అల్లాహ్ స్మరణలో హృదయాలు శాంతి పొందుతాయి (ఖుర్ఆన్ 13:28).", en: "Hearts find peace in the remembrance of Allah (Quran 13:28)." },
  },
  {
    glyph: "دُعَاء",
    translit: "Duʿāʾ",
    meaning: { te: "దువా", en: "Supplication" },
    note: { te: "దువా ఆరాధన యొక్క సారాంశం (హదీస్).", en: "Duʿāʾ is the essence of worship (Hadith)." },
  },
  {
    glyph: "بَرَكَة",
    translit: "Barakah",
    meaning: { te: "దీవెన", en: "Blessing" },
    note: { te: "అన్ని విషయాలలో దైవిక సమృద్ధి.", en: "Divine abundance in all matters." },
  },
  {
    glyph: "هُدَى",
    translit: "Hudā",
    meaning: { te: "మార్గదర్శనం", en: "Guidance" },
    note: { te: "ఖురాన్ మానవాళికి మార్గదర్శనం (ఖుర్ఆన్ 2:185).", en: "The Quran is guidance for mankind (Quran 2:185)." },
  },
  {
    glyph: "مَغْفِرَة",
    translit: "Maghfirah",
    meaning: { te: "క్షమాపణ", en: "Forgiveness" },
    note: { te: "అల్-గఫ్ఫార్ (మన్నించేవాడు) అల్లాహ్ నామం.", en: "Al-Ghaffār (The Oft-Forgiving) is a name of Allah." },
  },
  {
    glyph: "حِكْمَة",
    translit: "Ḥikmah",
    meaning: { te: "వివేకం", en: "Wisdom" },
    note: { te: "వివేకం పొందినవాడు ఎంతో మేలు పొందాడు (ఖుర్ఆన్ 2:269).", en: "He who is given wisdom has been given much good (Quran 2:269)." },
  },
  {
    glyph: "أَمَانَة",
    translit: "Amānah",
    meaning: { te: "విశ్వసనీయత", en: "Trust" },
    note: { te: "అమానత్ నిలబెట్టడం నిజమైన విశ్వాస చిహ్నం.", en: "Fulfilling trust is a mark of true faith." },
  },
  {
    glyph: "عَدْل",
    translit: "ʿAdl",
    meaning: { te: "న్యాయం", en: "Justice" },
    note: { te: "అల్లాహ్ న్యాయాన్ని మరియు మంచి ప్రవర్తనను ఆదేశిస్తాడు (ఖుర్ఆన్ 16:90).", en: "Allah commands justice and good conduct (Quran 16:90)." },
  },
  {
    glyph: "تَوَكُّل",
    translit: "Tawakkul",
    meaning: { te: "అల్లాహ్‌పై నమ్మకం", en: "Trust in Allah" },
    note: { te: "ఒంటెను కట్టు, ఆపై అల్లాహ్‌పై నమ్మకం ఉంచు.", en: "Tie your camel, then put your trust in Allah." },
  },
  {
    glyph: "إِخْلَاص",
    translit: "Ikhlāṣ",
    meaning: { te: "నిష్కాపట్యం", en: "Sincerity" },
    note: { te: "అల్లాహ్ కోసం మాత్రమే స్వచ్ఛమైన భక్తి — ఒక సూరహ్ పేరు కూడా.", en: "Pure devotion for Allah alone — also a Surah name." },
  },
  {
    glyph: "سَكِينَة",
    translit: "Sakīnah",
    meaning: { te: "ప్రశాంతత", en: "Tranquility" },
    note: { te: "అల్లాహ్ విశ్వాసుల హృదయాలలో ప్రశాంతత పంపాడు (ఖుర్ఆన్ 48:4).", en: "Allah sent tranquility into the hearts of believers (Quran 48:4)." },
  },
  {
    glyph: "رِزْق",
    translit: "Rizq",
    meaning: { te: "జీవనాధారం", en: "Provision" },
    note: { te: "అన్ని జీవనాధారం అల్లాహ్ నుండే వస్తుంది (ఖుర్ఆన్ 51:58).", en: "All provision comes from Allah (Quran 51:58)." },
  },
  {
    glyph: "يَقِين",
    translit: "Yaqīn",
    meaning: { te: "నిశ్చయత", en: "Certainty" },
    note: { te: "నిశ్చయత వచ్చేవరకు నీ ప్రభువును ఆరాధించు (ఖుర్ఆన్ 15:99).", en: "Worship your Lord until certainty comes to you (Quran 15:99)." },
  },
  {
    glyph: "صِدْق",
    translit: "Ṣidq",
    meaning: { te: "సత్యం", en: "Truthfulness" },
    note: { te: "సత్యవాదులతో ఉండండి (ఖుర్ఆన్ 9:119).", en: "Be with the truthful (Quran 9:119)." },
  },
  {
    glyph: "خَشْيَة",
    translit: "Khashyah",
    meaning: { te: "భయభక్తి", en: "Reverence" },
    note: { te: "జ్ఞానులు మాత్రమే అల్లాహ్‌ను నిజంగా భయపడతారు (ఖుర్ఆన్ 35:28).", en: "Only those who know truly fear Allah (Quran 35:28)." },
  },
  {
    glyph: "حَيَاء",
    translit: "Ḥayāʾ",
    meaning: { te: "సిగ్గు", en: "Modesty" },
    note: { te: "సిగ్గు పూర్తిగా మంచిదే (హదీస్).", en: "Modesty is entirely goodness (Hadith)." },
  },
  {
    glyph: "تَفَكُّر",
    translit: "Tafakkur",
    meaning: { te: "ఆలోచన", en: "Reflection" },
    note: { te: "ఒక గంట ఆలోచన ఏడాది ఆరాధన కంటే మేలు.", en: "An hour of reflection is better than a year of worship." },
  },
  {
    glyph: "وَفَاء",
    translit: "Wafāʾ",
    meaning: { te: "విధేయత", en: "Loyalty" },
    note: { te: "ఒప్పందాలు నెరవేర్చడం ఇస్లాంలో ప్రశంసనీయం.", en: "Fulfilling covenants is highly praised in Islam." },
  },
  {
    glyph: "قَنَاعَة",
    translit: "Qanāʿah",
    meaning: { te: "సంతృప్తి", en: "Contentment" },
    note: { te: "సంతృప్తి శాశ్వత నిధి (హదీస్).", en: "Contentment is an everlasting treasure (Hadith)." },
  },
  {
    glyph: "تَوَاضُع",
    translit: "Tawāḍuʿ",
    meaning: { te: "వినమ్రత", en: "Humility" },
    note: { te: "అల్లాహ్ కోసం వినమ్రత చూపేవారిని అల్లాహ్ ఉన్నతం చేస్తాడు.", en: "Whoever humbles himself for Allah, Allah elevates him." },
  },
  {
    glyph: "إِحْسَان",
    translit: "Iḥsān",
    meaning: { te: "శ్రేష్ఠత", en: "Excellence" },
    note: { te: "అల్లాహ్‌ను చూస్తున్నట్లు ఆరాధించడం (జిబ్రీల్ హదీస్).", en: "To worship Allah as if you see Him (Hadith of Jibreel)." },
  },
];

export const arabicPhrases: Phrase[] = [
  {
    glyph: "السَّلَامُ عَلَيْكُمْ",
    translit: { te: "అస్-సలాము అలైకుమ్", en: "As-salamu alaykum" },
    meaning: { te: "మీపై శాంతి కలుగుగాక — ముస్లిం అభివాదనం.", en: "Peace be upon you — the Muslim greeting." },
  },
  {
    glyph: "وَعَلَيْكُمُ السَّلَام",
    translit: { te: "వ అలైకుము స్-సలామ్", en: "Wa alaykumu as-salam" },
    meaning: { te: "మీపై కూడా శాంతి కలుగుగాక — అభివాదనకు సమాధానం.", en: "And upon you be peace — the reply to the greeting." },
  },
  {
    glyph: "بِسْمِ اللَّهِ",
    translit: { te: "బిస్మిల్లాహ్", en: "Bismillah" },
    meaning: { te: "అల్లాహ్ పేరుతో — ఏదైనా మొదలుపెట్టే ముందు.", en: "In the name of Allah — said before starting anything." },
  },
  {
    glyph: "الْحَمْدُ لِلَّهِ",
    translit: { te: "అల్‌హందులిల్లాహ్", en: "Alhamdulillah" },
    meaning: { te: "సర్వ స్తోత్రం అల్లాహ్‌కే — కృతజ్ఞతతో చెప్పేది.", en: "All praise is for Allah — said in thankfulness." },
  },
  {
    glyph: "إِنْ شَاءَ اللَّهُ",
    translit: { te: "ఇన్‌షా అల్లాహ్", en: "InshaAllah" },
    meaning: { te: "అల్లాహ్ తలిస్తే — భవిష్యత్తు గురించి చెప్పేది.", en: "If Allah wills — said about the future." },
  },
  {
    glyph: "مَا شَاءَ اللَّهُ",
    translit: { te: "మాషా అల్లాహ్", en: "MashaAllah" },
    meaning: { te: "అల్లాహ్ తలచినదే — మెచ్చుకోలుతో చెప్పేది.", en: "What Allah has willed — said in admiration." },
  },
  {
    glyph: "جَزَاكَ اللَّهُ خَيْرًا",
    translit: { te: "జజాకల్లాహు ఖైరన్", en: "JazakAllahu khayran" },
    meaning: { te: "అల్లాహ్ మీకు మేలు ప్రసాదించుగాక — ధన్యవాదాలు చెప్పే అందమైన విధానం.", en: "May Allah reward you with good — a beautiful way to say thank you." },
  },
  {
    glyph: "سُبْحَانَ اللَّهِ",
    translit: { te: "సుబ్‌హానల్లాహ్", en: "SubhanAllah" },
    meaning: { te: "అల్లాహ్ పవిత్రుడు — ఆశ్చర్యం, భక్తితో చెప్పేది.", en: "Glory be to Allah — said in wonder and awe." },
  },
];

export const urduWords: VocabWord[] = [
  {
    glyph: "رحمت",
    translit: "Rahmat",
    meaning: { te: "కరుణ", en: "Mercy" },
    note: { te: "రహమత్ అత్యంత మధురమైన ఉర్దూ పదం — దైవ కరుణలో మూలపడ్డది. అల్లాహ్ యొక్క రహమత్ సర్వవ్యాపి.", en: "رحمت is one of the most beautiful words in Urdu — rooted in divine compassion. Allah's rahmat encompasses all things." },
  },
  {
    glyph: "محبت",
    translit: "Muhabbat",
    meaning: { te: "ప్రేమ", en: "Love" },
    note: { te: "ముహబ్బత్-ఎ-రసూల్ ﷺ ఇస్లామిక్ విశ్వాసానికి కేంద్రం. ఉర్దూ కవిత్వంలో అత్యంత మధురమైన పదం.", en: "Muhabbat-e-Rasool ﷺ (love of the Prophet) is central to Islamic faith. The sweetest word in Urdu poetry." },
  },
  {
    glyph: "صبر",
    translit: "Sabr",
    meaning: { te: "సహనం", en: "Patience" },
    note: { te: "నిశ్చయంగా అల్లాహ్ సబ్ర్ చేసే వారితో ఉంటాడు (ఖుర్ఆన్ 2:153). ఇస్లాంలో అత్యున్నత గుణాలలో ఒకటి.", en: "Verily, Allah is with those who have sabr (Quran 2:153). One of the highest virtues in Islam." },
  },
  {
    glyph: "شکر",
    translit: "Shukar",
    meaning: { te: "కృతజ్ఞత", en: "Gratitude" },
    note: { te: "మీరు కృతజ్ఞులైతే నేను మీకు ఇంకా ఇస్తాను (ఖుర్ఆన్ 14:7). శుకర్ దీవెనలను పెంచుతుంది.", en: "If you are grateful, I will give you more (Quran 14:7). Shukar multiplies blessings." },
  },
  {
    glyph: "ایمان",
    translit: "Iman",
    meaning: { te: "విశ్వాసం", en: "Faith" },
    note: { te: "ముస్లిం జీవితానికి మరియు గుర్తింపుకు పునాది. నిజమైన ఈమాన్ హృదయంలో ఉంటుంది.", en: "The foundation of a Muslim's life and identity. True iman lives in the heart." },
  },
  {
    glyph: "توبہ",
    translit: "Tawbah",
    meaning: { te: "పశ్చాత్తాపం", en: "Repentance" },
    note: { te: "అల్లాహ్ పశ్చాత్తాప పడే వారిని ప్రేమిస్తాడు (ఖుర్ఆన్ 2:222). తౌబహ్ ద్వారం ఎల్లప్పుడూ తెరుచుకుని ఉంటుంది.", en: "Allah loves those who sincerely repent (Quran 2:222). The door of tawbah is always open." },
  },
  {
    glyph: "نیت",
    translit: "Niyyat",
    meaning: { te: "ఉద్దేశ్యం", en: "Intention" },
    note: { te: "చర్యలు వాటి ఉద్దేశ్యాలచే తీర్మానించబడతాయి — ప్రసిద్ధ హదీస్ నుండి ముఖ్యమైన ఇస్లామిక్ సూత్రం.", en: "Actions are judged by their intentions — a key Islamic principle from the famous hadith." },
  },
  {
    glyph: "دعا",
    translit: "Dua",
    meaning: { te: "దువా", en: "Supplication" },
    note: { te: "దువా విశ్వాసి యొక్క ఆయుధం. ఇది ఆరాధన యొక్క సారాంశం (హదీస్).", en: "Dua is the weapon of the believer. It is the essence of worship (Hadith)." },
  },
  {
    glyph: "جنت",
    translit: "Jannat",
    meaning: { te: "స్వర్గం", en: "Paradise" },
    note: { te: "సద్గుణం గలవారికి శాశ్వత నివాసం. ఆశించగలిగే అత్యంత గొప్ప ప్రతిఫలం.", en: "The eternal abode of the righteous. The greatest reward one can hope for." },
  },
  {
    glyph: "تقویٰ",
    translit: "Taqwa",
    meaning: { te: "అల్లాహ్ భయం", en: "God-consciousness" },
    note: { te: "ఉత్తమ వనరు తఖ్వా (ఖుర్ఆన్ 2:197). అల్లాహ్ దృష్టిలో వ్యక్తి విలువకు కొలమానం.", en: "The best provision is taqwa (Quran 2:197). The measure of a person's worth before Allah." },
  },
  {
    glyph: "علم",
    translit: "Ilm",
    meaning: { te: "జ్ఞానం", en: "Knowledge" },
    note: { te: "జ్ఞానాన్ని అన్వేషించడం ప్రతి ముస్లిముపై తప్పనిసరి (హదీస్). అవతరించిన మొదటి పదం \"ఇఖ్రా\" — చదువు.", en: "Seeking knowledge is obligatory on every Muslim (Hadith). The first word revealed was Iqra — Read." },
  },
  {
    glyph: "ذکر",
    translit: "Zikr",
    meaning: { te: "స్మరణ", en: "Remembrance" },
    note: { te: "అల్లాహ్ యొక్క జికర్‌లో హృదయాలు శాంతి పొందుతాయి (ఖుర్ఆన్ 13:28). ఆత్మకు పోషణ.", en: "Hearts find peace in zikr of Allah (Quran 13:28). The nourishment of the soul." },
  },
  {
    glyph: "برکت",
    translit: "Barkat",
    meaning: { te: "దీవెన", en: "Blessing" },
    note: { te: "ఉర్దూలో ప్రేమించబడిన పదం — జీవనాధారంలో, సమయంలో, పిల్లల్లో బరకత్. రోజువారీ దువా.", en: "A cherished word in Urdu — barkat in rizq, time, children, and relationships. A common daily dua." },
  },
  {
    glyph: "ہدایت",
    translit: "Hidayat",
    meaning: { te: "మార్గదర్శనం", en: "Guidance" },
    note: { te: "ఖుర్ఆన్ మానవాళికి హిదాయత్ (ఖుర్ఆన్ 2:185). అల్లాహ్ ఇవ్వగలిగే అత్యంత గొప్ప బహుమతి.", en: "The Quran is hidayat for mankind (Quran 2:185). The greatest gift Allah can give." },
  },
  {
    glyph: "مغفرت",
    translit: "Maghfirat",
    meaning: { te: "క్షమాపణ", en: "Forgiveness" },
    note: { te: "నిష్కపటమైన వారికి అల్లాహ్ మఘ్ఫిరత్ అపరిమితం. అల్-గఫ్ఫార్ (మన్నించే వాడు) అల్లాహ్ నామాలలో ఒకటి.", en: "Allah's maghfirat is unlimited for the sincere. Al-Ghaffar (The Oft-Forgiving) is a name of Allah." },
  },
  {
    glyph: "یقین",
    translit: "Yaqin",
    meaning: { te: "నిశ్చయత", en: "Certainty" },
    note: { te: "నిశ్చయత (యఖీన్) వచ్చే వరకు నీ ప్రభువును ఆరాధించు (ఖుర్ఆన్ 15:99). విశ్వాసంలో దృఢ నిశ్చయం.", en: "Worship your Lord until certainty (yaqin) comes to you (Quran 15:99). Firm conviction in faith." },
  },
  {
    glyph: "صدق",
    translit: "Sidq",
    meaning: { te: "సత్యం", en: "Truthfulness" },
    note: { te: "సత్యవాదులతో ఉండండి (ఖుర్ఆన్ 9:119). మాటలో, పనులలో, ఉద్దేశ్యంలో సిద్ఖ్.", en: "Be with the truthful (Quran 9:119). Sidq in speech, action, and intention." },
  },
  {
    glyph: "اخلاص",
    translit: "Ikhlas",
    meaning: { te: "నిజాయితీ", en: "Sincerity" },
    note: { te: "అల్లాహ్ కోసం మాత్రమే స్వచ్ఛమైన భక్తి. ఇఖ్లాస్ సూరహ్ 112 పేరు కూడా — నిజాయితీ అధ్యాయం.", en: "Pure devotion for Allah alone. Also the name of Surah 112 — the chapter of sincerity." },
  },
  {
    glyph: "سکون",
    translit: "Sukoon",
    meaning: { te: "శాంతి", en: "Tranquility" },
    note: { te: "నిజమైన సుకూన్ అల్లాహ్ జికర్‌లో లభిస్తుంది. అన్ని అర్థాలను అతిక్రమించే శాంతి.", en: "True sukoon is found in the remembrance of Allah. The peace that passes all understanding." },
  },
  {
    glyph: "رزق",
    translit: "Rizq",
    meaning: { te: "జీవనాధారం", en: "Provision" },
    note: { te: "అన్ని రిజ్‌ఖ్ అల్లాహ్ నుండే వస్తుంది (ఖుర్ఆన్ 51:58). ఉర్దూ మాట్లాడే ఇళ్ళలో రోజువారీ వాడే పదం.", en: "All rizq comes from Allah alone (Quran 51:58). A word used daily in Urdu-speaking households." },
  },
  {
    glyph: "توکل",
    translit: "Tawakkul",
    meaning: { te: "అల్లాహ్‌పై నమ్మకం", en: "Trust in Allah" },
    note: { te: "ఒంటె కట్టు, ఆపై అల్లాహ్‌పై తవక్కుల్ పెట్టు. కృషితో అల్లాహ్ పై ఆధారపడటం మధ్య సమతుల్యత.", en: "Tie your camel, then put your tawakkul in Allah. Balance effort with reliance on Allah." },
  },
  {
    glyph: "عدل",
    translit: "Adl",
    meaning: { te: "న్యాయం", en: "Justice" },
    note: { te: "అల్లాహ్ న్యాయాన్ని మరియు మంచి ప్రవర్తనను ఆదేశిస్తున్నాడు (ఖుర్ఆన్ 16:90). ఇస్లామిక్ నాగరికతకు స్తంభం.", en: "Allah commands adl and good conduct (Quran 16:90). Justice is a pillar of Islamic civilization." },
  },
  {
    glyph: "امانت",
    translit: "Amanat",
    meaning: { te: "విశ్వసనీయత", en: "Trustworthiness" },
    note: { te: "అమానత్ నిలబెట్టడం నిజమైన విశ్వాసానికి చిహ్నం. ప్రవక్త ﷺ అల్-అమీన్ (విశ్వసనీయుడు) అని పిలువబడ్డారు.", en: "Fulfilling amanat is a mark of true faith. The Prophet ﷺ was known as Al-Amin (The Trustworthy)." },
  },
  {
    glyph: "حکمت",
    translit: "Hikmat",
    meaning: { te: "వివేకం", en: "Wisdom" },
    note: { te: "హిక్మత్ అల్లాహ్ దయతో లభించే బహుమతి (ఖుర్ఆన్ 2:269). ప్రతి పరిస్థితిలో సరిగ్గా వ్యవహరించే జ్ఞానం.", en: "Hikmat is a gift from Allah (Quran 2:269). Wisdom to act rightly in every situation." },
  },
  {
    glyph: "حیا",
    translit: "Haya",
    meaning: { te: "సిగ్గు", en: "Modesty" },
    note: { te: "హయా (సిగ్గు) పూర్తిగా మంచిదే — ఇది విశ్వాసం యొక్క శాఖ (హదీస్). అందరికీ ఒక గుణం.", en: "Haya (modesty) is entirely goodness — it is a branch of faith (Hadith). A virtue for all." },
  },
  {
    glyph: "تواضع",
    translit: "Tawadu",
    meaning: { te: "వినమ్రత", en: "Humility" },
    note: { te: "అల్లాహ్ కోసం వినమ్రత చూపించే వారిని అల్లాహ్ ఉన్నతం చేస్తాడు. తవాదు విశ్వాసికి అలంకారం.", en: "Whoever humbles himself for Allah, Allah elevates him. Tawadu is the adornment of the believer." },
  },
  {
    glyph: "احسان",
    translit: "Ihsan",
    meaning: { te: "శ్రేష్ఠత", en: "Excellence" },
    note: { te: "అల్లాహ్‌ను చూస్తున్నట్లు ఆరాధించడం (జిబ్రీల్ హదీస్). ఆధ్యాత్మిక ఆచరణలో అత్యున్నత స్థాయి.", en: "To worship Allah as if you see Him (Hadith of Jibreel). The highest level of spiritual practice." },
  },
  {
    glyph: "قناعت",
    translit: "Qanaat",
    meaning: { te: "సంతృప్తి", en: "Contentment" },
    note: { te: "ఖనాత్ (సంతృప్తి) శాశ్వత నిధి (హదీస్). అల్లాహ్ ఇచ్చిన దానిలో ఆనందం కనుగొనడం.", en: "Qanaat (contentment) is an everlasting treasure (Hadith). Finding joy in what Allah has given." },
  },
  {
    glyph: "وفا",
    translit: "Wafa",
    meaning: { te: "విధేయత", en: "Loyalty" },
    note: { te: "సంబంధాలలో వఫా ఉన్నత సచ్చీలత చిహ్నం. ఒప్పందాలు నెరవేర్చడం ఇస్లాంలో ప్రశంసనీయం.", en: "Wafa in relationships is a mark of high character. Fulfilling covenants is praised in Islam." },
  },
  {
    glyph: "خلوص",
    translit: "Khulus",
    meaning: { te: "హృదయ శుద్ధి", en: "Purity of Heart" },
    note: { te: "ఖులూస్ — హృదయ శుద్ధి మరియు నిజాయితీ ఉద్దేశ్యం — సేవకుడిని అల్లాహ్‌తో కలిపే వెలుతురు.", en: "Khulus — purity of heart and sincere intention — is the light that connects the servant to Allah." },
  },
];

export const urduPhrases: Phrase[] = [
  {
    glyph: "السلام علیکم",
    translit: { te: "అస్-సలామ్ అలైకుమ్", en: "As-salam alaikum" },
    meaning: { te: "మీపై శాంతి కలుగుగాక — అభివాదనం.", en: "Peace be upon you — the greeting." },
  },
  {
    glyph: "شکریہ",
    translit: { te: "శుక్రియా", en: "Shukriya" },
    meaning: { te: "ధన్యవాదాలు.", en: "Thank you." },
  },
  {
    glyph: "خوش آمدید",
    translit: { te: "ఖుష్ ఆమదీద్", en: "Khush Aamadeed" },
    meaning: { te: "స్వాగతం.", en: "Welcome." },
  },
  {
    glyph: "اللہ حافظ",
    translit: { te: "అల్లాహ్ హాఫిజ్", en: "Allah Hafiz" },
    meaning: { te: "వీడ్కోలు — అల్లాహ్ మిమ్మల్ని కాపాడుగాక.", en: "Goodbye — may Allah protect you." },
  },
  {
    glyph: "معاف کیجیے",
    translit: { te: "మాఫ్ కీజియే", en: "Maaf kijiye" },
    meaning: { te: "క్షమించండి.", en: "Excuse me, or I am sorry." },
  },
  {
    glyph: "کیا حال ہے؟",
    translit: { te: "క్యా హాల్ హై?", en: "Kya haal hai?" },
    meaning: { te: "మీరు ఎలా ఉన్నారు?", en: "How are you?" },
  },
  {
    glyph: "مہربانی",
    translit: { te: "మెహర్బానీ", en: "Meharbani" },
    meaning: { te: "దయ, లేదా దయచేసి.", en: "Kindness, or please." },
  },
  {
    glyph: "ٹھیک ہوں",
    translit: { te: "ఠీక్ హూఁ", en: "Theek hoon" },
    meaning: { te: "నేను బాగున్నాను.", en: "I am fine." },
  },
];
