/* Pull the full lesson bodies out of the legacy site's shared data files.

   assets/data/*-lessons.js holds 54 complete lessons across seven portals —
   intro, sections with their own comprehension checks, takeaways, quizzes,
   common mistakes, FAQs, revision points and further reading, all bilingual.
   The premium build had none of it: the portals listed lesson titles and the
   lessons themselves did not exist as pages.

   The files assign to window.IF_LESSONS, so each is run in a vm sandbox with
   a stub window rather than parsed.

   Usage: node scripts/extract-lessons.mjs [path-to-static-site]
*/
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = path.resolve(process.argv[2] || "../Islamic Front/projects/islamic-front-website");
const OUT = path.join(ROOT, "src/content/lessons.ts");

/** Legacy data file -> the premium route that owns those lessons. */
const PORTALS = [
  { file: "quran-lessons.js", portal: "learn-quran" },
  { file: "salah-lessons.js", portal: "learn-salah" },
  { file: "seerah-lessons.js", portal: "seerah" },
  { file: "history-lessons.js", portal: "islamic-history" },
  { file: "kids-lessons.js", portal: "kids-islam" },
  { file: "arabic-lessons.js", portal: "learn-arabic" },
  { file: "urdu-lessons.js", portal: "learn-urdu" },
];

function load(file) {
  const src = fs.readFileSync(path.join(SITE, "assets/data", file), "utf8");
  const sandbox = { window: {} };
  vm.runInNewContext(src, sandbox, { timeout: 8000 });
  const data = sandbox.window.IF_LESSONS;
  if (!data?.lessons) throw new Error(`No IF_LESSONS.lessons in ${file}`);
  return data;
}

/* Field pairs come as x_en/x_te or {en,te}. Both fold to { te, en }. */
const bi = (o) => (o && typeof o === "object" ? { te: o.te ?? "", en: o.en ?? "" } : null);
const biPair = (o, base) =>
  o?.[`${base}_en`] !== undefined ? { te: o[`${base}_te`] ?? "", en: o[`${base}_en`] ?? "" } : null;

const list = (arr, fn) => (Array.isArray(arr) ? arr.map(fn).filter(Boolean) : []);

function normSection(s) {
  const out = {
    heading: biPair(s, "h") ?? bi(s.heading) ?? biPair(s, "title") ?? null,
    body: bi(s.body) ?? biPair(s, "b") ?? bi(s.text) ?? null,
  };
  if (s.check) {
    out.check = {
      question: biPair(s.check, "q"),
      options: list(s.check.opts, bi),
      answer: typeof s.check.ans === "number" ? s.check.ans : 0,
    };
  }
  return out.heading || out.body ? out : null;
}

const normQuiz = (q) => ({
  question: biPair(q, "q"),
  options: list(q.opts, bi),
  answer: typeof q.ans === "number" ? q.ans : 0,
});

const normFaq = (f) => ({ question: biPair(f, "q"), answer: biPair(f, "a") });

const normLink = (l) =>
  l && l.label && l.url ? { label: String(l.label), url: String(l.url) } : null;

/* Seerah and Kids number their lessons l1..l8 and k1..k8, which makes for a
   URL nobody can read or share meaningfully. Where a slug is that opaque, one
   is derived from the English title instead; descriptive slugs are kept. */
function readableSlug(id, titleEn) {
  if (!/^[a-z]\d+$/i.test(id)) return id;
  const derived = titleEn
    .replace(/^Level\s*\d+\s*[—–-]\s*/i, "")
    .toLowerCase()
    .replace(/\(.*?\)/g, " ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return derived || id;
}

const lessons = [];
const summary = [];

for (const { file, portal } of PORTALS) {
  const data = load(file);
  let n = 0;
  for (const l of data.lessons) {
    lessons.push({
      slug: readableSlug(String(l.id), l.title_en ?? ""),
      portal,
      title: { te: l.title_te ?? "", en: l.title_en ?? "" },
      intro: bi(l.intro),
      sections: list(l.sections, normSection),
      takeaways: list(l.takeaways, bi),
      didYouKnow: list(l.didyouknow, bi),
      reflect: list(l.reflect, bi),
      mistakes: list(l.mistakes, bi),
      faqs: list(l.faqs, normFaq).filter((f) => f.question && f.answer),
      quiz: list(l.quiz, normQuiz).filter((q) => q.question && q.options.length),
      revision: list(l.revision, bi),
      summary: bi(l.summary),
      apply: bi(l.apply),
      reading: [...list(l.reading, normLink), ...list(l.refs, normLink)].filter(
        (v, i, a) => a.findIndex((x) => x.url === v.url) === i,
      ),
    });
    n++;
  }
  summary.push(`  ${portal.padEnd(16)} ${String(n).padStart(2)} lessons`);
}

/* A lesson whose slug collides with another in the same portal would make one
   of them unreachable, since the route is /[portal]/[slug]. */
const seen = new Set();
for (const l of lessons) {
  const key = `${l.portal}/${l.slug}`;
  if (seen.has(key)) throw new Error(`Duplicate lesson route: ${key}`);
  seen.add(key);
}

const out = `/* AUTO-GENERATED by scripts/extract-lessons.mjs — do not edit by hand.
   Source: the legacy static site's assets/data/*-lessons.js.
   Re-run to refresh. ${lessons.length} lessons across ${PORTALS.length} portals. */

export type Bi = { te: string; en: string };

export type QuizItem = {
  question: Bi;
  options: Bi[];
  /** Index into options. */
  answer: number;
};

export type LessonSection = {
  heading: Bi | null;
  body: Bi | null;
  /** An inline comprehension check, where the lesson has one. */
  check?: QuizItem;
};

export type Lesson = {
  slug: string;
  /** Route segment of the portal this lesson belongs to. */
  portal: string;
  title: Bi;
  intro: Bi | null;
  sections: LessonSection[];
  takeaways: Bi[];
  didYouKnow: Bi[];
  reflect: Bi[];
  mistakes: Bi[];
  faqs: { question: Bi; answer: Bi }[];
  quiz: QuizItem[];
  revision: Bi[];
  summary: Bi | null;
  apply: Bi | null;
  reading: { label: string; url: string }[];
};

export const lessons: Lesson[] = ${JSON.stringify(lessons, null, 2)};

export const lessonsByPortal = (portal: string) => lessons.filter((l) => l.portal === portal);

export const findLesson = (portal: string, slug: string) =>
  lessons.find((l) => l.portal === portal && l.slug === slug) ?? null;
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out, "utf8");

const total = (k) => lessons.reduce((a, l) => a + (Array.isArray(l[k]) ? l[k].length : 0), 0);
console.log(`Wrote ${path.relative(ROOT, OUT).split(path.sep).join("/")}`);
console.log(summary.join("\n"));
console.log(
  `  totals: ${lessons.length} lessons, ${total("sections")} sections, ${total("quiz")} quiz questions, ` +
    `${total("faqs")} FAQs, ${total("takeaways")} takeaways, ${total("mistakes")} mistakes`,
);
