/* Pull the narrative datasets out of the legacy Seerah, Islamic History and
   Kids portals.

   These arrays hold the substance those portals are for: the timeline of the
   Prophet's life, the character traits with their evidence, the caliphs and
   empires and cities, the prophet stories for children. The premium build
   showed a fraction of each.

   Fields come in `x_en` / `x_te` pairs, which are folded into { te, en }.
   Icon fields hold raw inline SVG from the legacy markup and are dropped —
   the premium build draws its own icons.

   Usage: node scripts/extract-portals.mjs [path-to-static-site]
*/
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = path.resolve(process.argv[2] || "../Islamic Front/projects/islamic-front-website");
const OUT = path.join(ROOT, "src/content/portals.ts");

function extractArray(file, name) {
  const src = fs.readFileSync(file, "utf8");
  const start = src.search(new RegExp(`(?:var|const|let)\\s+${name}\\s*=\\s*\\[`));
  if (start === -1) throw new Error(`${name} not found in ${path.basename(file)}`);
  const open = src.indexOf("[", start);
  let depth = 0;
  let end = -1;
  let quote = null;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === "'" || c === '"' || c === "`") quote = c;
    else if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) throw new Error(`Unterminated ${name} in ${path.basename(file)}`);
  return vm.runInNewContext(src.slice(open, end), Object.create(null), { timeout: 3000 });
}

/** Fold `x_en`/`x_te` pairs into { te, en }; drop SVG and unpaired noise. */
function normalise(entry) {
  const out = {};
  const seen = new Set();
  for (const [k, v] of Object.entries(entry)) {
    if (typeof v !== "string") continue;
    if (v.includes("<svg")) continue; // legacy inline icon markup
    // Two conventions in the legacy code: bio_en/bio_te and en_s/te_s.
    const suffix = k.match(/^(.*)_(en|te)$/);
    const prefix = k.match(/^(en|te)_(.*)$/);
    if (suffix || prefix) {
      const base = suffix ? suffix[1] : prefix[2];
      const side = suffix ? suffix[2] : prefix[1];
      const otherKey = suffix
        ? `${base}_${side === "en" ? "te" : "en"}`
        : `${side === "en" ? "te" : "en"}_${base}`;
      if (seen.has(base)) continue;
      const other = entry[otherKey];
      if (typeof other !== "string") continue;
      out[base || "text"] = side === "en" ? { te: other, en: v } : { te: v, en: other };
      seen.add(base);
    } else if (k === "en" || k === "te") {
      if (seen.has("title")) continue;
      if (typeof entry.en === "string" && typeof entry.te === "string") {
        out.title = { te: entry.te, en: entry.en };
        seen.add("title");
      }
    } else if (k === "ar") {
      out.arabic = v;
    }
  }
  return out;
}

const esc = (s) => JSON.stringify(s);

function render(entries) {
  return entries
    .map((e) => {
      const lines = Object.entries(e).map(([k, v]) =>
        typeof v === "string"
          ? `    ${k}: ${esc(v)},`
          : `    ${k}: { te: ${esc(v.te)}, en: ${esc(v.en)} },`,
      );
      return `  {\n${lines.join("\n")}\n  },`;
    })
    .join("\n");
}

const SETS = [
  { export: "seerahEvents", portal: "seerah", array: "EVENTS" },
  { export: "seerahCharacter", portal: "seerah", array: "CHAR" },
  { export: "historyEras", portal: "islamic-history", array: "EVENTS" },
  { export: "historyPeople", portal: "islamic-history", array: "PEOPLE" },
  { export: "historyEmpires", portal: "islamic-history", array: "EMPIRES" },
  { export: "historyCities", portal: "islamic-history", array: "CITIES" },
  { export: "kidsProphets", portal: "kids-islam", array: "PROPHETS" },
  { export: "womensWorship", portal: "womens-guidance", array: "WORSHIP_DATA" },
  { export: "womensFaqs", portal: "womens-guidance", array: "FAQS_DATA" },
];

const blocks = [];
const summary = [];

for (const s of SETS) {
  const file = path.join(SITE, "knowledge-center", s.portal, "index.html");
  const raw = extractArray(file, s.array);
  const rows = raw.map(normalise).filter((r) => Object.keys(r).length > 0);
  const fields = [...new Set(rows.flatMap((r) => Object.keys(r)))];
  blocks.push(
    `/** ${s.portal} · ${s.array} — ${rows.length} entries.\n    Fields: ${fields.join(", ")} */\nexport const ${s.export}: PortalEntry[] = [\n${render(rows)}\n];`,
  );
  summary.push(`  ${s.export.padEnd(18)} ${String(rows.length).padStart(3)} entries  [${fields.join(", ")}]`);
}

const out = `/* AUTO-GENERATED by scripts/extract-portals.mjs — do not edit by hand.
   Source: the legacy static site's Seerah, Islamic History and Kids portals.
   Re-run to refresh.

   Entries are loosely typed on purpose: each legacy array carries a different
   set of fields, and forcing them into one rigid shape would mean either
   dropping data or inventing empty values. Consumers read the fields they
   need and check for presence. */

export type Bi = { te: string; en: string };
export type PortalEntry = { arabic?: string } & Record<string, Bi | string | undefined>;

${blocks.join("\n\n")}
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out, "utf8");
console.log(`Wrote ${path.relative(ROOT, OUT).split(path.sep).join("/")}`);
console.log(summary.join("\n"));
