/* Pull the Arabic and Urdu vocabulary and phrase sets out of the legacy site.

   Both portal pages declare WORDS and PHRASES arrays. Each word carries a
   transliteration, both meanings, and a note explaining why the word matters
   — the kind of detail that makes a vocabulary list worth reading rather than
   just scrolling. The premium build had six words and no phrases at all.

   Usage: node scripts/extract-vocab.mjs [path-to-static-site]
*/
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SITE = path.resolve(process.argv[2] || "../Islamic Front/projects/islamic-front-website");
const OUT = path.join(ROOT, "src/content/vocabulary.ts");

function extractArray(file, name) {
  const src = fs.readFileSync(file, "utf8");
  const start = src.search(new RegExp(`(?:var|const|let)\\s+${name}\\s*=\\s*\\[`));
  if (start === -1) throw new Error(`${name} not found in ${file}`);
  const open = src.indexOf("[", start);
  let depth = 0;
  let end = -1;
  let quote = null;
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === "'" || c === '"' || c === "`") quote = c;
    else if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) throw new Error(`Unterminated ${name} in ${file}`);
  return vm.runInNewContext(src.slice(open, end), Object.create(null), { timeout: 3000 });
}

const esc = (s) => JSON.stringify(s ?? "");

const emitWords = (list) =>
  list
    .map((w) =>
      [
        "  {",
        `    glyph: ${esc(w.ar ?? w.ur)},`,
        `    translit: ${esc(w.tr)},`,
        `    meaning: { te: ${esc(w.te)}, en: ${esc(w.en)} },`,
        `    note: { te: ${esc(w.note_te)}, en: ${esc(w.note)} },`,
        "  },",
      ].join("\n"),
    )
    .join("\n");

const emitPhrases = (list) =>
  list
    .map((p) =>
      [
        "  {",
        `    glyph: ${esc(p.ar ?? p.ur)},`,
        `    translit: { te: ${esc(p.tr_te)}, en: ${esc(p.tr_en)} },`,
        `    meaning: { te: ${esc(p.m_te)}, en: ${esc(p.m_en)} },`,
        "  },",
      ].join("\n"),
    )
    .join("\n");

const src = (p) => path.join(SITE, "knowledge-center", p, "index.html");
const arabicWords = extractArray(src("learn-arabic"), "WORDS");
const arabicPhrases = extractArray(src("learn-arabic"), "PHRASES");
const urduWords = extractArray(src("learn-urdu"), "WORDS");
const urduPhrases = extractArray(src("learn-urdu"), "PHRASES");

const out = `/* AUTO-GENERATED by scripts/extract-vocab.mjs — do not edit by hand.
   Source: the legacy static site's language portals. Re-run to refresh. */

export type Bi = { te: string; en: string };

export type VocabWord = {
  glyph: string;
  translit: string;
  meaning: Bi;
  /** Why this word is worth knowing — usage, Quranic frequency, nuance. */
  note: Bi;
};

export type Phrase = {
  glyph: string;
  translit: Bi;
  meaning: Bi;
};

export const arabicWords: VocabWord[] = [
${emitWords(arabicWords)}
];

export const arabicPhrases: Phrase[] = [
${emitPhrases(arabicPhrases)}
];

export const urduWords: VocabWord[] = [
${emitWords(urduWords)}
];

export const urduPhrases: Phrase[] = [
${emitPhrases(urduPhrases)}
];
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out, "utf8");

const withNote = (l) => l.filter((w) => w.note && w.note_te).length;
console.log(`Wrote ${path.relative(ROOT, OUT).split(path.sep).join("/")}`);
console.log(`  arabic: ${arabicWords.length} words (${withNote(arabicWords)} annotated), ${arabicPhrases.length} phrases`);
console.log(`  urdu:   ${urduWords.length} words (${withNote(urduWords)} annotated), ${urduPhrases.length} phrases`);
